### ISSUE TITLE
How can i create multiple images from build.gradle

### ISSUE THREAD

**Issue by saurabh4studies** [GoogleContainerTools/jib#1614] opened 2019-04-10 07:05 UTC
**Description of the issue**:

I need to have running MSSQL DB, Elasticsearch in order to make my application fully functional. So far i am able to create docker image as per below gradle script. 

Is there any way i can create different images for MSSQL DB and elasticsearch ?

**Environment**: 
OS: Window 7
JDK: Open JDK 8
Gradle: 5.2.1

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'com.google.cloud.tools.jib' version '1.0.2'
    id 'war'
}

jib {
    from {
        image = 'tomcat:8.5'
    }
    container {
        appRoot = '/usr/local/tomcat/webapps/eVA'
        ports = ['8080/tcp']
    }
    to {
        image = 'ecw-assistant:tomcat8.5'
    }
}

tasks.build.dependsOn { tasks.jibDockerBuild }
```

**Additional Information**:

**Comment by chanseokoh** [comment] 2019-04-10 15:01
I believe this is a duplicate of #1615 which you created. Closing.

**Closed by chanseokoh** 2019-04-10 15:01 UTC
