### ISSUE TITLE
How to starting project using Alpine's Tini ？

### ISSUE THREAD

**Issue by goudai** [GoogleContainerTools/jib#2386] opened 2020-04-06 11:53 UTC
I want to know how to configure  to achieve the following effect
entrypoint set to
```bash
 [tini,java, --add-opens, java.base/sun.nio.ch=ALL-UNNAMED, -cp, /app/resources:/app/classes:/app/libs/*, ...
```
My application will use tini to start, ensure pid! = 1, if it is equal to 1, then java related tools will not be available, and there will be a zombie process. There is an [ISSUS](https://github.com/docker-library/openjdk/issues/76)

**Comment by loosebazooka** [comment] 2020-04-06 12:17
You could use the entrypoint configuration parameter (in the container config)?
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#container-object
https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#container-closure

**Comment by goudai** [comment] 2020-04-06 12:22
Can Add a parameter? the meaning of this parameter is to add a custom command before java.

**Comment by loosebazooka** [comment] 2020-04-06 12:34
No, you would need to do this in you jib configuration. Are you using maven or gradle?

**Comment by goudai** [comment] 2020-04-06 12:40
I don't want to write any configuration to the pom file, I use the following command to build
```bash
mvn com.google.cloud.tools:jib-maven-plugin:build \
-Djib.to.auth.username=247687009@qq.com \
-Djib.to.auth.password=*** \
-Djib.container.jvmFlags=--add-opens,java.base/sun.nio.ch=ALL-UNNAMED \
-Djib.from.image=f** \
-Dimage=**
```
It ’s easy to use, and I really like this way.

**Comment by loosebazooka** [comment] 2020-04-06 12:42
so the same way you have configured `-Djib.container.jvmFlags` you would configure `-Djib.container.entrypoint=my,entrypoint,values`

**Comment by goudai** [comment] 2020-04-06 12:45
But I only want to set up a tini, and I don't want to change the default entrypoint. I think the default entrypoint is easy to use and very good. According to your suggestions, I will not be able to enjoy the convenience it brings.

**Comment by goudai** [comment] 2020-04-06 12:48
I want to avoid the pid of the container equal to 1 without changing the entrypoint and maintaining this pleasant experience. This is my original intention.

**Comment by goudai** [comment] 2020-04-06 12:56
I think many people have this kind of demand, because in the actual production container, we did not use a program like Tini at the beginning, resulting in many pods that cannot be killed, and all jvm tools cannot be used normally. This will be a disaster for troubleshooting.

**Comment by loosebazooka** [comment] 2020-04-06 13:27
Right, so you're asking for something like #894 ?

**Comment by chanseokoh** [comment] 2020-04-06 13:43
Prepending `tini` (or adjusting `entrypoint`) could also be done with the proposed [Jib extension framework](https://github.com/GoogleContainerTools/jib/issues/1962#issuecomment-599235543), once implemented. Not that this must be done through the extension framework.

**Comment by goudai** [comment] 2020-04-06 14:22
I want a pure extension point that can precede the java command. I don't have to modify the entrypoint and I don't have to write xml. such as
```bash
jib.container.javaBefore = tini
```

**Comment by goudai** [comment] 2020-04-09 07:26
Friends, recommend or suggest an elegant solution. I especially need it.
Thanks!

**Comment by chanseokoh** [comment] 2020-04-09 14:36
As @loosebazooka said, #894 may work to some extent; this would certainly be able to do done purely on the command line once implemented. The problem is that we found it a non-trivial undertaking to implement #894 due to our rigid config processing architecture.

Other than that, at the moment, I can't really think of a way to achieve this if you want to do this only on the command line, unless you are willing to set the entire entrypoint. And I don't think we'll add a special configuration like `jib.container.javaBefore` only because there's a request to achieve this only through command-line. The config option seems too specific.

**Comment by goudai** [comment] 2020-04-11 09:55
Hi, friends, I found a solution in the kubernetes documentation. https://v1-16.docs.kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/。

**Comment by chanseokoh** [comment] 2020-04-12 03:47
Glad to to hear you found a workaround for your runtime platform. Based on all of our discussions, I believe we can close this as a dup of #894.

**Closed by chanseokoh** 2020-04-12 03:47 UTC

**Comment by mfriedenhagen** [comment] 2020-04-29 05:04
@goudai , I solved this with a custom image, which includes dumb-init and creating a short shell script called java in /usr/local/bin, see #894

**Comment by chanseokoh** [comment] 2020-06-11 21:26
FTR: https://github.com/GoogleContainerTools/jib/issues/894#issuecomment-642935267

**Comment by Dr-wgy** [comment] 2023-11-27 14:26
> As @loosebazooka said, #894 may work to some extent; this would certainly be able to do done purely on the command line once implemented. The problem is that we found it a non-trivial undertaking to implement #894 due to our rigid config processing architecture.
> 
> Other than that, at the moment, I can't really think of a way to achieve this if you want to do this only on the command line, unless you are willing to set the entire entrypoint. And I don't think we'll add a special configuration like `jib.container.javaBefore` only because there's a request to achieve this only through command-line. The config option seems too specific.
I use jib-maven-plugin 
                        <entrypoint>"/usr/bin/tini", "--","xxx,sh"</entrypoint>
                        
                        Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "\"/usr/bin/tini\"": stat "/usr/bin/tini": no such file or directory: unknown
