### ISSUE TITLE
Jib Gradle plugin fails with Gradle Play plugin

### ISSUE THREAD

**Issue by joschi** [GoogleContainerTools/jib#961] opened 2018-09-10 13:22 UTC
**Description of the issue**:

When trying to create a Docker image for a Gradle project using the [Gradle Play plugin](https://docs.gradle.org/4.10/userguide/play_plugin.html), the Jib Gradle plugin fails with the following message:

```text
> Could not find task 'classes' on project root project 'gradle-play-gib' - perhaps you did not apply the 'java' plugin?
```

The Jib Gradle plugin seems to hardcode a dependency on the `classes` task which is provided by the [Gradle Java plugin](https://docs.gradle.org/4.10/userguide/java_plugin.html#sec:java_tasks) but not by the Gradle Play plugin.

https://github.com/GoogleContainerTools/jib/blob/d1a2012ad0229d0c1cfac8d36397cad85bc8cb98/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java#L110

**Expected behavior**:

The Jib Gradle plugin should create a Docker image with the Play application and its dependencies.

**Steps to reproduce**:

* Clone https://github.com/joschi/gradle-play-jib (`git clone https://github.com/joschi/gradle-play-jib.git`)
* Run `./gradlew build`

**Environment**:

* macOS 10.13.6
* Java 1.8.0_181
* Gradle 4.9
* Jib Gradle plugin 0.9.10

**`jib-gradle-plugin` Configuration**:
```groovy
plugins {
    id 'play'
    id 'com.google.cloud.tools.jib' version '0.9.10'
}

version = '1.0.0'

repositories {
    jcenter()
}

model {
    components {
        play {
            platform play: '2.6.18', scala: '2.12', java: '1.8'
            injectedRoutesGenerator = true
        }
    }
    distributions {
        playBinary {
            baseName = project.name
        }
    }
    tasks.createPlayBinaryStartScripts {
        applicationName = project.name
    }
}
```
See also: https://github.com/joschi/gradle-play-jib

**Log output**:
```text
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradle-play-gib'.
> Could not find task 'classes' on project root project 'gradle-play-gib' - perhaps you did not apply the 'java' plugin?

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'gradle-play-gib'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:73)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:54)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:682)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:138)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:266)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:179)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:138)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:121)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:74)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Could not find task 'classes' on project root project 'gradle-play-gib' - perhaps you did not apply the 'java' plugin?
        at com.google.cloud.tools.jib.gradle.JibPlugin.lambda$apply$1(JibPlugin.java:137)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy26.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:187)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:184)
        at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1398)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:193)
        ... 91 more
Caused by: org.gradle.api.UnknownTaskException: Task with path 'classes' not found in root project 'gradle-play-gib'.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:414)
        at com.google.cloud.tools.jib.gradle.JibPlugin.lambda$apply$1(JibPlugin.java:110)
        ... 107 more
```

**Comment by loosebazooka** [comment] 2018-09-10 13:31
Hi @joschi, the play framework Gradle integration uses the Gradle experimental (and now deprecated) project model. We are intentionally not supporting that. I believe the solution is to have the gradle team (or someone) write a plugin for play using the current/standard plugin model.

**Comment by cricket007** [comment] 2018-12-07 05:21
Also running into this for trying out adding #347 for Play... Even the Play docs say the "default Maven layout" is experimental, so it's a lose-lose on those fronts.  

> using the current/standard plugin model

Is there more information on this? @loosebazooka 

> pull request to support the Gradle Play framework

If I understood the response correctly, that is an *external Gradle plugin* for Play that is not deemed experimental or deprecated, and not part of Jib. Correct me if I'm wrong.

**Comment by loosebazooka** [comment] 2019-04-11 21:13
@joschi @cricket007 sorry for not providing an update here.
See: https://docs.gradle.org/current/userguide/play_plugin.html

>Play is a modern web application framework. The Play plugin adds support for building, testing and running Play applications with Gradle.
>
>The Play plugin makes use of the Gradle [software model](https://docs.gradle.org/current/userguide/software_model.html#software_model).

The key is the use of the software model to build their applications. It's a deprecated pattern and we do not intend to build support for it because it is a maintenance burden. I think the current solution here is to build an application using the gradle `play` plugin and then maybe taking advantage of jib core to containerize your application.

>In case someone provided a pull request to support the Gradle Play framework, would you consider merging it?

This is *not* something we would do unfortunately. Our goal is to design a general purpose tool that is platform/framework agnostic. Adding in specialty code for a one-off framework doesn't fit our project goals.

However if you do find a solution (maybe using `jib-core`) we'd be happy to review and link to it with #347.

**Comment by aboyett** [comment] 2019-10-10 12:42
There is an [external Play plugin](https://gradle.github.io/playframework/) as noted in https://github.com/GoogleContainerTools/jib/issues/961#issuecomment-445126017. It specifically calls out *not* using the software model:
> This plugin is different from the Play plugin  shipped with the Gradle distribution. It’s developed and shipped  independently from the Gradle core functionality and does not use the  software model.

This plugin provides the `classes` task but the plugin doesn't configure this build in a way that jib can detect the mainclass (`play.core.server.NettyServer`). When passing the mainclass explicitly the application doesn't initialize properly, and visiting the webserver produces the following exception:

```
$ docker run --rm -p 9000:9000 localhost/play-jib-test:latest                                                                                                                                          
Play server process ID is 1                                                                                                                                                                                                                   
SLF4J: Class path contains multiple SLF4J bindings.                                                                                                                                                                                           
SLF4J: Found binding in [jar:file:/app/libs/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]                                                                                                                               
SLF4J: Found binding in [jar:file:/app/libs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]                                                                                                                                 
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.                                       
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]                             
[info] play - Application started (Prod)                                                                                                                                                                                                      
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000                                                                                                                                                                                     
[error] p.nettyException - Exception caught in Netty                                                                                                                                                                                          
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.headers()Lorg/jboss/netty/handler/codec/http/HttpHeaders;                   
        at play.core.server.netty.PlayDefaultUpstreamHandler.getHeaders(PlayDefaultUpstreamHandler.scala:366) ~[play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:87) ~[play_2.11-2.3.10.jar:2.3.10]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) ~[netty-http-pipelining-1.1.2.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:104) ~[netty-3.2.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.4.Final.jar:na]               
```

It's worth noting this gradle play plugin creates a distribution jar (installed into `/app/lib/` rather than `/app/cp/`) with an ordered classpath in the `Class-Path` field in META-INF/MANIFEST.MF. The provided shell script in dist tar created by the gradle play plugin passes this single jar as the classpath:
```
java -classpath /path/to/project/build/stage/main/lib/play-jib-test.jar play.core.server.NettyServer
```

It feels like this plugin is quite close to doing the right thing but some assistance would be appreciated to determine the correct gradle/jib configuration to make a play project work; or determine the modifications to this external play gradle plugin so it exposes the information jib needs to containerize a project correctly.

**Comment by loosebazooka** [comment] 2019-10-10 18:37
@aboyett can you provide us with a sample to play around with? I'm not familiar with how play framework works but the prospect of integration with jib doesn't sound too discouraging and I am hopeful there could be a solution.

**Comment by jamesward** [comment] 2019-10-16 00:16
This seems to be working for me.  Sample project:
https://github.com/jamesward/hello-play-gradle

**Comment by aboyett** [comment] 2019-10-16 07:37
Thanks for the example project @jamesward! I've modified the play-scala-starter-example project based on your modifications to achieve a usable result with play 2.6 (albeit without resources like CSS) at https://github.com/aboyett/play-scala-starter-example/tree/jib-gradle-2.6

What mainclass would you use with Play 2.3.x? `play.core.server.ProdServerStart` as used in the example was introduced in Play 2.4.0 and using the previous `play.core.server.NettyServer` mainclass yields the error in https://github.com/GoogleContainerTools/jib/issues/961#issuecomment-540555450

**Comment by aboyett** [comment] 2019-10-16 19:49
The documentation is inconsistent on supported version. This page indicates Play 2.3.x is supported https://gradle.github.io/playframework/#play_framework and a fix was merged for the Play 2.3.x route parser less than a month ago https://github.com/gradle/playframework/pull/94

The start script generated by the stage/dist works with the Grade Play plugin works, but the entrypoint generated by jib does not.

I think this discussion is a bit off-topic now that we have a confirmed working mechanism for Play 2.6 (and probably 2.4-2.7) It sounds like I should open a ticket against http://github.com/gradle/playframework to try to resolve the Play 2.3.x specific behavior.

**Comment by jamesward** [comment] 2019-10-16 19:51
Oh interesting.  yeah, their docs do have a conflict :)

Usually a NoSuchMethod error means there was some version misalignment with transitive deps.

**Comment by loosebazooka** [comment] 2020-03-10 14:43
Obsolete. If anyone is still interested in this issue, please try with the new Play Plugin: https://gradle.github.io/playframework/

**Closed by loosebazooka** 2020-03-10 14:43 UTC
