### ISSUE TITLE
Both the base image and push image addresses are HTTP and do not work

### ISSUE THREAD

**Issue by pog2g** [GoogleContainerTools/jib#2314] opened 2020-03-01 18:28 UTC
**Environment**:

- *Jib version: 2.1.0
- *Build tool: maven
- *OS: mac

**Description of the issue**:
* from image http and to image http,build image failure(allowInsecureRegistries value is true),can't use useCurrentTimestamp,The documentation does not provide an introduction.
* The document does not describe the setting sendCredentialsOverHttp
* If you can only use HTTPS which is most unreasonable, how can I get the HTTPS certificate on the Intranet (even less appropriate for self-signed certificates)

**`jib-maven-plugin` Configuration**: 
```
 <plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>2.1.0</version>
    <configuration>
        <from>
            <image>192.168.51.78:20069/library/openjdk:11.0.6-jre-slim</image>
        </from>
        <to>
            <image>192.168.51.78:20069/depttwo/${project.name}:${project.version}</image>
        </to>
        <container>
            <ports>
                <port>8080</port>
            </ports>
            <mainClass>com.Application</mainClass>
            <environment>
                <TZ>Asia/Shanghai</TZ>
            </environment>
        </container>
        <allowInsecureRegistries>true</allowInsecureRegistries>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>build</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Log output**: 
```
Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.1.0:build (default) on project security-manage: Build image failed, perhaps you should use a registry that supports HTTPS so credentials can be sent safely, or set the 'sendCredentialsOverHttp' system property to true

```

**Additional Information**:

**Comment by loosebazooka** [comment] 2020-03-01 18:47
We discourage the use of sendCrendentialsOverHttp. 

However, you can find information on it here: https://github.com/GoogleContainerTools/jib/issues/668 and here: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-diagnose-problems-pulling-or-pushing-from-remote-registries

**Comment by pog2g** [comment] 2020-03-01 18:54
@loosebazooka HTTP is definitely not an exception. There has to be a good solution.

**Comment by chanseokoh** [comment] 2020-03-01 20:16
@pog2g I understand the pain, but people should know that, over plain-HTTP, your username and password are passed **in plain test**, and that anyone in your intranet can easily see them. For example, it is extremely easy for your colleagues to see your bare password by just running a simple network tool.

[A Guide to Sniffing Out Passwords and Cookies](https://lifehacker.com/a-guide-to-sniffing-out-passwords-and-cookies-and-how-5853483
) says

> What Wireshark does is sniff out the packets being passed around your network—whether they're heading to or from your computer or to or from other computers on the same network as you—and let you poke around at the data passed back and forth in these packets.
>
> When you log into a web site, for example, your browser sends what's called a POST request to a server somewhere on there on the internet. Wireshark can capture that POST request, and if you know where to look, you can find your username and password in plain text—assuming you're logging into a site that isn't using a secured HTTPS connection,

> Similar to how it can capture usernames and passwords sent over HTTP connections, Wireshark can also capture cookies for you (or some other nefarious sniffer)

You wouldn't advertise your username/password to your colleges, would you? We are trying to make users who are not familiar with security aware the consequences of sending credentials over HTTP by requiring to set `-DsendCredentialsOverHttp`.

**Comment by chanseokoh** [comment] 2020-03-01 20:58
> Although can self-sign certificate, but how to deal with domain name resolution

Forgot to say: you don't need self-signed certificate. When using `<allowInsecureRegistries>`, Jib does send credentials even if it cannot verify the server. Insecure HTTPS (i.e., TLS/SSL verification failure) is still susceptible for attack, but at least it is not any near the degree of using plain HTTP. As long as you are not communicating over plain HTTP (even if it is insecure HTTPS), Jib will send credentials and you don't need `-DsendCredentialsOverHttp`. You just need to make your registry speak HTTPS, even if it is insecure.

**Comment by pog2g** [comment] 2020-03-02 01:20
@chanseokoh I think it's a little overthinking, since it's local, I certainly don't need to worry about security. Moreover, I used the jib of self-signed certificate to solve the problem, but it brought more trouble, because I needed to deal with the certificate problem when k8s and docker pulled the mirror, and everyone needed to deal with it. What's more, using HTTP offers more options. In addition, jib has alternative products. Why do I have to use the jib to bring me so many unnecessary troubles? I just recommend keeping HTTP

**Comment by pog2g** [comment] 2020-03-02 01:27
@chanseokoh Unless you can be sure that other systems are going your way, such as k8s or docker,There is no need to deal with pulling  image

**Comment by chanseokoh** [comment] 2020-03-02 17:29
@GoogleContainerTools/java-tools-build maybe it's not too much to ask to make `sendCredentialsOverHttp` configurable in `pom.xml` and `build.gradle` (which will be effective only when `allowInsecureRegistries` is set and the registry is plain HTTP).

**Comment by pog2g** [comment] 2020-03-03 08:33
@chanseokoh 
At present, the internal system of self-signed certificate is deadly, k8s, docker, kubesphere and Jenkins are not allowed to use, directly prompt: 'x509: certificate signed by unknown authority'. That's the cost of not getting the jib to use HTTP

**Comment by raizoor** [comment] 2020-03-03 13:19
I think that's a good problem to discuss. Local development normally are more "light".
Maybe a specificly feature to " local development ", printing a lot of warnings with problems to use that.

Jib need to be secure at default, but it's a problem transform it "insecure" if the user need that?

**Comment by chanseokoh** [comment] 2020-03-03 13:38
We realized we have an open issue to allow fine-grained control of `allowInsecureRegistries` and `sendCredentialsOverHttp` (#1923). I will close this as a duplicate of #1923.

For now, please use `-DsendCredentialsOverHttp`.

**Closed by chanseokoh** 2020-03-03 13:38 UTC
Labels: good first issue

**Comment by wxywizard** [comment] 2020-03-23 08:41
> We realized we have an open issue to allow fine-grained control of `allowInsecureRegistries` and `sendCredentialsOverHttp` (#1923). It will make both of them configurable in `pom.xml` and `build.gradle`. Once fixed, you will no longer required to pass `sendCredentialsOverHttp` on the command line. I will close this as a duplicate of #1923.
> 
> For now, please use `-DsendCredentialsOverHttp`.


I want to ask how to set this configuration in pom？

**Comment by wxywizard** [comment] 2020-03-23 09:00
> @loosebazooka HTTP is definitely not an exception. There has to be a good solution.
> Internal use, how to set HTTPS. If so, you might as well write your own dockerfile（Although can self-sign certificate, but how to deal with domain name resolution）
> 
> It is even more troublesome if -dsendcredentialsoverhttp =true is required from the command line. You need to change the idea tool Settings. It's several times more complicated than writing a dockerfile, and it's not universal

hello，
how can this problem be solved？

**Comment by chanseokoh** [comment] 2020-03-23 15:02
@wxywizard you just need to set the system property `sendCredentialsOverHttp=true` for the JVM running Maven. There are variety of ways to set system properties; one of easy ways is to pass it on the command line when running Maven, like `mvn -DsendCredentialsOverHttp ...`.

However, if you do want to set system properties in `pom.xml`, you can use [properties-maven-plugin](http://www.mojohaus.org/properties-maven-plugin/set-system-properties-mojo.html). For example,

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>properties-maven-plugin</artifactId>
    <version>1.0.0</version>
    <executions>
        <execution>
            <goals>
                <goal>set-system-properties</goal>
            </goals>
            <configuration>
                <properties>
                    <property>
                        <name>sendCredentialsOverHttp</name>
                        <value>true</value>
                    </property>
                </properties>
            </configuration>
        </execution>
    </executions>
</plugin>
```

The `set-system-properties` is bound to the `initialize` Maven phase, so make sure you always run at least that phase. For example, `mvn jib:build` will not work, but `mvn initialize jib:build`, `mvn compile jib:build` will work.

**Comment by Bryce-huang** [comment] 2020-11-13 08:01
in 2.6.0 .it not work

> @wxywizard you just need to set the system property `sendCredentialsOverHttp` to true for the JVM running Maven. There are variety of ways to set system properties; one of easy ways is to pass it on the command line when running Maven, like `mvn -DsendCredentialsOverHttp ...`.
> 
> However, if you do want to set system properties in `pom.xml`, you can use [properties-maven-plugin](http://www.mojohaus.org/properties-maven-plugin/set-system-properties-mojo.html). For example,
> 
> ```
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>properties-maven-plugin</artifactId>
>     <version>1.0.0</version>
>     <executions>
>         <execution>
>             <goals>
>                 <goal>set-system-properties</goal>
>             </goals>
>             <configuration>
>                 <properties>
>                     <property>
>                         <name>sendCredentialsOverHttp</name>
>                         <value>true</value>
>                     </property>
>                 </properties>
>             </configuration>
>         </execution>
>     </executions>
> </plugin>
> ```
> 
> The `set-system-properties` is bound to the `initialize` Maven phase, so make sure you always run at least up to that phase. For example, `mvn jib:build` will not work, but `mvn initialize jib:build`, `mvn compile jib:build`, or `mvn package jib:build` will work.

in 2.6.0 .it not work

**Comment by chanseokoh** [comment] 2020-11-13 15:15
@Bryce-huang it works for me. Note I'm using `jib-maven-plugin:2.6.0` below. Make sure you see in the Maven output that the `properties-maven-plugin:1.0.0:set-system-properties` goal is being executed.

```
$ mvn -Djib.to.image=localhost:5000/foo initialize compile jib:build
...
[INFO] --- properties-maven-plugin:1.0.0:set-system-properties (default) @ helloworld ---
[INFO] Set 1 system property
...
[INFO] --- jib-maven-plugin:2.6.0:build (default-cli) @ helloworld ---
[WARNING] Authentication over HTTP is enabled. It is strongly recommended that you do not enable this on a public network!
...
[INFO] Containerizing application to localhost:5000/foo...
...
[WARNING] Cannot verify server at https://localhost:5000/v2/. Attempting again with no TLS verification.
[WARNING] Failed to connect to https://localhost:5000/v2/ over HTTPS. Attempting again with HTTP.
...
[INFO] Built and pushed image as localhost:5000/foo
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.765 s
[INFO] Finished at: 2020-11-13T10:02:57-05:00
[INFO] ------------------------------------------------------------------------
```
On the other hand, if I flip the value in `properties-maven-plugin`, it fails.
```diff
             <configuration>
                 <properties>
                     <property>
                         <name>sendCredentialsOverHttp</name>
-                        <value>true</value>
+                        <value>false</value>
                     </property>
                 </properties>
             </configuration>
```
```
$ mvn -Djib.to.image=localhost:5000/foo initialize compile jib:build                                                                                
[INFO] Scanning for projects...
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.134 s
[INFO] Finished at: 2020-11-13T10:07:36-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.6.0:build (default-cli) on project helloworld: Build image failed, perhaps you should use a registry that supports HTTPS so credentials can be sent safely, or set the 'sendCredentialsOverHttp' system property to true: Required credentials for localhost:5000/foo were not sent because the connection was over HTTP -> [Help 1]
```
When in doubt, try executing only the `initialize` cycle with debug logs (`-X`). You should see something like this:
```
$ mvn -X initialize
...
[DEBUG] Configuring mojo org.codehaus.mojo:properties-maven-plugin:1.0.0:set-system-properties from plugin realm ClassRealm[plugin>org.codehaus.mojo:properties-maven-plugin:1.0.0, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'org.codehaus.mojo:properties-maven-plugin:1.0.0:set-system-properties' with basic configurator -->
[DEBUG]   (f) properties = {sendCredentialsOverHttp=true}
[DEBUG] -- end configuration --
[DEBUG] Setting system properties:
[DEBUG] - sendCredentialsOverHttp = true
[INFO] Set 1 system property
...
```
Note the lines
```
[DEBUG] Setting system properties:
[DEBUG] - sendCredentialsOverHttp = true
[INFO] Set 1 system property
```
