### ISSUE TITLE
failed: program arguments list contains null elements 

### ISSUE THREAD

**Issue by TPrinceIsaac** [GoogleContainerTools/jib#3361] opened 2021-07-28 20:01 UTC
**Steps to reproduce:**

create maven project with pom.xml

run mvn compile jib:build -Djib.serialize=true
get error below

**Error:**

ERROR: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.0:build (jib-build) on project foo-bar-xxxx-xxxxx: Execution jib-build of goal com.google.cloud.tools:jib-maven-plugin:2.7.0:build failed: program arguments list contains null elements -> [Help 1]

**Expected behavior:**
An error message telling us which arguments contained null values.

**Comment by elefeint** [comment] 2021-07-28 21:44
@TPrinceIsaac This in itself is a legitimate validation issue. Can you provide a list of arguments on which it was triggered incorrectly?

**Comment by chanseokoh** [comment] 2021-07-28 22:00
Particularly your [`<container><args>`](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#container-object) settings in your `pom.xml`.

And the latest Jib version is 3.1.2.

**Comment by chanseokoh** [comment] 2021-08-05 19:21
Closing. The cause is that one of the `<container><args>` values is null.

**Closed by chanseokoh** 2021-08-05 19:21 UTC
Labels: p2, kind/user-question
