### ISSUE TITLE
Spring Boot doesn't seem to pick up application.properties in resources.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#800] opened 2018-08-06 16:49 UTC
Originally from conversation on the [Gitter channel](https://gitter.im/google/jib).

Spring Boot doesn't seem to pick up the `application.properties` placed in `src/main/resources`. In order to use `application.properties`, the arg `--spring.config.location=/app/resources/application.properties` needs to be set.

Note that this still needs to be confirmed reproducible.

**Comment by sergeygalkin** [comment] 2018-08-17 05:02
I have reproduce. During start it looks like this During boot error looks like org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notifier' defined in URL [jar:file:/app/libs/libs-common-0.0.1-SNAPSHOT.jar!/io/domain/libs/common/service/Notifier.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'io.domain.libs.node.Code' in value "${io.domain.libs.node.Code}" 
Workaround is add 
`<jvmFlag>-Dspring.config.location=/app/resources/application.properties</jvmFlag>`

**Comment by coollog** [comment] 2018-08-22 14:08
@sergeygalkin Thanks for the info! We'll investigate this more.

**Comment by Techtony96** [comment] 2018-09-12 01:05
I am unsure if this is still happening as I have it fixed by specifying the full path. If I have some extra time I will mess around with it though.

**Comment by sergeygalkin** [comment] 2018-09-12 06:52
@chanseokoh  With your code all fine. I will try late with my code. May be this is happens only with submodules

**Comment by ST-DDT** [comment] 2018-10-02 08:21
Maybe this is related to https://github.com/GoogleContainerTools/jib/issues/905

**Comment by chanseokoh** [comment] 2019-02-14 16:17
This works in-house, and others have also reported the same. Not reproducible. There might have been a different cause for the issue, but it's working now. Closing.

**Closed by chanseokoh** 2019-02-14 16:17 UTC
Labels: P1
