### ISSUE TITLE
Invalid date when pushed to gitlab container registry

### ISSUE THREAD

**Issue by aclowkey** [GoogleContainerTools/jib#578] opened 2018-07-12 05:38 UTC
**Description of the issue**:
Running jib:build pushes an image which appears to be 48 years ago in Gitlab.
**Expected behavior**:
Date should be date of the build?
**Steps to reproduce**: 
mvn clean jib:build
![screenshot_20180712_083553](https://user-images.githubusercontent.com/2061017/42614496-d9ef8dbc-85ae-11e8-884b-eb6c68cfbbb4.png)
**Environment**: 
Maven, Kubuntu 17.04
Push to Gitlab version 11.02

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
<groupId>com.google.cloud.tools</groupId>
<artifactId>jib-maven-plugin</artifactId>
<version>0.9.4</version>
<configuration>
<to>
<image>gitlab:4567/server/serverapi/too_old</image>
</to>
</configuration>
</plugin>
```

Can this image be built locally? i.e. without pushing to anywhere. So I can see whether it's a gitlab or a JIB issue..

**Comment by chanseokoh** [comment] 2018-07-12 11:45
This is WAI, actually. Jib doesn't set the timestamp to achieve reproducibility.

`mvm compile jib:dockerBuild` can push the image directly to your local Docker daemon.

**Comment by aclowkey** [comment] 2018-07-12 12:02
@chanseokoh  What is WAI?
It still comes out as 48 years ago.

> gitlab:4567/server/serverapi/too_old                            latest                d4bae3ccc8e8        48 years ago        118MB
>

**Comment by chanseokoh** [comment] 2018-07-12 12:10
Sorry, I am saying showing 48 years old is WAI, as Jib does not set the timestamp for the image. We are aware that this can be confusing and discussing ways to address this issue.

**Comment by coollog** [comment] 2018-07-12 12:57
@aclowkey Is the date necessary for gitlab to work for your case?

**Comment by aclowkey** [comment] 2018-07-12 13:01
It will work.

**Comment by coollog** [comment] 2018-07-12 13:05
Okay, great, I will close this as working as intended for now. Feel free to reopen if the `48 years ago` ends up being a problem for you.

**Closed by coollog** 2018-07-12 13:05 UTC

**Comment by aclowkey** [comment] 2018-07-12 13:14
I mean, it i can use the image but it makes seeing images by their
chronological order very inconvinient..

**Comment by patflynn** [comment] 2018-07-12 14:43
@coollog is there a FR issue for this?  I remember a conversation happening a while back about strategies around this but I don't quite remember the details.  I remember a suggestion that was something like using the date of the last commit, which seemed interesting.

**Comment by TadCordle** [comment] 2018-07-12 14:47
I believe that was this issue https://github.com/GoogleContainerTools/jib/issues/413

**Comment by coollog** [comment] 2018-07-12 14:47
@patflynn there is an istio-dev thread about possible solutions: https://groups.google.com/forum/#!topic/istio-dev/nuv6UaBFGDk
