### ISSUE TITLE
Consider publishing Jib CLI to SDKMAN

### ISSUE THREAD

**Issue by vpavic** [GoogleContainerTools/jib#3419] opened 2021-08-13 17:47 UTC
SDKMAN is a very popular tool for managing various SDKs for the JVM. The list of currently available SDKs can be seen [here](https://sdkman.io/sdks).

Jib CLI seems like a natural fit for the SDKMAN, and I'm pretty sure its presence on the SDKMAN would help increase adoption.

**Comment by suztomo** [comment] 2021-08-16 14:13
@vpavic I'm new to SDKMAN. It seems that the tool allows users to have different versions of the tools listed there. I want to know more about that. Would you  describe your situation where you encountered issues where you only had one version of Jib CLI?

**Comment by vpavic** [comment] 2021-08-16 19:38
> Would you describe your situation where you encountered issues where you only had one version of Jib CLI?

I'm not sure if I understand this right.

There are no issues - rather than managing my local Jib CLI installation manually, I'd like to have it managed by SDKMAN, just like I have it with a number of tools listed on [sdkman.io](https://sdkman.io/sdks).

**Comment by suztomo** [comment] 2021-08-17 14:34
Good. Glad to hear you're not having a problem. Thank you for clarification.

**Comment by suztomo** [comment] 2021-08-23 15:36
This feature is not currently in our roadmap. If we change the direction, we revisit this issue.

**Comment by mpeddada1** [comment] 2021-10-18 14:22
This is really cool! Thanks for the update.

**Comment by emmileaf** [comment] 2022-08-05 16:05
Duplicate of #3667, closing as part of cleanup to centralize the discussion there.

**Closed by emmileaf** 2022-08-05 16:05 UTC
Labels: p3, kind/feature
