### ISSUE TITLE
Connect to production.cloudflare.docker.com:443

### ISSUE THREAD

**Issue by Ycm19970520** [GoogleContainerTools/jib#4050] opened 2023-06-21 03:04 UTC
Run Command mvn clean compile jib:build 

Error reporting：Connect to production.cloudflare.docker.com:443 [production.cloudflare.docker.com/104.18.124.25, production.cloudfla
re.docker.com/104.18.121.25, production.cloudflare.docker.com/104.18.122.25, production.cloudflare.docker.com/104.18.125.25, production.cloudflare.docker.com/104.18.123.25] failed: Connect timed out

**Comment by suztomo** [comment] 2023-06-23 02:55
It seems the connection from your computer to the Cloudflare docker site was unavailable at that time. Can you retry again, probably from different network?

**Comment by suztomo** [comment] 2023-06-23 03:07
Duplicate of https://github.com/GoogleContainerTools/jib/issues/4047. If there's network issue, then I'm afraid that Jib cannot resolve that.

**Closed by suztomo** 2023-06-23 03:07 UTC

**Comment by lexang** [comment] 2024-06-06 09:58
isThereAnyOtherWayToOpenALadder？
