### ISSUE TITLE
Allow to run a java -jar image

### ISSUE THREAD

**Issue by pilhuhn** [GoogleContainerTools/jib#530] opened 2018-07-10 16:26 UTC
The plugin currently requires directly or indirectly a main class. It is possible to run Java code via `java -jar archive.jar`. The plugin should support that.

**Comment by loosebazooka** [comment] 2018-07-10 17:10
Yes, our initial focus was creating fast incremental builds and that meant layering the way we do now.

While it is definitely possible, as you say, to just create an image with one layer ["fat jar layer"], or two layers ["jar layer", "dependencies layer"], those cases can be easily achieved with docker.

If you interest in Jib is as a docker replacement, then certainly in the future we can plan on offering something, perhaps in the form of a jib-jar-packaging plugin.

**Comment by patflynn** [comment] 2018-07-11 14:36
@pilhuhn why do you need a jar?

**Comment by pilhuhn** [comment] 2018-07-11 14:45
On 11 Jul 2018, at 16:36, Patrick Flynn wrote:

> @pilhuhn why do you need a jar?

My scenario is having a Throntail v2 server in hollow mode.
Here the server code is created once and would be the base layer 
together with the jvm.
And then the application .war is layered on top.
Thorntail is then started `java -jar thorntail-hollow.jar 
application.war`.

Yes, I could try to find the main class that is in the 
thorntail-hollow.jar, but it feels strange.

**Comment by patflynn** [comment] 2018-07-11 15:08
A lot of the packaging craziness that frameworks have been doing to have runnable jar services becomes unnecessary with jib.  The docker image becomes the package, and we can optimally lay out the application files and configure the entrypoint without any hackery.

It may be worth experimenting with configuring thorntail to skip it's packaging and configure the main class.  We've found that approach works very well for Spring Boot and Dropwizard based apps.  It'll also make your builds quicker.

**Comment by ST-DDT** [comment] 2018-10-02 08:29
Related https://github.com/GoogleContainerTools/jib/issues/905

**Comment by dansiviter** [comment] 2019-01-28 14:18
As mentioned in #347 it's not possible to configure Thorntail v2 to run a flat classpath as it uses JBoss module classloader to construct a deployment via `thorntail-maven-plugin`. In a nutshell, the dependency graph will not have all the required dependencies in it so will not run in Jib.
This has been addressed in Thorntail v4 as that uses a flat classpath, but unknown timeline to when that'll be released at the moment.

**Comment by t1** [comment] 2019-03-07 04:52
I'd like to run my app in a full Wildfly (`airhacks/wildfly`), which obviously makes me an odd person here ;-)
I can deploy my exploded war into `<appRoot>/opt/wildfly-${wildfly-version}/standalone/deployments/myapp.war</appRoot>` (yes, a directory named `.war`), but then I also need a file `/opt/wildfly-${wildfly-version}/standalone/deployments/myapp.war.dodeploy` to actually trigger the deployment. This file is one level above my files, so I don't see how to produce that file without a multi module project.
It would be easier to have a normal `.war`. The main benefit of using `jib` over `Dockerfile` is that I don't have to run the Docker demon and all the overhead introduced by that; the packaging step is a minor issue in my use-case.
And I really like `jib` making the build reproducible. It would be uber cool, if it would set all file dates _in my war_ to zero, too.

**Comment by chanseokoh** [comment] 2019-03-07 20:15
@t1 fortunately in this case, I think you can place `myapp.war.dodeploy` into `<your project root>/src/main/jib/opt/wildfly-${wildfly-version}/standalone/deployments/myapp.war.dodeploy`. Anything under `src/main/jib` will be copied into the image keeping the layout as-is, so the `.dodeploy` file will be placed at precisely `/opt/wildfly-${wildfly-version}/standalone/deployments/`.

> it would be easier to have a normal .war

As this issue stands, this is one of the things we've been considering (although supporting `.jar` has a higher priority than `.war`). We may eventually get to it, but probably not real soon.

> if it would set all file dates in my war to zero, too.

I don't think this is not what reproducibility implies. Often it's actually against it. We do check timestamps of files being put into the image to verify the files are not changed.

**Comment by t1** [comment] 2019-03-08 06:53
@chanseokoh: Thanks for the hint. I had thought that `/src/main/jib` was placed relative to the deployment. Works like a charm!

>> if it would set all file dates in my war to zero, too.
> I don't think this is not what reproducibility implies. Often it's actually against it. We do check timestamps of files being put into the image to verify the files are not changed.

Maybe I misunderstood this, too. I thought all file modification dates where set to 0 (1970-01-01), so if you build the same image twice with the same content, it will have the same checksum. I had exactly this issue with two wars containing exactly the same files but having different checksums... then I found out it was just different timestamps. I was happy to read that jib does that ootb, so I assume it does it in some cases, but not in others?

**Comment by chanseokoh** [comment] 2019-03-08 15:31
@t1 sorry, I was obviously confused about the timestamps of the files on the host and the timestamps of the files in the image.

Yeah, we do [set the timestamps of all files in the image that we put to 1 second since the epoch](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java#L124). I bet with the two WARs you have, all the files that Jib puts in the images will have the timestamp set to 1970-01-01 + 1sec. If they have different checksums, then I think there must be something else different between the two. (BTW, Jib currently doesn't unpack the final WAR files but instead uses the exploded WAR directory at the moment. (#1091)) Also, when you say checksums, what kind of checksums are you specifically referring to?

**Comment by t1** [comment] 2019-03-08 15:58
@chanseokoh: I wasn't clear about the problem I had seen earlier with the two wars having the same content but different checksums: it was about real wars that where put on Artifactory, and rebuilding one created a different SHA-256 checksum which was confusing. This had nothing to do with jib; I just happened to like the idea of resetting the timestamps when building an archive.

**Comment by patflynn** [comment] 2019-03-08 16:09
I haven't tried it, but you may want to look at a maven plugin such as this
one: https://zlika.github.io/reproducible-build-maven-plugin/

**Comment by t1** [comment] 2019-03-08 18:18
@patflynn: Thanks for the hint. I had the problem ~ 5 years ago, before that plugin was created, so I hadn't found it then ;-)
(and you really shouldn't include the mail footer in your reply or probably anybody can unsubscribe you ;-)

**Comment by t1** [comment] 2019-03-08 18:24
@patflynn: I tried it; work's like a charm!

**Comment by patflynn** [comment] 2019-03-08 19:04
Happy to hear!

**Comment by briandealwis** [comment] 2019-04-08 14:40
#1606 produces a separate fatjar using the `spring-boot-maven-plugin`'s `classifier` argument.  There are two implications here:
  - the users may want to specify an arbitrary jar file
  - the users should be able to indicate that the project dependencies should be ignored (they are unneeded)

**Comment by chanseokoh** [comment] 2019-06-20 19:23
Update: #905 is fixed, and the next Jib release will enable containerizing a JAR, placing it at `/app/classpath/helloworld-1.jar` for example.

Of course, this doesn't automatically make Jib to do `java -jar ...`, but at least you can manually set the `jib.entrypoint` to do so.  _However_, you should avoid containerizing a fat/shaded JAR, because Jib assumes that the JAR contains only the application `.class` and resource files and will copy dependencies JARs into `/app/libs/` no matter what. That will lead into another issue that your `META-INF/MANIFEST.MF` should list the dependency JARs in the `Class-Path` header with right paths. (Specifying both `-jar` and `-cp` won't work.)

That said, in many cases, it'd be just simpler and straightforward to let Jib do the default `java -cp /app/classpath/*:/app/libs/* <correct main class>` in the case of non-fat JAR containerization anyway.

**Comment by diego92sigma6** [comment] 2022-08-02 23:00
Closing due to cleanup. Please reopen if needed.

**Closed by diego92sigma6** 2022-08-02 23:00 UTC
Labels: area/jib-maven-plugin, p4, area/jib-gradle-plugin, discuss, kind/feature
