### ISSUE TITLE
Images not reproducible due to atime and ctime (in combination with other Gradle plugins)

### ISSUE THREAD

**Issue by felixscheinost** [GoogleContainerTools/jib#3962] opened 2023-03-22 14:05 UTC
**Environment**:

- *Jib version:* Gradle Plugin 3.3.1 
- *Build tool:* Gradle 7.5
- *OS:* macOS 13.2.1

**Description of the issue**:

I am running `gradle clean`, `gradle jibBuildTar` twice and inspecting the tar files using `dive`.

The layer containing JARs from Gradle subprojects isn't reproducible.

I made sure to include the following in my Gradle file:

```kotlin
  tasks.withType<AbstractArchiveTask> {
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true
  }
```

I ensured that this works by running twice: `gradle clean`, `gradle :<subproject>:jar`, `shasum <jar>` and comparing the checksums of the JAR file. I also extracted the layer which confirms: The JARs itself are reproduced correctly.

Diffing the `.tar.gz` files of the respective layer showed that some `ctime` and `atime` attributes were different.

I set a breakpoint in `ReproducibleLayerBuilder#build` to inspect the `sortedFilesystemEntries`. There I could see that `mTime` was correctly set to a fixed timestamp but `cTime` and `aTime` weren't.

<img width="1423" alt="grafik" src="https://user-images.githubusercontent.com/31761492/226929727-312f19ad-b388-49b0-96ae-1e5d15fc0d30.png">

I think additionally to `entry.setModTime` both `entry.setStatusChangeTime` and `entry.setLastAccessTime` also need to be set to a fixed value.

**Expected behavior**:

Running `gradle clean`, `gradle jibBuildTar` should be reproducible.

**Steps to reproduce**:

1. Have a Gradle project with multiple subprojects. 
2. The main project depends on some of the subprojects using `implementation(project(":some-subproject")`'
3. Have the [OWASP dependency check plugin in the project as well](https://plugins.gradle.org/plugin/org.owasp.dependencycheck). This plugin depends on `org.apache.commons:commons-compress:1.22` which adds `ctime` and `atime` support.

**Comment by felixscheinost** [comment] 2023-03-22 14:19
Huh, it seems that this bug only happens as I have another Gradle plugin in my project which causes `org.apache.commons:commons-compress` to be updated from 1.21 to 1.22, which adds atime and ctime support.

**Comment by felixscheinost** [comment] 2023-03-24 11:33
I think this issue could be closed, right? This thing just needs to be kept in mind once you Jib updates to 1.22. I think even when closed this issue may help someone struggling with the same issue as I am 😃

**Comment by emmileaf** [comment] 2023-03-24 23:09
@felixscheinost Yes, I'll close this issue since you've discovered the cause - thanks for the investigation and documenting your findings here!

**Closed by emmileaf** 2023-03-24 23:09 UTC
Labels: priority:p3, question, area/jib-gradle-plugin
