### ISSUE TITLE
MANIFEST_INVALID when pushing manifest to quay.io

### ISSUE THREAD

**Issue by chris-pccw** [GoogleContainerTools/jib#2470] opened 2020-05-18 01:41 UTC
**Environment**: Jenkins

- *Jib version:* 2.2.0
- *Build tool:* maven 3.6.3
- *OS:*: centos7 on slaves and head/master

**Description of the issue**:
The `mvn jib:build` goal constantly failed with below message. Sometimes a retry will fix it
```
Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.2.0:build (default-cli) on project workflow-java-sdk-process-cloud: Tried to push image manifest for quay.io/your_image but failed because: Registry may not support pushing OCI Manifest or Docker Image Manifest Version 2, Schema 2 | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 400 BAD REQUEST
[ERROR] {"errors":[{"code":"MANIFEST_INVALID","detail":{"message":"Attempt to create an invalid manifest. Please report this issue."},"message":"manifest invalid"}]}
```

If retry the same goal in Jenkins, it went back to normal
```
[INFO] --- jib-maven-plugin:2.2.0:build (default-cli) @ my project ---
[INFO] 
[INFO] Containerizing application to quay.io/my_image:version, quay.io/my_image...
[INFO] Using credentials from Maven settings file for quay.io/my_image:version
[INFO] Getting manifest for base image adoptopenjdk/openjdk11@sha256:f92b946306c1f17be5578a84f61482766c4a47d6c75a2b49a49b7ef321cc750f...
[INFO] Building resources layer...
[INFO] Building dependencies layer...
[INFO] Building classes layer...
[INFO] The base image requires auth. Trying again for adoptopenjdk/openjdk11@sha256:f92b946306c1f17be5578a84f61482766c4a47d6c75a2b49a49b7ef321cc750f...
[INFO] The base image reference is manifest list, searching for linux/amd64
[INFO] Using base image with digest: sha256:63a55a2b49a12a15409c8228e7a23be3347b565d45dc7d05a03f965b495e0a90
[INFO] 
[INFO] Container entrypoint set to [java, -XX:MaxRAMPercentage=75.0, -XX:+UseContainerSupport, -Djava.awt.headless=true, -Djava.security.egd=file:/dev/./urandom, -cp, /app/resources:/app/classes:/app/libs/*, mypackage.MyApplication]
[INFO] 
[INFO] Built and pushed image as quay.io/my_image:version quay.io/my_image
```

**Expected behavior**:
The error message is misleading and it shouldn't fail for the first time

**Steps to reproduce**:

  1. Create a simple spring boot project with maven 3.6.3 and jib plugin 2.2.0
  2. Create a Jenkins job and publish the docker image to quay.io

**`jib-maven-plugin` Configuration**: 
```xml
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${maven-jib-plugin.version}</version>
                    <configuration>
                        <from>
                            <image>${jib.from.image}</image>
                        </from>
                        <to>
                            <image>${docker.registry}/${docker.image.name}:${version.number}</image>
                            <tags>
                                <tag>latest</tag>
                            </tags>
                        </to>
                        <container>
                            <labels>
                                <quay.expires-after>12w</quay.expires-after>
                            </labels>
                            <jvmFlags>
                                <jvmFlag>-XX:MaxRAMPercentage=75.0</jvmFlag>
                                <jvmFlag>-XX:+UseContainerSupport</jvmFlag>
                                <jvmFlag>-Djava.awt.headless=true</jvmFlag>
                                <jvmFlag>-Djava.security.egd=file:/dev/./urandom</jvmFlag>
                            </jvmFlags>
                            <ports>
                                <port>8080</port>
                            </ports>
                        </container>
                    </configuration>
                </plugin>

```

**Comment by loosebazooka** [comment] 2020-05-18 02:08
It's possible you still need to whitelist your project for schema manifest v2.2. As seen in this comment: https://github.com/GoogleContainerTools/jib/issues/1986#issuecomment-531290926

**Comment by chris-pccw** [comment] 2020-05-18 02:48
Hi @loosebazooka, 

Thanks for the quick response. We already did in Feb 2020, but was told "we are working on deploying a new version of Quay.io that will fully support v2_2 schema The new version of Quay will be available in the near future." 

If v2_2 is not supported at all, shouldn't it fail all the time? But for our case, the failure appears to be intermittent. Sometimes it works, sometime it doesn't

Full communication with quay support attached below

> Hi Quay.io Support,
> 
> We are evaluating google container tool called jib, and we are getting error when pushing distroless image to quay.io. Tried to push image manifest for quay.io/my_image, but failed because: Registry may not support pushing OCI Manifest or Docker Image Manifest Version 2, Schema 2According to comments in github for this tool[1], our organisation[2] needs to be whitelisted by quay.io for docker manifest v2.2. We'd like to arrange for this to allow us to complete our evaluation.

> [1] https://github.com/GoogleContainerTools/jib/issues/1646#issuecomment-485979463
> [2] https://quay.io/organization/consoleconnect

> Hi ,
> 
> We are actively working on deploying a new version of Quay.io that will fully support v2_2 schema The new version of Quay will be available in the near future.
> 
> Please let us know if you have any questions.
> 
> Thank you,

**Comment by loosebazooka** [comment] 2020-05-18 03:01
@chris-pccw that's unfortunate. Schema v2.1 is deprecated so we have no real incentive to introduce support for it: https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1

The intermittent failure is strange, but I really don't think it's a jib issue. Perhaps they are running multiple versions of their registry behind a load balancer (I dunno, it could be anything). Could you use another registry in the meantime, while they update their systems?

**Comment by chanseokoh** [comment] 2020-05-18 14:03
If it's failing intermittently, it may not be a Schema version issue. Often Quay correctly returns `415 UNSUPPORTED MEDIA TYPE` (#2163, Enterprise Quay in this case).

The following error message is from Quay.io, and I think you should report the issue to Quay too.
```
[ERROR] {"errors":[{"code":"MANIFEST_INVALID","detail":{"message":"Attempt to create an invalid manifest. Please report this issue."},"message":"manifest invalid"}]}
```

We occasionally get a report from Jib users where they see a totally unexpected upload error when pushing an image to a major registry like Quay.io, Sonatype Nexus, Artifactory, etc. Most of the time, the registry does not return any reason or helpful message why the manifest is invalid or what is specifically wrong with the manifest; like in your case, it's frustrating to see such an unhelpful registry error message. Even so, in certain cases, we were able to prove there is a bug in the registry (e.g., #2372, #1986), but not all the time (e.g., #2230, #2013). However, from what I've been investigating these issues, I do not believe Jib has a bug in pushing an invalid manifest. I suspect some registries do have a concurrency bug, and I am also heavily leaning toward to that possibility in your case too.

Whenever we get this type of report, I really hope to get to the bottom of the issue so that we can conclusively prove that it's not a Jib issue but a bug in a registry. That's not so easy without the registry developers and admins looking into the registry logs and when and under which condition the registry returns the error. We can only try to infer as much information as possible from the Jib side, but it's very inefficient given the nature of the issue. The best I think is that you ask Quay.io devs when exactly Quay.io returns the error and get back to us.

In the meantime, I'm also curious to see the detailed interactions with the registry. Could you follow [these instructions](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic) to capture raw HTTP interactions?

**Comment by chris-pccw** [comment] 2020-05-18 23:50
Switching to different registry is not an option for my case at this stage.

I turned on the logging and will get back to you once if fails.

BTW, I raised the same issue to quay as well, and below is their response

> It sounds like Jib is either generating a bad manifest on the first push, or is attempting to push manifests before their dependencies have been fully uploaded and verified on our end.

**Comment by chanseokoh** [comment] 2020-05-19 03:53
Thanks. I forgot to ask this: could you to also capture the HTTP traffic of the next successful Jib push without making any changes to the project or the environment right after an initial push failure? This time, I really want to uncover yet another proven case of a bug in Quay, and I think we should be able to do it with your help.

**Comment by chanseokoh** [comment] 2020-05-19 04:08
Oh! I forgot the most important thing: this probably happens only when there is a high-level of concurrency. When you attempt to capture HTTP traffic, you should not pass `-Djib.serialize=true` which will completely turn off concurrency.

And could you also ask them what exactly is wrong in the manifest, e.g., whether they think a certain blob specified in the manifest is not fully uploaded, and if so, whether they can pinpoint whi h blob (SHA for the blob) is believed to be missing once it happens. Honestly, I suspect that they have a concurrency issue so that even if the registry returns that all blobs are fully uploaded, their internal system state is not completely stablized by the time a manifest is being pushed.

**Comment by chris-pccw** [comment] 2020-05-19 04:18
[jib_success_log.txt](https://github.com/GoogleContainerTools/jib/files/4648169/jib_success_log.txt)

I just uploaded the log with `-Djib.serialize=true`. Off the top of my head, it always worked with this option enabled. I will try to make another successful build without that flag

**Comment by chanseokoh** [comment] 2020-05-19 04:20
Thanks. It is best to have a failure log + a success log right after the failure. Without `jib.serialize`, of course.

**Comment by chris-pccw** [comment] 2020-05-19 05:21
[failure.txt](https://github.com/GoogleContainerTools/jib/files/4648365/failure.txt)
[success.txt](https://github.com/GoogleContainerTools/jib/files/4648366/success.txt)

Hi @chanseokoh, here is a failed one and a successful one without `jib.serialize` for your investigation. Thanks!

**Comment by chanseokoh** [comment] 2020-05-19 20:25
@chris-pccw turns out this is enough to prove that it's a bug in Quay.io. Thank you very much for the logs! As we observed in the past, this looks like yet another concurrency bug in Quay.io.

## Image Manifest

At the end of the `failure.txt` log, we can see that Jib attempts to push the (same) image manifest for the two tags `:latest` and `:20200519-041939.a928c63`, one of which fails with `MANIFEST_INVALID`:

- `PUT https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/manifests/20200519-041939.a928c63`
- `PUT https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/manifests/latest`

The content of the manifest (pretty-printed using `jq`) is the following:
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "digest": "sha256:1cdc23e3f89c99545a8a9096a5e5569d54a8d6656358b7905b6d02830a6450c5",
    "size": 7367
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:524b0c1e57f8ee5fee01a1decba2f301c324a6513ca3551021264e3aa7341ebc",
      "size": 75880141
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:c3de08fd295cd74cad49245d68e8199f21c58816d841ef9fb59bb16922e84a34",
      "size": 932384
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:4afc23114b786a4399160b9ec1701d8e5048d199c5b14928c3f201daee9fa27a",
      "size": 6595406
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:bbe08f64767f98dfaa9fc7578716aa361381c4a7a2034853bebeca73b0a01dbc",
      "size": 78581131
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:cfb7bf3f7554626d242c3e66d28308b7965e62a5a47ba91f2ba386dcf88b3618",
      "size": 157167214
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de",
      "size": 78677
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:48a5d06fb573a955b671969eeaf580b82fa97c941c060ca2f8c7e6b4542193e6",
      "size": 377054
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:f426fe7fbed36b01a2d36d349127041c482872a907b8801a56d3099f38a0c35a",
      "size": 17802
    }
  ]
}
```
Syntactically, there is nothing wrong with the manifest, as verified by `jq`. (The size of the actual manifest being pushed is 1,574 bytes, and this is correct as well.) The manifest lists total 9 SHAs (8 image layer blobs + 1 container configuration JSON).

Below, we can verify that Quay.io itself did confirm that all the SHAs listed in the manifest either already exist in the registry or has been uploaded successfully.

## Four Base Image Layer SHAs

The following SHAs are the layers from the base image (`quay.io/consoleconnect/wp_workflow_base:latest`):

1. sha256:524b0c1e57f8ee5fee01a1decba2f301c324a6513ca3551021264e3aa7341ebc - size 75880141
2. sha256:c3de08fd295cd74cad49245d68e8199f21c58816d841ef9fb59bb16922e84a34 - size 932384
3. sha256:4afc23114b786a4399160b9ec1701d8e5048d199c5b14928c3f201daee9fa27a - size 6595406
4. sha256:bbe08f64767f98dfaa9fc7578716aa361381c4a7a2034853bebeca73b0a01dbc - size 78581131

For these layers, Quay.io responded to all the corresponding HEAD requests and confirmed that the layers already exist in the repository.

1. sha256:524b0c1e57f8ee5fee01a1decba2f301c324a6513ca3551021264e3aa7341ebc - size 75880141
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:524b0c1e57f8ee5fee01a1decba2f301c324a6513ca3551021264e3aa7341ebc
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 75880141
...
Docker-Content-Digest: sha256:524b0c1e57f8ee5fee01a1decba2f301c324a6513ca3551021264e3aa7341ebc
```

2. sha256:c3de08fd295cd74cad49245d68e8199f21c58816d841ef9fb59bb16922e84a34 - size 932384
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:c3de08fd295cd74cad49245d68e8199f21c58816d841ef9fb59bb16922e84a34
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 932384
Docker-Content-Digest: sha256:c3de08fd295cd74cad49245d68e8199f21c58816d841ef9fb59bb16922e84a34
```

3. sha256:4afc23114b786a4399160b9ec1701d8e5048d199c5b14928c3f201daee9fa27a - size 6595406
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:4afc23114b786a4399160b9ec1701d8e5048d199c5b14928c3f201daee9fa27a
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 6595406
...
Docker-Content-Digest: sha256:4afc23114b786a4399160b9ec1701d8e5048d199c5b14928c3f201daee9fa27a
```

4. sha256:bbe08f64767f98dfaa9fc7578716aa361381c4a7a2034853bebeca73b0a01dbc - size 78581131
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:bbe08f64767f98dfaa9fc7578716aa361381c4a7a2034853bebeca73b0a01dbc
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 78581131
...
Docker-Content-Digest: sha256:bbe08f64767f98dfaa9fc7578716aa361381c4a7a2034853bebeca73b0a01dbc
```

## Four Application Layer Blob SHAs

Next, The following SHAs are application layers built by Jib:

1. sha256:cfb7bf3f7554626d242c3e66d28308b7965e62a5a47ba91f2ba386dcf88b3618 - size 157167214
2. sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de - size 78677
3. sha256:48a5d06fb573a955b671969eeaf580b82fa97c941c060ca2f8c7e6b4542193e6 - size 377054
4. sha256:f426fe7fbed36b01a2d36d349127041c482872a907b8801a56d3099f38a0c35a - size 17802

Quay.io confirmed that all the application layers either already exist in the repository or has been uploaded successfully.

1. sha256:cfb7bf3f7554626d242c3e66d28308b7965e62a5a47ba91f2ba386dcf88b3618 - size 157167214
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:cfb7bf3f7554626d242c3e66d28308b7965e62a5a47ba91f2ba386dcf88b3618
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 157167214
...
Docker-Content-Digest: sha256:cfb7bf3f7554626d242c3e66d28308b7965e62a5a47ba91f2ba386dcf88b3618
```

2. sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de - size 78677
```
CONFIG: -------------- REQUEST  --------------
POST https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/?mount=sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de&from=consoleconnect/wp_workflow_base
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 202 ACCEPTED
...
Docker-Upload-UUID: 8b8383da-44e0-4afb-b3bc-95e35891d620
Range: bytes=0--1
Location: https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/8b8383da-44e0-4afb-b3bc-95e35891d620
...
CONFIG: -------------- REQUEST  --------------
PATCH https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/8b8383da-44e0-4afb-b3bc-95e35891d620
...
CONFIG: Total: 78,677 bytes (logging first 16,384 bytes)
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 202 ACCEPTED
...
Docker-Upload-UUID: 8b8383da-44e0-4afb-b3bc-95e35891d620
Range: 0-78676
Location: https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/8b8383da-44e0-4afb-b3bc-95e35891d620
...
CONFIG: -------------- REQUEST  --------------
PUT https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/8b8383da-44e0-4afb-b3bc-95e35891d620?digest=sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 201 CREATED
...
Docker-Content-Digest: sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de
Location: https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:97368fbf3fdd3a61e3bf78e327efb52754a3d5cbc1e08248f2889926ad35a3de
```

3. sha256:48a5d06fb573a955b671969eeaf580b82fa97c941c060ca2f8c7e6b4542193e6 - size 377054
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:48a5d06fb573a955b671969eeaf580b82fa97c941c060ca2f8c7e6b4542193e6
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 377054
...
Docker-Content-Digest: sha256:48a5d06fb573a955b671969eeaf580b82fa97c941c060ca2f8c7e6b4542193e6
```

4. sha256:f426fe7fbed36b01a2d36d349127041c482872a907b8801a56d3099f38a0c35a - size 17802
```
CONFIG: -------------- REQUEST  --------------
HEAD https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:f426fe7fbed36b01a2d36d349127041c482872a907b8801a56d3099f38a0c35a
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
...
Content-Length: 17802
...
Docker-Content-Digest: sha256:f426fe7fbed36b01a2d36d349127041c482872a907b8801a56d3099f38a0c35a
```

## Container Configuration Blob SHA

Finally, Quay.io also confirmed the container configuration JSON (sha256:1cdc23e3f89c99545a8a9096a5e5569d54a8d6656358b7905b6d02830a6450c5 - size 7367) is successfully uploaded.

```
CONFIG: -------------- REQUEST  --------------
POST https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/?mount=sha256:1cdc23e3f89c99545a8a9096a5e5569d54a8d6656358b7905b6d02830a6450c5&from=consoleconnect/wp_workflow_base
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 202 ACCEPTED
...
Docker-Upload-UUID: 10ee7811-fc44-4349-a037-015a632e366c
Range: bytes=0--1
Location: https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/10ee7811-fc44-4349-a037-015a632e366c
...
CONFIG: -------------- REQUEST  --------------
PATCH https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/10ee7811-fc44-4349-a037-015a632e366c
...
CONFIG: Total: 7,367 bytes
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 202 ACCEPTED
...
Docker-Upload-UUID: 10ee7811-fc44-4349-a037-015a632e366c
Range: 0-7366
Location: https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/10ee7811-fc44-4349-a037-015a632e366c
...
CONFIG: -------------- REQUEST  --------------
PUT https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/uploads/10ee7811-fc44-4349-a037-015a632e366c?digest=sha256:1cdc23e3f89c99545a8a9096a5e5569d54a8d6656358b7905b6d02830a6450c5
...
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 201 CREATED
...
Docker-Content-Digest: sha256:1cdc23e3f89c99545a8a9096a5e5569d54a8d6656358b7905b6d02830a6450c5
Location: https://quay.io/v2/consoleconnect/wp_workflow-java-sdk-service-billing/blobs/sha256:1cdc23e3f89c99545a8a9096a5e5569d54a8d6656358b7905b6d02830a6450c5
```

**Comment by chris-pccw** [comment] 2020-05-19 23:25
Thank you so much @chanseokoh for the detailed info here. I will report it to Quay.io. Despite the concurrency issue identified here, if I set `-Djib.serialize=true` when pushing image, it will work right? If so, I am happy to close this ticket

**Comment by josephschorr** [comment] 2020-05-20 11:38
@chanseokoh Is Jib pushing the same manifest contents twice in parallel? If so, there is a possibility it is a concurrency issue, as the specific manifest issue raised can only occur if the manifest is invalid (i.e. the number of history entries in config disagrees with the number of layers) OR a parallel push of the manifest occurs at the same time and our attempt to create the manifest fails (and the subsequent lookup fails too). I'll see if we can reproduce the issue, as our code should support the fallback case.

**Comment by chanseokoh** [comment] 2020-05-20 12:49
@josephschorr according to the Docker Registry API, pushing a manifest in multiple times is the only way to create multiple tags and pushing a valid manifest multiple times in parallel should not cause any problem. The Registry API spec does not impose any restrictions in pushing manifests concurrently, and in practice all sane registry implementations have never had any problem with it.

A manifest Jib creates is a valid one, and even though there is no restrictions in the spec that the number of layer histories must matche the number of layers, we do ensure augmenting missing history entries in case a base image is missing some after we found that some registry implementation malfunctions when the number of history entries do not match.

**Comment by josephschorr** [comment] 2020-05-20 13:03
@chanseokoh Oh, I know its allowed :) I was asking if Jib did indeed push in parallel, so we could narrow down the root cause. Since it sounds like it is, we'll investigate that angle. Thanks!

**Comment by chanseokoh** [comment] 2020-05-20 13:06
@josephschorr yeah, I confrm Jib pushes in parallel. Thank you for looking into it!

**Comment by chanseokoh** [comment] 2020-05-20 14:04
@chris-pccw although `-Djib.serialize=true` does work, it can be terribly slow, as it turns off concurrency completely. I'd rather do
```bash
if ! ./mvnw jib:build; then
  echo "Normal build failed. Falling back."
  # this should be really fast as all layers have already uploaded
  # and will upload only the manifest
  ./mvnw -Djib.serialize=true jib:build
fi
```
or
```bash
#!/bin/bash

for i in {1..10}; do
  if ./mvnw jib:build; then break; fi
done
```
And it will help us and the Jib community if you keep us informed on this issue. I'd appreciate it.

**Comment by chanseokoh** [comment] 2020-05-20 14:14
@chris-pccw or, if this happens only when creating multiple tags (i.e., pushing the same manifest multiple times in parallel), you could do `mvn jib:build` twice in succession as another workaround. I see you pushing `:latest` and `:20200519-041939.a928c63`.
```
./mvnw -Djib.to.image=registry/repo:latest jib:build
./mvnw -Djib.to.image=registry/repo:20200519-041939.a928c63 jib:build
```
(Or you could set up Maven profiles or use another system property to parameterize a tag.)

**Comment by chris-pccw** [comment] 2020-05-21 06:40
Sure will do. Thanks a lot for your help @chanseokoh

**Comment by chanseokoh** [comment] 2020-08-06 20:05
@chris-pccw Quay.io [deployed a fix]( https://groups.google.com/g/quay-sig/c/7Pp80zhdgzM/m/5_QAzDqIBQAJ), so you may try it out.

> The fix has been deployed to Quay.io. Please let us know if you encounter any further issues.

I'll close the issue, but I'd appreciate an update if it resolved your issue.

**Closed by chanseokoh** 2020-08-06 20:05 UTC

**Comment by chris-pccw** [comment] 2020-08-07 00:00
Thanks for letting me know, however I got two issues after removing `-Djib.serialize=true`
1. First time it failed with below error message
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.4.0:build (default-cli) on project xxx: 500 Internal Server Error
[ERROR] <html>
[ERROR]   <head>
[ERROR]     <title>Internal Server Error</title>
[ERROR]   </head>
[ERROR]   <body>
[ERROR]     <h1><p>Internal Server Error</p></h1>
[ERROR]     
[ERROR]   </body>
[ERROR] </html>
[ERROR] 
```
2. Second attempt worked, but it doesn't seem to honour `labels` settings as shown below
```
<labels>
     <quay.expires-after>12w</quay.expires-after>
</labels>
```
![Screen Shot 2020-08-07 at 9 56 35 am](https://user-images.githubusercontent.com/46508107/89594174-82d55580-d894-11ea-8a6b-f8e54cdbdb0c.png)

Version `20200806.f757486`'s was generated earlier, `latest` should never expire, that's expected behaviour, however the new one `20200806.8961dbb` was not set with any expiry date.

**Comment by josephschorr** [comment] 2020-08-07 00:06
I'll take a look at #1 tomorrow; #2 is by design currently: we only apply the labels on the first manifest creation, not on subsequent tags. This will likely be changed in a future version but remains the current behavior because the label applies to the manifest, not the tags.

**Comment by chanseokoh** [comment] 2021-03-04 19:04
Marking resolved.
