### ISSUE TITLE
Wrong Push Timestamp when using GitLab Registry

### ISSUE THREAD

**Issue by apomp** [GoogleContainerTools/jib#597] opened 2018-07-13 05:46 UTC
**Description of the issue**:
When pushing to our private GitLab Registry, the wrong timestamp (epoch 0) is set instead of the real timestamp when the image was pushed. 

**Expected behavior**:
The correct timestamp (inferred from server time or from the system's time where the image was built) is used)

**Steps to reproduce**: 
Just include the dependency and push to a private GitLab registry (not testet with a public one). 

**Environment**: 
Build on Windows 10, IntelliJ and Maven 3

**`jib-maven-plugin` Configuration**: 
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${com.google.cloud.tools.jib}</version>
                <configuration>
                    <to>
                        <image>${git.registry}:${project.version}</image>
                    </to>
                </configuration>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by apomp** [comment] 2018-07-13 05:47
![image](https://user-images.githubusercontent.com/9024256/42674661-f9ea0076-8670-11e8-8e9e-b194929390e1.png)

**Comment by coollog** [comment] 2018-07-13 12:47
Hi @apomp , this is related to #578 . We set the timestamp to 0 ensure reproducibility of the image overall. We can consider adding an option to configure this timestamp so that you can get a real creation time on GitLab registry.

**Comment by apomp** [comment] 2018-07-13 12:59
Thank you for your response. Allowing to configure the timestamp would be a good solution.

**Comment by TadCordle** [comment] 2018-07-13 16:53
Since we have #413 open to discuss this issue, I'm going to close this one. Feel free to comment on #413 if you have anything to remark.

**Closed by TadCordle** 2018-07-13 16:53 UTC
