### ISSUE TITLE
Spring boot classifier support

### ISSUE THREAD

**Issue by HJK181** [GoogleContainerTools/jib#1606] opened 2019-04-08 12:15 UTC
**Description of the issue**:
We use the spring-boot-maven-plugin to add a classifier to the executable FAT-JAR.
```
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <classifier>exec</classifier>
  </configuration>
</plugin>
```
This way we can have our integration tests include a dependency without including all the Spring Boot libs. 

Using JIB it is not possible to specify that we only wan't to build from *-exec.jar file and ignore the *.jar file.

**Expected behavior**:
With the dockerfile-maven-plugin it was possible to define a build arg which could than be used in the Dockerfile's entrypoint:
```
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>dockerfile-maven-plugin</artifactId>
  <configuration>
    <buildArgs>
      <JAR_FILE combine.self="override">${project.build.finalName}-exec.jar</JAR_FILE>
    </buildArgs>
  </configuration>
</plugin>
```
I'm not familiar with JIB's code so I don't know what to expect, except that I need to define which JAR file should be analysed by JIB.

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<version>1.0.2</version>
	<configuration>
		<from>
			<image>openjdk:8u151-jdk-alpine</image>
		</from>
		<to>
			<image>${docker.repository}/xxx-services/${project.artifactId}</image>
			<credHelper>ecr-login</credHelper>
			<tags>
				<tag>jib-test</tag>
			</tags>
		</to>
	</configuration>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>build</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by briandealwis** [comment] 2019-04-08 14:30
Jib currently doesn't support using a jar. We're considering adding support, and the important thing for this issue is that the project's built artifact may not be the jar to use.

Duplicate of #530

**Comment by briandealwis** [comment] 2019-04-08 14:38
@HJK181 Jib packages up your project's class files and resources, with its dependencies such as the Spring Boot libraries and the embedded tomcat, into the image.  Are you finding that the resulting image doesn't work?

**Comment by HJK181** [comment] 2019-04-08 15:17
Ok, I didn't know that the JAR file is not important for builder the image. The resulting image does start with the following message:
```
The Class-Path manifest attribute in /app/libs/core-1.0-SNAPSHOT.jar referenced one or more files that do not exist: file:/app/libs/lib/micrometer-registry-prometheus-1.1.2.jar,file:/app/libs/lib/micrometer-core-1.1.2.jar,...
```

The core-1.0-SNAPSHOT which is a dependency of my project has micrometer _1.1.2_ in it's POM whereas my project uses micrometer _1.1.0_. When inspecting the maven dependency hierarchy in my IDE it get's resolved to 1.1.0. So maybe the problem here is that JIB expects the version of the core instead of my project?

**Comment by briandealwis** [comment] 2019-04-08 15:51
Jib places dependencies in `/app/libs`.  Are you embedding path names in your `Class-Path` entries?

Jib configures the class-path based on the project dependencies, which should match what your IDE reports for your project's Maven dependency hierarchy.  The [`dive` tool](https://github.com/wagoodman/dive) is useful for inspecting the resulting images to see what was actually packaged.

**Comment by chanseokoh** [comment] 2019-04-08 17:43
```
The Class-Path manifest attribute in /app/libs/core-1.0-SNAPSHOT.jar referenced one or more files that do not exist: file:/app/libs/lib/micrometer-registry-prometheus-1.1.2.jar,file:/app/libs/lib/micrometer-core-1.1.2.jar,...
```
Maybe this is a warning and not an error. As long as 1.1.0 is in the classpath (which should be the case with Jib), I think core-1.0-SNAPSHOT will pick up and use 1.1.0. That said, can't you upgrade your project to use 1.1.2 for safety?

**Comment by HJK181** [comment] 2019-04-09 08:04
@briandealwis We are not embedding path names in the _Class-Path_. 
Thank you for your tip on the _dive tool_, I think I could nail down the problem with it. The core-1.0-SNAPSHOT project uses the _maven-dependency-plugin_:
```
<plugin>
	<artifactId>maven-dependency-plugin</artifactId>
	<version>${maven-dependency-plugin.version}</version>
	<executions>
		<execution>
			<goals>
				<goal>copy-dependencies</goal>
			</goals>
			<configuration>
				<overWriteReleases>false</overWriteReleases>
				<includeScope>runtime</includeScope>
				<outputDirectory>${project.build.directory}/lib</outputDirectory>
			</configuration>
		</execution>
	</executions>
</plugin>
```
where all dependencies are placed in _/lib_. This results in the following _MANIFEST.MF_:
```
Class-Path: lib/micrometer-registry-prometheus-1.1.2.jar lib/micrometer-core-1.1.2.jar ...
```
When inspecting the Docker image JIB builds, micrometer can be found under /app/libs/micrometer-core-1.1.0.jar, like you described. The warning when the container starts searches for the dependency on a different path (/app/libs/lib): _file:/app/libs/lib/micrometer-core-1.1.2.jar_

@chanseokoh Of course this can be fixed by aligning the micrometer version in my project, I just got a little bit confused about the warning message which printed out 64 JAR files, so I thought they all have a mismatch and need to be aligned. In fact I noticed with the use of the _dive tool_, that the message just prints out the whole Class-Path found in the MANIFEST.MF if _one_ dependency can't be found. I should have red the message more carefully _...one or more files that do not exist..._

**Comment by briandealwis** [comment] 2019-04-09 09:32
My guess is that you have the`maven-jar-plugin` configured to `<addClasspath>`.

**Comment by HJK181** [comment] 2019-04-09 10:01
> My guess is that you have the`maven-jar-plugin` configured to `<addClasspath>`.

That's correct! Is this a problem, can I just ignore the message and everything work fine or do I need to change the _maven-jar_plugin_ in the core? As the core is manged by us it would be possible, but if it's in a external dependency what would be the solution?

**Comment by briandealwis** [comment] 2019-04-09 14:20
It's just a warning.  Jib will have added the dependencies to `/app/libs` and included them on the command-line.

Do you need to change your use of `maven-jar-plugin`?  To me, a `Class-Path` header only makes sense for a runnable jar (`java -jar xxx.jar`): it's really just a short-cut to avoid specifying additional jar files on the command line.  As you're seeing, adding the `Class-Path` header to a *library* makes the library fragile as (1) it is assuming a file-system layout that may not actually apply, and (2) it is referencing different versions that what is actually being deployed in the actual product.

Closing this issue as the cause is not Jib.

**Closed by briandealwis** 2019-04-09 14:20 UTC

**Comment by neoword** [comment] 2019-06-21 22:18
@briandealwis corollary to this, any support for docker `--build-arg`?
This example showed that dockerfile-maven-plugin supports  docker buildArgs.
Typically docker buildArgs are used in the customization of a `<FROM>` (base) image.

Is there a workaround? Happy to open new issue if that is a better place for this.

**Comment by briandealwis** [comment] 2019-06-22 00:39
@neoward it is best to open new issues and reference issues that you think might apply. That said you can use specify the base image either from your pom.xml / build.script or by using the `jib.from.image` property.
