### ISSUE TITLE
Enable jetty quickstart + bypassing start.jar

### ISSUE THREAD

**Issue by nilsonpontello** [GoogleContainerTools/jib#1685] opened 2019-05-02 14:18 UTC
I am looking forward to using jib as replacement for my current docker plugin but I got stuck in one final improvement. Quoting [jetty docs](https://www.eclipse.org/jetty/documentation/9.4.x/quickstart-webapp.html#_bypassing_start_jar):

> The Jetty start.jar mechanism is a very powerful and flexible mechanism for constructing a classpath and executing a configuration encoded in Jetty XML format. However, this mechanism does take some time to build the classpath. The start.jar mechanism can be bypassed by using the –dry-run option to generate and reuse a complete command line to start Jetty at a later time

```
$ RUN=$(java -jar $JETTY_HOME/start.jar --add-to-start=quickstart --dry-run)
$ eval $RUN
```

While playing with jib/maven/jetty  I've managed to enable quickstart by overwriting CMD command from base image but I haven't found a way to bypass the start.jar because it needs to be generated after my war is added inside the container.

How can I solve this? Any idea?

**Comment by chanseokoh** [comment] 2019-05-02 15:09
Although I just learned this Jetty feature today, here's what I think:

With `--dry-run`, seems like you actually need to run `start.jar` with all your contents, which means you do need to run the built image. This implies you have to build an image first and do something to make it work correctly. If this should work, I think it is inevitable you will have to set up some multi steps. I can't think of a way to do all this in a single Jib build step. As you know, Jib doesn't go into the business of being able to run an image. (Jib will by no way provide a runtime or attempt to run an image. Jib won't use the Docker runtime either), not to mention that Jib focuses on reproducibility and more declarative image building. So, the only way I can think of is you do the dry run in advance, look and check the output, and set it using `<entrypoint>` + `<args>` if that looks good. Of course, if you change your app, you may want to do the dry run again so that the start command is always up to date and compatible with your app. For that matter, you might want to automate this, but as I said, I think it is inevitable it involves some multi-step setup.

Also, reading the doc you linked

> Note that --dry-run may create a properties file in the temp directory and include it on the generated command line. If so, then a copy of the temporary properties file should be taken and the command line updated with it’s new persistent location.

I think you anyway have to check the output of the dry run and you may need to do some manual intervention because of the temp file creation.

Considering all these, I don't see a way to do this in a single declarative Jib building without actually running anything, and the only alternative is to set the right `<entrypoint>` in a declarative way.

**Comment by chanseokoh** [comment] 2019-05-07 14:37
Considering the above, I'll close this, but if you have further feedback, feel free to re-open.

**Closed by chanseokoh** 2019-05-07 14:37 UTC

**Comment by briandealwis** [comment] 2019-05-07 23:15
I wonder if @coollog's [autojib](https://github.com/coollog/autojib/) might work here...
