### ISSUE TITLE
Feature request: disallowing pushing to public repository

### ISSUE THREAD

**Issue by AxelHeathnet** [GoogleContainerTools/jib#2522] opened 2020-06-11 07:12 UTC
**Description of the issue**:
At the moment, when pushing to docker hub, the plugin does not verify whatever the destination repository is private. That could be a problem when testing new images as you’d risk to make them available in advance.

**Expected behavior**:
Just add an “allowInsecure” param to the “to” section, defaulted to true that would halt the build if pushing to a public registry.
Adding a whitelist of allowed repos would also help as people could put a list of allowed registries configured to not be public.
```xml
<allowInsecure>false<allowInsecure>
```

**Comment by loosebazooka** [comment] 2020-06-11 13:39
Can you explain how you ran into this? Most registries, even public ones require credentials.

I don't really see Jib implementing this. Restricting registries to *push* to seems like a process thing and not necessarily one that jib should be responsible for.

If you really wish to create policy that you can apply to all build files in your organization, you could potentially write your own extension to do it. (https://github.com/GoogleContainerTools/jib-extensions).

**Comment by AxelHeathnet** [comment] 2020-06-16 14:48
I was doing some tests with my personal registry on docker.hub. 
As you probably know docker hub only allows for 1 private repository in its free version, I wanted to try building an image that didn't have a repository associated.

I would have expected for it to fail, as the remote repository didn't even exist but what happened was that the image was successfully pushed and a new,  **public** repository for it was created.

I think this one is a bug, as it shouldn't create a repo on its own if it doesn't exists.

Then, suppose I incidentally create a public repository on docker hub but I'm not the one making the jib build: the person actually pushing is logged in and allowed to push on my registry, but they would push the image to a **public** repo which couldn't be always what I want.

**Comment by loosebazooka** [comment] 2020-06-16 15:07
I understand that this can be frustrating, but this is the exact same behavior as docker. Jib is merely implementing the registry API. How the remote registry handles this is really up to them. The registry settings at dockerhub seem to be the issue, perhaps there are some security constraints you can add there. Unfortunately it looks like that is something you must pay them for :disappointed: 

As we do not really consider this an issue that the core jib functionality should address, you can write a simple extension to solve this problem for you, as mentioned in my previous comment.

**Comment by chanseokoh** [comment] 2020-06-29 16:18
@AxelHeathnet I saw your thumbs-up. I agree with @loosebazooka. I confirmed myself that the Docker Hub default is to create a repo as public, whose default can only be changed with a paid option. Closing the issue.

**Closed by chanseokoh** 2020-06-29 16:18 UTC
