### ISSUE TITLE
BuildStepsExecutionException: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri

### ISSUE THREAD

**Issue by jamesward** [GoogleContainerTools/jib#2519] opened 2020-06-09 22:25 UTC
**Environment**:

- *Jib version:* 2.4.0
- *Build tool:* Gradle 6.5
- *OS:* Linux

**Description of the issue**:
I ran:
```
./gradlew :server:jib --image=grpc-kotlin-sample-androi
```
Got:
```
Execution failed for task ':server:jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/RequestConfig$Builder;
```

**Expected behavior**:
No error

**Steps to reproduce**:
I'm working on a project to reproduce and will share that shortly.

**Comment by jamesward** [comment] 2020-06-09 23:12
Here is the project I tried this one:
https://github.com/jamesward/kotlin-samples/tree/master/run/grpc-sample-android

I tried adding jib to the `server` subproject.

**Comment by chanseokoh** [comment] 2020-06-09 23:14
I suspect https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building. This seems like a duplicate of #2183 (as mentioned in the FAQ).

**Comment by chanseokoh** [comment] 2020-06-18 15:37
I'm pretty sure this is a dup of #2183. The [FAQ above](https://github.com/GoogleContainerTools/jib/issues/2519#issuecomment-641628476) explains a fix.

**Closed by chanseokoh** 2020-06-18 15:37 UTC

**Comment by golery** [comment] 2021-01-16 22:09
For my case, I use maven with version 0.34.1. Just downgrade to 0.34.0 and it works.
