### ISSUE TITLE
comand and tomcat war support

### ISSUE THREAD

**Issue by SnowerWkh** [GoogleContainerTools/jib#646] opened 2018-07-18 05:48 UTC
**Description of the issue**:

 * I want to deploy an tomcat app  with a base image, but not have relative parameters can config  comand to start container  in labels "configuration",  "mainClass" is not satisfy
* I can't put my application war into the specified location of the base image.

**Expected behavior**:

* put my application war into the specified location of the base image；
* can config comand to start container  in labels "configuration"

Thanks for contributing!

**Comment by coollog** [comment] 2018-07-18 14:05
Hi @SnowerWkh , thanks for filing this issue! We are actively working on support for WARs in #431 .

**Comment by YJFinBJ** [comment] 2018-07-19 11:41
- I would like to deploy java war  on a tomcat ,so I use a tomcat base image, and I also have not just like "mainClass", I use entrypoint ["catalina.sh",run] in my dockerfile
- There is some JVM  profiles args

**Comment by coollog** [comment] 2018-07-19 12:59
Hi @YJFinBJ , what sorts of instructions are you performing in your entrypoint script (`catalina.sh`)? The default base image `gcr.io/distroless/java` does not include a shell by design. If you'd like to use an entrypoint script, you can use the `gcr.io/distroless/java:debug` image or another base image that includes a shell. 

Are you calculating JVM args in your entrypoint script? If not, I would recommend either setting them using the `jvmFlags` parameter or adding them via the `JAVA_TOOL_OPTIONS` environment variable at run time.

**Comment by chanseokoh** [comment] 2018-07-19 17:46
@YJFinBJ we are currently gearing toward using Jetty instead of Tomcat, at least for now, for WAR support: #431. If people find Jetty lacking some functionalities and need Tomcat, we can think about the feature to switch the servlet engine.

**Comment by YJFinBJ** [comment] 2018-07-20 01:58
Hi  @coollog @chanseokoh    There is start/stop Bootstrap in catalina.sh,and also some env args like JAVA_OPTS etc.   And JVM args can setting them in jvmFlags that's OK
But since you are currently gearing toward using Jetty,do you have any demo with war package deploy on jetty, jetty is similar with tomcat I think

**Comment by chanseokoh** [comment] 2018-07-20 02:05
@YJFinBJ this may be helpful: https://github.com/GoogleContainerTools/jib/issues/431#issuecomment-406356286

**Comment by YJFinBJ** [comment] 2018-07-20 02:19
HI  @chanseokoh  I still have another question maybe not abt this issue.
[ERROR] No plugin found for prefix 'jib' in the current project and in the plugin groups 
 how to set my repository in my ./m2/settings, and I cann't package jib-maven-plugin upload to our own maven repository myself

**Comment by coollog** [comment] 2018-08-03 17:33
Closing this in favor of #431. For WAR use cases now, we recommend converting to a JAR with embedded Tomcat (via dependencies under `org.apache.tomcat.embed`).

**Closed by coollog** 2018-08-03 17:33 UTC
