### ISSUE TITLE
Jib built image file date 1970 problem

### ISSUE THREAD

**Issue by soulmz** [GoogleContainerTools/jib#1800] opened 2019-06-21 07:42 UTC
**Description of the issue**:

Projects are SpringBoot and Vue, Web projects
The front end is placed in the resources/static file.
Recently, I changed it to the Jib package. When Http accesses, the cache is very serious.
The browser is based on the last modification time to determine whether to cache, all 304.
Based on the JIb packaged project, the file modification time is 1970.
Therefore, the browser cannot update the file.

http response header by file all:

`last-modified: Thu, 01 Jan 1970 00:00:01 GMT`

is not:

`Last-Modified:Fri, 21 Jun 2019 06:45:40 GMT`

中文描述:

项目是 SpringBoot 和 Vue ，Web项目
前端放在 resources/static 文件内。
最近，改成Jib方式打包。Http访问时，缓存很严重。
浏览器是基于 最后修改时间 判断是否缓存，全 304。
基于JIb打包的项目，文件的修改时间都是 1970 。
因此，浏览器出现无法更新文件。

http 响应的文件头: 
`last-modified: Thu, 01 Jan 1970 00:00:01 GMT` 

并不是 

`Last-Modified:Fri, 21 Jun 2019 06:45:40 GMT`

**Expected behavior**:

I think all the file is 1970, not the right behavior

```bash
root@e5946250a9b5:/app# ls resources/ -l
total 24
-rw-r--r-- 1 root root 2432 Jan  1  1970 application.yml
drwxr-xr-x 3 root root 4096 Jan  1  1970 com
-rw-r--r-- 1 root root  966 Jan  1  1970 data.sql
-rw-r--r-- 1 root root  685 Jan  1  1970 rebel.xml
-rw-r--r-- 1 root root  347 Jan  1  1970 schema-h2.sql
drwxr-xr-x 2 root root 4096 Jan  1  1970 static
```

**I want to see like this: **

```bash
root@e5946250a9b5:/app# ls resources/ -l
total 24
-rw-r--r-- 1 root root 2432 Jun 21 15:42 application.yml
drwxr-xr-x 1 root root 4096 Jun 21 15:42 com
-rw-r--r-- 1 root root  966 Jun 21 15:42 data.sql
-rw-r--r-- 1 root root  685 Jun 21 15:42 rebel.xml
-rw-r--r-- 1 root root  347 Jun 21 15:42 schema-h2.sql
drwxr-xr-x 1 root root 4096 Jun 21 15:42 static

```

**Steps to reproduce**:

**Environment**: 

MacOS , Maven

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.3.0</version>
                <configuration>
                    <from>
                        <!--base image-->
                        <image>openjdk:8u212</image>
                    </from>
                    <container>
                        <labels>
                            <MAINTAINER>soulmz</MAINTAINER>
                        </labels>
                        <workingDirectory>/app</workingDirectory>
                        <environment>
                            <!-- 时区 -->
                            <TZ>Asia/Shanghai</TZ>
                            <!-- 强制设置默认 8080端口 -->
                            <SERVER_PORT>8080</SERVER_PORT>
                        </environment>
                        <useCurrentTimestamp>true</useCurrentTimestamp>
                        <!-- 可选操作 -->
                        <ports>
                            <port>8080</port>
                        </ports>
                        <volumes>
                            <volume>/app/logs</volume>
                            <volume>/app/heapdump</volume>
                        </volumes>
                    </container>
                    <to>
                        <image>demo:v1.0.0</image>
                    </to>
                </configuration>
            </plugin>
```

**Log output**: 

**Additional Information**: 

I think that is a great plugin jib。 thx

**Comment by chanseokoh** [comment] 2019-06-21 15:44
Hi @soulmz,

This is the intended behavior and explained in this FAQ: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago

For now, you can set the current timestamp for the image creation time with `<useCurrentTimestamp>`, but as explained in the FAQ, you should be aware that this will lead to non-reproducible builds.

While we are at it, we have an open issue for another option (#1609) for more flexible configuration for the creation time.

FTR, #1608 is also slightly related, but #1608 is for the timestamps in the files in an image.

**Comment by chanseokoh** [comment] 2019-06-21 15:45
I'm closing this issue, but feel free to re-open if you have more feedback.

**Closed by chanseokoh** 2019-06-21 15:45 UTC

**Comment by soulmz** [comment] 2019-06-22 02:04
@chanseokoh 

yeah，I need This feature. 

Because you can't guarantee anything, all users can as you have expected such behavior.

It makes me very headache now。
