### ISSUE TITLE
adoptopenjdk base image is deprecated and add support for Java 17 

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#3483] opened 2021-10-21 16:29 UTC
> https://hub.docker.com/_/adoptopenjdk
> 
> DEPRECATED; use https://hub.docker.com/_/eclipse-temurin/

Might be worth checking out eclipse-temurin or another alternative

**Comment by chanseokoh** [comment] 2021-11-01 21:17
Another issue: currently ASM [can't examine bytecode of newer Java versions](https://stackoverflow.com/q/69798822/1701388), so this also needs to be taken care of.

**Comment by Sineaggi** [comment] 2021-11-01 22:24
Perhaps we should create a new issue investigating if we can try/catch that issue and log possible solutions in the future.

**Comment by chanseokoh** [comment] 2021-11-10 19:57
Going with [`eclipse-temurin` for Java 8 and 11, and `azul/zulu-openjdk` for Java 17](https://github.com/GoogleContainerTools/jib/pull/3498/files#diff-95d01a6e5ce434c5d813aa4c91f0d8526ea0f537348ace1537377672a19c6799R5).

**Comment by chanseokoh** [comment] 2021-11-11 15:08
Fixed by #3491 and #3499.

**Comment by racevedoo** [comment] 2021-12-23 17:49
Actually temurin now ships JREs: https://blog.adoptium.net/2021/12/eclipse-temurin-jres-are-back/

**Comment by chanseokoh** [comment] 2022-01-05 16:26
Fortunately, we haven't released the base image change (#3491). For consistency, we will use Temurin for Java 17 as well.

**Comment by FlorianAgilap** [comment] 2022-01-13 10:11
Hello,
I was wondering if there was any expected date of release for the support of Java 17 by JIB ?
We upgraded our whole projet to Java 17 recently, and only just noticed that one of the subprojects relies on JIB. So a release date expectation would help us know whether we can just wait for it, find a workaround, rollback to Java 11 or anything...
Thanks in advance !

**Comment by chanseokoh** [comment] 2022-01-14 22:12
Will release a new version next week.

But if you have a build failure due to ASM, there is a [workaround](https://stackoverflow.com/a/69802995/1701388). If the problem is about Jib not automatically selecting a working base image for Java 17, you can always configure `from.image` yourself to point to any suitable JRE image (e.g., `eclipse-temurin:17-jre`).

**Comment by fblampe** [comment] 2022-01-18 14:26
[default_base_image.md](docs/default_base_image.md) (first sentence) still links to the deprecated AdoptOpenJdk image. It also mentions the project being renamed to Adoptium, but now it's already called Eclipse Temurin.

Should probably be updated to prevent confusion.

**Comment by chanseokoh** [comment] 2022-01-18 15:04
@fblampe the doc will be updated once there's a new release.

**Closed** 2022-03-29 21:55 UTC
Labels: p1
