### ISSUE TITLE
Jib seems to strip .war file META-INF/ contents from image

### ISSUE THREAD

**Issue by edrandall** [GoogleContainerTools/jib#2064] opened 2019-10-14 22:23 UTC
**Environment**:

- *Jib version:* 1.6.1
- *Build tool:* maven: 3.6.0
- *OS:* MacOS 10.14.4 / bash 3.2.57(1)

**Description of the issue**:

/META-INF/MANIFEST.MF (and accompanying maven metadata files) were present in the .war file, but have been stripped from the built image.

** .war file contents **
```
   632 Mon Oct 14 22:58:40 BST 2019 META-INF/MANIFEST.MF
     0 Mon Oct 14 22:58:40 BST 2019 META-INF/
 17492 Mon Oct 14 22:54:14 BST 2019 META-INF/maven/.../pom.xml
    85 Mon Oct 14 22:58:38 BST 2019 META-INF/maven/.../pom.properties
```
** Image contents **
Directory is present, but empty:
```
drwxr-xr-x  0 0      0           0 14 Oct 13:03 apps/apache-tomcat/web/META-INF/
```

**Expected behavior**:
Final image will contain all files from .war including META-INF/ directory

**Steps to reproduce**:

  1.  Build .war using maven-war-plugin:war; a META-INF/MANIFEST.MF is generated in the .war file as part of this process
  2. Use jib-maven-plugin:dockerBuild to overlay the .war on an image ie.
	

**`jib-maven-plugin` Configuration**: 
```xml
	<plugin>
		<groupId>com.google.cloud.tools</groupId>
		<artifactId>jib-maven-plugin</artifactId>
		<version>1.6.1</version>
		<executions>
			<execution>
				<id>jib-build</id>
				<phase>install</phase>
				<goals>
					<goal>dockerBuild</goal>
				</goals>
				<configuration>
					<container>
						<appRoot>/apps/apache-tomcat/web</appRoot>
						<user>username</user>
					</container>
					<from>
						<image>${jib.base.image}</image>
					</from>
					<to>
						<image>${jib.target.image}</image>
					</to>
				</configuration>
			</execution>
		</executions>
	</plugin>

```

**Comment by chanseokoh** [comment] 2019-10-14 22:35
Hi @edrandall,

Yeah, this is because the way Jib works: Jib does not simply take a WAR and put it into the image as-is, but puts exploded WAR contents by default for better image layering.

For JAR packaging, you can actually make Jib put a JAR as-is with `<containerizingMode>packaged`, but this feature is not implemented for WAR. It looks like you are the first user to request this! That said, we are really curious, what exactly do you need from `META-INF/MANIFEST.MF` (or other files) for what? We'd like to understand users' use cases correctly so that we can help people build images in the right way.

And, I wonder if you can switch your project from WAR to JAR, although I'm not so optimistic honestly.

**Comment by chanseokoh** [comment] 2019-10-14 22:44
> Yeah, this is because of the way Jib works: Jib does not simply take a WAR and put it into the image as-is, but puts exploded WAR contents by default for better image layering.

Oh, actually, on second thought, because Jib is supposed to explode the WAR, so `META-INF/` and all the stuff in it should end up landing in the image, which isn't the case here. For Gradle, I believe it will work, but for Maven, we are not actually exploding the WAR yet: #1091. That said, this issue is practically a duplicate of #1091.

But we are still very curious of your use case and why you want this for what.

**Comment by chanseokoh** [comment] 2019-10-14 22:49
Closing as a dup of #1091. Feel free to update this issue.

**Closed by chanseokoh** 2019-10-14 22:49 UTC

**Comment by edrandall** [comment] 2019-10-15 06:58
Whilst this ticket might technically be a duplicate of #1091 it's in no way obvious that the final deployment will be altered in this way.
