### ISSUE TITLE
NPE on maven with the command jib:build

### ISSUE THREAD

**Issue by BkSouX** [GoogleContainerTools/jib#1815] opened 2019-06-28 08:53 UTC
Hi,

I have a Null Pointer Exception when running the command jib build.
Here is the stacktrace :

```
+ ./mvnw compile jib:build -Dimage=registry.****.local:9999/layout-api -Djib.to.tags=40

[INFO] Scanning for projects...

[INFO] 
[INFO] -----------------------< com.layout:layout-api >------------------------
[INFO] Building api 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------

[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ layout-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource

[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ layout-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- jib-maven-plugin:1.3.0:build (default-cli) @ layout-api ---

[INFO] 
[INFO] Containerizing application to registry.****.local:9999/layout-api, registry.****.local:9999/layout-api:40...
[INFO] Retrieving registry credentials for registry.****.local:9999...
[INFO] Getting base image gcr.io/distroless/java:11...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...

juin 28, 2019 10:45:51 AM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
GRAVE: Got more than one input Future failure. Logging failures after the first
java.lang.NullPointerException: layerDiffId required
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.cloud.tools.jib.cache.CachedLayer$Builder.build(CachedLayer.java:66)
	at com.google.cloud.tools.jib.cache.CacheStorageReader.retrieve(CacheStorageReader.java:186)
	at com.google.cloud.tools.jib.cache.Cache.retrieve(Cache.java:161)
	at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:78)
	at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:37)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

And the pom : 

```
<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>1.3.0</version>
				<configuration>
					<to>
						<image>layout-api</image>
					</to>
					<allowInsecureRegistries>true</allowInsecureRegistries>
					<container>
						<jvmFlags>
							<jvmFlag>-Xverify:none</jvmFlag>
							<jvmFlag>-XX:TieredStopAtLevel=1</jvmFlag>
						</jvmFlags>
					</container>
				</configuration>
			</plugin>
```

It seems to work when running on another server and it worked multiple times before having that issue.

Any idea what could be the problem ?

**Comment by chanseokoh** [comment] 2019-06-28 12:40
Hi @BkSouX 

It is obvious that the local Jib cache (somewhere under your home directory, not the Docker local cache) is incomplete (or corrupted). Clearing the cache will resolve the issue, but before doing that, can you try to recall what you did that led to this cache corruption?

**Comment by loosebazooka** [comment] 2019-07-02 20:37
@BkSouX did you try clearing the cache and rebuilding?

Perhaps we should provide a better error message here.

**Comment by chanseokoh** [comment] 2019-07-02 21:25
@loosebazooka coincidentally, I cleaned up the code around this a few days ago, and Jib will start surfacing CacheCorruptedException in the new 1.4.0 release:

https://github.com/GoogleContainerTools/jib/pull/1812/files#diff-35c774453081c8bec8cc3f74d37116fbR169

The old code was not catching the case where the layer file does not exist.

**Comment by BkSouX** [comment] 2019-07-04 06:41
> @BkSouX did you try clearing the cache and rebuilding?
> 
> Perhaps we should provide a better error message here.

No idea, nothing special I think. Im using it in a jenkins pipeline.

**Comment by chanseokoh** [comment] 2019-07-18 21:40
Having recently looked into Jib's async and cache code, I can theorize one possibility where it may happens when a previous Jib Maven/Gradle build failed.

```
+ ./mvnw compile jib:build -Dimage=registry.****.local:9999/layout-api -Djib.to.tags=40

...

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ layout-api ---
[INFO] Nothing to compile - all classes are up to date
```

From the log, this `./mvnw compile jib:build` isn't the first build, as classes were already compiled.

My theory is based on the observation that async threads will simply die when a JVM exits. For example, suppose a thread was downloading and caching a base image layer, while another thread was trying authentication with a target registry. The latter auth thread couldn't auth with the server due to wrong credentials, throws an exception, and terminates the Maven build (JVM) immediately. Apparently, the JVM doesn't wait for threads still running, and the thread downloading a layer is terminated abruptly. This is all my speculation, but given that any error will just kill concurrent threads, this could really be a problem if we are not guarding against this properly.

**Comment by chanseokoh** [comment] 2020-01-23 21:31
As mentioned in https://github.com/GoogleContainerTools/jib/issues/1815#issuecomment-506719367 and https://github.com/GoogleContainerTools/jib/issues/1815#issuecomment-507850405, the situation is that

- The layer directory `<Jib cache>/layers/<layer digest>` exists. (Otherwise, it would have short-circuited [here](https://github.com/GoogleContainerTools/jib/pull/1812/files#diff-35c774453081c8bec8cc3f74d37116fbL162 ).)
- The existence of the directory implies that it must have contained a single layer content blob file. However, reaching [here](https://github.com/GoogleContainerTools/jib/pull/1812/files#diff-35c774453081c8bec8cc3f74d37116fbL186) to hit NPE means there was no layer blob file inside the directory to [initialize builder fields](https://github.com/GoogleContainerTools/jib/pull/1812/files#diff-35c774453081c8bec8cc3f74d37116fbL178-L182).

Note, our cache mechanism creates a layer directory by trying to atomically moving a temporary directory. A temporary directory must have already contained a layer content blob file. But the fact that at the time of execution the final layer directory was an empty directory.

So I think this situation is possible if the file system did not support atomic directory move. We cannot confirm this with little information, but I this is certainly possible if atomic move degrades to copying. I'll close this as a duplicate of #1044.

**Closed by chanseokoh** 2020-01-23 21:31 UTC
