### ISSUE TITLE
SocketTimeoutException behind Proxy

### ISSUE THREAD

**Issue by mheidt** [GoogleContainerTools/jib#1816] opened 2019-06-28 14:47 UTC
I am running behind corporate proxy and the registry is within the local network, so that I am using a .mvn/jvm.config with the proxy parameters.

It took me some time, to realize, that I had to  run the following command to get beyond the authorization. 

./mvnw jib:build -Dhttp.nonProxyHosts="localhost|*.dlh.de"

I had expected that .mvn/jvm.config would be enough. It was using the proxy settings. why not nonProxyHosts as well?

The major issue is a SocketTimeoutException I can't explain.
Is the socket opened without considering proxy settings?

The configuration in the pom:
```xml
<configuration>
                        <from>
                            <image>adoptopenjdk:11-jre-hotspot</image>
                        </from>
                        <to>
                            <image>registry.cute.dlh.de:5000/cnews:latest</image>
                        </to>
                        <container>
                            <entrypoint>
                                <shell>sh</shell>
                                <option>-c</option>
                                <arg>chmod +x /entrypoint.sh &amp;&amp; sync &amp;&amp; /entrypoint.sh</arg>
                            </entrypoint>
                            <ports>
                                <port>8080</port>
                                <port>5701/udp</port>
                            </ports>
                            <environment>
                                <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
                                <JHIPSTER_SLEEP>0</JHIPSTER_SLEEP>
                            </environment>
                            <useCurrentTimestamp>true</useCurrentTimestamp>
                        </container>
                       <allowInsecureRegistries>true</allowInsecureRegistries>
</configuration>
```

And the --debug enabled output:

INFO]  TIMING  Retrieving registry credentials for registry.cute.dlh.de:5000
[INFO]  TIMING  Pulling base image manifest
[INFO]  TIMING  Building application layers
[INFO]  TIMED   Building application layers : 1.0 ms
[INFO]  TIMING  Building classes layer
[INFO]  TIMING  Building resources layer
[INFO]  TIMING  Building extra files layer
[INFO]  TIMING  Building dependencies layer
[INFO]  TIMING  Setting up to push layers
[INFO]  TIMED   Setting up to push layers : 7.0 ms
[INFO]  TIMED   Building classes layer : 315.0 ms
[INFO]  TIMED   Building extra files layer : 313.0 ms
[INFO]  TIMED   Building resources layer : 314.0 ms
[INFO]  TIMED   Building dependencies layer : 318.0 ms
[INFO]  No credentials could be retrieved for registry registry.cute.dlh.de:5000
[INFO]  TIMED   Retrieving registry credentials for registry.cute.dlh.de:5000 : 350.0 ms
[INFO]  TIMING  Authenticating with push to registry.cute.dlh.de:5000
[INFO] The base image requires auth. Trying again for adoptopenjdk:11-jre-hotspot...
[INFO]  TIMING  Retrieving registry credentials for registry-1.docker.io
[INFO]  No credentials could be retrieved for registry registry-1.docker.io
[INFO]  TIMED   Retrieving registry credentials for registry-1.docker.io : 4.0 ms
[INFO]  TIMED   Pulling base image manifest : 4403.0 ms
[INFO]  TIMING  Setting up base image caching
[INFO]  TIMED   Setting up base image caching : 2.0 ms
[INFO]  TIMING  Pulling base image layer sha256:3cf0a0f024f7858fb52dfe83162e093ed44d195a987007b5478be7ea693cc8a6
[INFO]  TIMING  Pulling base image layer sha256:5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd
[INFO]  TIMING  Pulling base image layer sha256:a31c3b1caad473a474d574283741f880e37c708cc06ee620d3e93fa602125ee0
[INFO]  TIMING  Pulling base image layer sha256:14ca88e9f6723ce82bc14b241cda8634f6d19677184691d086662641ab96fe68
[INFO]  TIMING  Pulling base image layer sha256:b054a26005b7f3b032577f811421fab5ec3b42ce45a4012dfa00cf6ed6191b0f
[INFO]  TIMED   Pulling base image layer sha256:5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd : 0.0 ms
[INFO]  TIMED   Pulling base image layer sha256:b054a26005b7f3b032577f811421fab5ec3b42ce45a4012dfa00cf6ed6191b0f : 0.0 ms
[INFO]  TIMED   Pulling base image layer sha256:14ca88e9f6723ce82bc14b241cda8634f6d19677184691d086662641ab96fe68 : 0.0 ms
[INFO]  TIMED   Pulling base image layer sha256:3cf0a0f024f7858fb52dfe83162e093ed44d195a987007b5478be7ea693cc8a6 : 0.0 ms
[INFO]  TIMED   Pulling base image layer sha256:a31c3b1caad473a474d574283741f880e37c708cc06ee620d3e93fa602125ee0 : 0.0 ms
[INFO]  TIMING  Pulling base image layer sha256:b7ae501a5b5f94ca0383b1ea4e08bf8567051e870c94cf9faa08376548dcbcb2
[INFO]  TIMING  Setting up to push layers
[INFO]  TIMED   Pulling base image layer sha256:b7ae501a5b5f94ca0383b1ea4e08bf8567051e870c94cf9faa08376548dcbcb2 : 1.0 ms
[INFO]  TIMED   Setting up to push layers : 0.0 ms
[INFO]  TIMING  Building container configuration
[INFO]
[INFO] Container entrypoint set to [sh, -c, chmod +x /entrypoint.sh && sync && /entrypoint.sh]
[INFO]  TIMED   Building container configuration : 2.0 ms
[INFO]  TIMED   Authenticating with push to registry.cute.dlh.de:5000 : 20478.0 ms
[INFO]  TIMED   Building and pushing image : 20987.0 ms
[INFO] Executing tasks:
[INFO] [==================            ] 60.0% complete
[INFO] > setting up to push layers
[INFO] > setting up to push layers
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.868 s
[INFO] Finished at: 2019-06-28T16:25:59+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.3.0:build (default-cli) on project cnews: connect timed out -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.3.0:build (default-cli) on project cnews: connect timed out
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
Caused by: org.apache.maven.plugin.MojoExecutionException: connect timed out
    at com.google.cloud.tools.jib.maven.BuildImageMojo.execute (BuildImageMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.DualStackPlainSocketImpl.waitForConnect (Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect (DualStackPlainSocketImpl.java:85)
    at java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:188)
    at java.net.PlainSocketImpl.connect (PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect (SocksSocketImpl.java:392)
    at java.net.Socket.connect (Socket.java:589)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket (SSLSocketFactory.java:542)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket (SSLSocketFactory.java:414)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket (SSLSocketFactory.java:488)
    at org.apache.http.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket (SchemeSocketFactoryAdaptor.java:66)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection (DefaultClientConnectionOperator.java:180)
    at org.apache.http.impl.conn.AbstractPoolEntry.open (AbstractPoolEntry.java:144)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open (AbstractPooledConnAdapter.java:134)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect (DefaultRequestDirector.java:610)
    at org.apache.http.impl.client.DefaultRequestDirector.execute (DefaultRequestDirector.java:445)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute (AbstractHttpClient.java:835)
    at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:108)
    at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:56)
    at com.google.api.client.http.apache.ApacheHttpRequest.execute (ApacheHttpRequest.java:65)
    at com.google.api.client.http.HttpRequest.execute (HttpRequest.java:1011)
    at com.google.cloud.tools.jib.http.Connection.send (Connection.java:200)
    at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call (RegistryEndpointCaller.java:254)
    at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.callWithAllowInsecureRegistryHandling (RegistryEndpointCaller.java:174)
    at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call (RegistryEndpointCaller.java:164)
    at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint (RegistryClient.java:355)
    at com.google.cloud.tools.jib.registry.RegistryClient.getRegistryAuthenticator (RegistryClient.java:181)
    at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call (AuthenticatePushStep.java:89)
    at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call (AuthenticatePushStep.java:43)
    at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly (CombinedFuture.java:180)
    at com.google.common.util.concurrent.InterruptibleTask.run (InterruptibleTask.java:57)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)

Thanks a lot

**Comment by chanseokoh** [comment] 2019-06-28 15:17
Hit @mheidt,

Can you share the contents of `.mvn/jvm.config` if possible?

> The major issue is a `SocketTimeoutException` I can't explain.

I am confused. Does this happen when you do not provide `-Dhttp.nonProxyHosts` on the command line or after you do so?

**Comment by chanseokoh** [comment] 2019-06-28 15:20
And do you have any proxy configuration in your Maven `settings.xml`?

**Comment by mheidt** [comment] 2019-06-28 15:26
-Dhttp.proxyHost=correct value
-Dhttp.proxyPort=correct value
-Dhttps.proxyHost=correct value
-Dhttps.proxyPort=correct value
-Dhttp.proxyUser=correct value
-Dhttp.proxyPassword=correct value
-Dhttp.nonProxyHosts="localhost|dlh.de"

And yes, the user based settings.xml contains the same

`<proxy>
            <id></id>
            <active>true</active>
            <protocol>http</protocol>
            <username></username>
            <password></password>
            <host></host>
            <port></port>
            <nonProxyHosts>localhost|*.dlh.de</nonProxyHosts>
        </proxy>`

**Comment by mheidt** [comment] 2019-06-28 15:29
When I do not provide the -Dhttp.nonProxyHost the corporate proxy kicks in a step earlier aka authentication

[===============               ] 50.0% complete
[INFO] > setting up to push layers
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.372 s
[INFO] Finished at: 2019-06-28T17:28:02+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.3.0:build (default-cli) on project cnews: Build image failed, perhaps you should make sure you have permissions for registry.cute.dlh.de:5000/cnews and set correct credentials. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-forbidden-or-denied for help: Unauthorized for registry.cute.dlh.de:5000/cnews: 403 URLBlocked
[ERROR]
[ERROR] <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
[ERROR] <html>
[ERROR] <head>
[ERROR] <meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
[ERROR] <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
[ERROR] <title>Connection Fail</title>

**Comment by chanseokoh** [comment] 2019-06-28 16:54
The setting in `.mvn/jvm.config` is different. I have manually verified that
```
-Dhttp.nonProxyHosts="localhost|dlh.de"
```
doesn't catch `registry.cute.dlh.de`. Change it to
```
-Dhttp.nonProxyHosts="localhost|*.dlh.de"
```
I am pretty sure it will work then.

**Comment by mheidt** [comment] 2019-07-01 07:53
Sorry for my blindness.
When i change the value in jvm.config, it works. 
But I still need the -Dhttp.nonProxyHosts parameter.

I expected that the -D parameter overwrites it in all cases though. But I reckon that the libraries that are used are just prioritizing differently.

**Comment by chanseokoh** [comment] 2019-07-01 14:38
Thanks for the update. I believe the issue is resolved, so I'm going to close this. If it isn't the case or you have a concern, feedback, or other opinions, feel free to re-open, and we can discuss furher.

**Closed by chanseokoh** 2019-07-01 14:38 UTC
