### ISSUE TITLE
Unable to build Docker image

### ISSUE THREAD

**Issue by naushadamin** [GoogleContainerTools/jib#863] opened 2018-08-21 17:19 UTC
**Description of the issue**:
Getting the following exception while trying to push a Docker image  to private Nexus reop

Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates (SSLSessionImpl.java:440)
    at org.apache.http.conn.ssl.AbstractVerifier.verify (AbstractVerifier.java:128)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket (SSLSocketFactory.java:339)

I've configured the following property in my pom.xml:

`<allowInsecureRegistries>true</allowInsecureRegistries>`

So I don't expect the SSL handshake to take place. What am I doing wrong? I am able to push successfully to the same repo using spotify plugin.

**Expected behavior**: Able to push image successfully

**Steps to reproduce**:  running 'mvn compile -e jib:build' 

**Environment**: 
OSX High Sierra
JDK 1.8
Maven 3

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
              <groupId>com.google.cloud.tools</groupId>
              <artifactId>jib-maven-plugin</artifactId>
              <version>0.9.7</version>
              <configuration>
              <from>
                <image>openjdk:8u171-alpine</image>
               
              </from>
              <to>
               <image>$host:$port/${project.artifactId}:${project.version}</image>
          
             </to>
             <container>
                <jvmFlags>
                <jvmFlag>-Xms512m</jvmFlag>
                <jvmFlag>-Xmx512m</jvmFlag>
                </jvmFlags>
             </container>
             <allowInsecureRegistries>true</allowInsecureRegistries>
              </configuration>
          </plugin>
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.7:build (default-cli) on project specialorderreceiving: Build image failed: peer not authenticated -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.7:build (default-cli) on project specialorderreceiving: Build image failed
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Build image failed
    at com.google.cloud.tools.jib.maven.BuildImageMojo.execute (BuildImageMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates (SSLSessionImpl.java:440)
    at org.apache.http.conn.ssl.AbstractVerifier.verify (AbstractVerifier.java:128)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket (SSLSocketFactory.java:339)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection (DefaultClientConnectionOperator.java:123)
    at org.apache.http.impl.conn.AbstractPoolEntry.open (AbstractPoolEntry.java:147)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open (AbstractPooledConnAdapter.java:108)
    at org.apache.http.impl.client.DefaultRequestDirector.execute (DefaultRequestDirector.java:415)
    at org.apache.http.impl.client.AbstractHttpClient.execute (AbstractHttpClient.java:641)
    at org.apache.http.impl.client.AbstractHttpClient.execute (AbstractHttpClient.java:576)
    at org.apache.http.impl.client.AbstractHttpClient.execute (AbstractHttpClient.java:554)
    at com.google.api.client.http.apache.ApacheHttpRequest.execute (ApacheHttpRequest.java:65)
    at com.google.api.client.http.HttpRequest.execute (HttpRequest.java:981)
    at com.google.cloud.tools.jib.http.Connection.send (Connection.java:130)
    at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call (RegistryEndpointCaller.java:173)
    at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call (RegistryEndpointCaller.java:244)
    at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call (RegistryEndpointCaller.java:141)
    at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint (RegistryClient.java:338)
    at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest (RegistryClient.java:213)
    at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest (RegistryClient.java:221)
    at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImage (PullBaseImageStep.java:177)
    at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call (PullBaseImageStep.java:109)
    at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call (PullBaseImageStep.java:54)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly (TrustedListenableFutureTask.java:127)
    at com.google.common.util.concurrent.InterruptibleTask.run (InterruptibleTask.java:57)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run (TrustedListenableFutureTask.java:80)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)

**Additional Information**:

**Comment by briandealwis** [comment] 2018-08-22 01:43
I think this indicates that your peer's certificate has expired.  `allowInsecureRegistries=true` only disables trust validation of the certificate chain.

**Comment by briandealwis** [comment] 2018-09-07 11:05
@naushadamin your error is happening when pulling the base image `openjdk` from Docker Hub!
```
com.google.cloud.tools.jib.registry.RegistryClient.pullManifest (RegistryClient.java:213)
at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest (RegistryClient.java:221)
at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImage (PullBaseImageStep.java:177)
```

Are you behind a proxy?

Does OpenSSL report any errors when running the following?
```
openssl s_client -connect registry.hub.docker.com:443 < /dev/null
```

Would you please follow the procedure in the FAQ to [obtain a network trace](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic) and attach the full log here? (Eliding your internal identifiers, of course.)

**Comment by naushadamin** [comment] 2018-09-17 20:35
Below is the output from openssl s_client -connect registry.hub.docker.com:443 < /dev/null

openssl s_client -connect registry.hub.docker.com:443 < /dev/null
CONNECTED(00000006)
depth=0 CN = *.hub.docker.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.hub.docker.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 CN = *.hub.docker.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=*.hub.docker.com
   i:/CN=GPCNETWORKCA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDKTCCAhGgAwIBAgIRAO+SsGnFtY1Iwo/orkujMAAwDQYJKoZIhvcNAQELBQAw
FzEVMBMGA1UEAxMMR1BDTkVUV09SS0NBMB4XDTE4MDcxOTAwMDAwMFoXDTE5MDgx
OTEyMDAwMFowGzEZMBcGA1UEAwwQKi5odWIuZG9ja2VyLmNvbTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAOcW97+lRKrmcerAP1jINbwg/K46m6yweeCC
ErzXMdNlwnLtqvCDWmQwzSfbTwcBkRxi2WGy4e8nQg9EP5wMG/JKWq5LJEuM1z1Z
w3Qg4jy+3bcTRgV9aniEVrHXP18N94YV4hhnObLq0ldSyyXz62l4yxcBh53DAKL3
KlCDA43EM097ZXefxRYNXczfWLBZd9cazv2n/xisGPq0sfBS1yPwbj1DiLbMfPKt
meI87gvk52aPpn40o/fOQsOtbKPeAG7nR4W5XsD7pgZEHNggrJ27h06c/46eAW0U
N3ylqScIjqr+6oI7QYtrG+aoC+SdBh2KxLfuWQcOVKbiGfj9urECAwEAAaNsMGow
KwYDVR0RBCQwIoIQKi5odWIuZG9ja2VyLmNvbYIOaHViLmRvY2tlci5jb20wDgYD
VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQBoa4JNWO40Sf/9YRqYJM7gE+KP
PNHPG2yAsL7fDDfT/+eZEg63EgyFGrVYiudtYhD8pylNMzZ372Q+xF4WJ22DlVt0
QsyvoLQ3pKrANkZSptUPSE6ddepR4QOFPDUz82d4oHhK+JfV0QFjZ9AxYctxW/Rd
trv+La8E0kjYfaANqBIf9+t+xcI/guLEJoS1n5tuBfthweeVnFCv1vOJISozlriT
JcBShWPsQ+/wNPM+2tlrOYhbXr8qOzz8h13T1hszVwf/kRWFvysJODNRQoOZCKSK
YYDlo+Yh4AoAhwO/6zav8S0U5MbB1ZNb6C7LT1R6IkZReqfR/GSEWjMBd8x6
-----END CERTIFICATE-----
subject=/CN=*.hub.docker.com
issuer=/CN=GPCNETWORKCA
---
No client certificate CA names sent
---
SSL handshake has read 974 bytes and written 636 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: D4E09C61BF50592B5E8A460451F43F0F0D0458190DF33DF0EF135BE179A48327
    Session-ID-ctx:
    Master-Key: 07DAFCE2330B101F5F6EB5AF7EE668882211BEE8F060AD66E03896F6CD9249FA1A5A3ABC16463AEE1CE0CA78CDCA42AB
    Start Time: 1537215143
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)

**Comment by chanseokoh** [comment] 2018-09-17 20:49
@naushadamin this shows that your machine itself cannot connect to `registry.hub.docker.com` (cannot verify the server, to be exact), so the issue is clearly unrelated to Jib. It may even the case that you cannot open `https://registry.hub.docker.com` in your browser. I think you should talk to your machine/network administrator to figure out what's going on.

**Comment by TadCordle** [comment] 2018-09-27 19:45
Closing since this issue doesn't seem to be related to Jib and hasn't had any activity lately, feel free to reopen if there are any new developments.

**Closed by TadCordle** 2018-09-27 19:45 UTC
