### ISSUE TITLE
A required class was missing while executing com.google.cloud.tools:jib-maven-plugin

### ISSUE THREAD

**Issue by aibowen** [GoogleContainerTools/jib#2861] opened 2020-10-23 17:10 UTC
jib's version is 2.5.2

the text below were full logs

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.5.2:build (default-cli) on project auth: Execution default-cli of goal com.google.cloud.to
ols:jib-maven-plugin:2.5.2:build failed: A required class was missing while executing com.google.cloud.tools:jib-maven-plugin:2.5.2:build: org/apache/http/conn/Htt
pHostConnectException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.google.cloud.tools:jib-maven-plugin:2.5.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/apache-maven/repository/com/google/cloud/tools/jib-maven-plugin/2.5.2/jib-maven-plugin-2.5.2.jar
[ERROR] urls[1] = file:/D:/apache-maven/repository/com/google/http-client/google-http-client/1.34.0/google-http-client-1.34.0.jar
[ERROR] urls[2] = file:/D:/apache-maven/repository/com/google/http-client/google-http-client-apache-v2/1.34.0/google-http-client-apache-v2-1.34.0.jar
[ERROR] urls[3] = file:/D:/apache-maven/repository/com/google/auth/google-auth-library-oauth2-http/0.18.0/google-auth-library-oauth2-http-0.18.0.jar
[ERROR] urls[4] = file:/D:/apache-maven/repository/com/google/auto/value/auto-value-annotations/1.6.6/auto-value-annotations-1.6.6.jar
[ERROR] urls[5] = file:/D:/apache-maven/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] urls[6] = file:/D:/apache-maven/repository/com/google/auth/google-auth-library-credentials/0.18.0/google-auth-library-credentials-0.18.0.jar
[ERROR] urls[7] = file:/D:/apache-maven/repository/com/google/http-client/google-http-client-jackson2/1.32.1/google-http-client-jackson2-1.32.1.jar
[ERROR] urls[8] = file:/D:/apache-maven/repository/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar
[ERROR] urls[9] = file:/D:/apache-maven/repository/com/google/guava/guava/29.0-jre/guava-29.0-jre.jar
[ERROR] urls[10] = file:/D:/apache-maven/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[ERROR] urls[11] = file:/D:/apache-maven/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-av
oid-conflict-with-guava.jar
[ERROR] urls[12] = file:/D:/apache-maven/repository/org/checkerframework/checker-qual/2.11.1/checker-qual-2.11.1.jar
[ERROR] urls[13] = file:/D:/apache-maven/repository/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar
[ERROR] urls[14] = file:/D:/apache-maven/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
[ERROR] urls[15] = file:/D:/apache-maven/repository/com/fasterxml/jackson/core/jackson-databind/2.11.2/jackson-databind-2.11.2.jar
[ERROR] urls[16] = file:/D:/apache-maven/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.2/jackson-annotations-2.11.2.jar
[ERROR] urls[17] = file:/D:/apache-maven/repository/com/fasterxml/jackson/core/jackson-core/2.11.2/jackson-core-2.11.2.jar
[ERROR] urls[18] = file:/D:/apache-maven/repository/org/ow2/asm/asm/8.0.1/asm-8.0.1.jar
[ERROR] urls[19] = file:/D:/apache-maven/repository/com/google/cloud/tools/jib-build-plan/0.4.0/jib-build-plan-0.4.0.jar
[ERROR] urls[20] = file:/D:/apache-maven/repository/com/google/cloud/tools/jib-plugins-extension-common/0.2.0/jib-plugins-extension-common-0.2.0.jar
[ERROR] urls[21] = file:/D:/apache-maven/repository/com/google/cloud/tools/jib-maven-plugin-extension-api/0.4.0/jib-maven-plugin-extension-api-0.4.0.jar
[ERROR] urls[22] = file:/D:/apache-maven/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[23] = file:/D:/apache-maven/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
[ERROR] urls[24] = file:/D:/apache-maven/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.24.jar
[ERROR] urls[25] = file:/D:/apache-maven/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[26] = file:/D:/apache-maven/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[27] = file:/D:/apache-maven/repository/org/apache/maven/maven-builder-support/3.5.2/maven-builder-support-3.5.2.jar
[ERROR] urls[28] = file:/D:/apache-maven/repository/org/apache/maven/resolver/maven-resolver-util/1.1.0/maven-resolver-util-1.1.0.jar
[ERROR] urls[29] = file:/D:/apache-maven/repository/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar
[ERROR] urls[30] = file:/D:/apache-maven/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[31] = file:/D:/apache-maven/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
[ERROR] urls[32] = file:/D:/apache-maven/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[33] = file:/D:/apache-maven/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar
[ERROR] urls[34] = file:/D:/apache-maven/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by chanseokoh** [comment] 2020-10-23 18:23
Hi @aibowen,

`org/apache/http/conn/HttpHostConnectException` is in `org.apache.httpcomponents:httpclient`, which is a direct dependency of `com.google.http-client:google-http-client`.
```
[INFO] +- com.google.http-client:google-http-client:jar:1.34.0:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.10:compile
```
Under normal circumstances, Maven should be able to resolve correct transitive plugin dependencies.

Can you delete `D:/apache-maven/repository/` and try again with `mvn -U clean ...`? I see sometimes a corrupted local artifact repository causes this failure.

If that doesn't resolve the issue, I think it's a rare project configuration issue (such as https://github.com/GoogleContainerTools/jib/issues/2321#issuecomment-597431846). For example, something unusual brings in a conflicting version of Google HTTP Client or Apache HttpClient at a lower lever of Maven classloading. Could you share your `pom.xml`? Ideally, a small sample that reproduces this issue.

**Comment by aibowen** [comment] 2020-10-24 03:27
my project contains the `org.apache.httpcomponents:httpclient:jar:4.5.10` now

**Comment by aibowen** [comment] 2020-10-24 03:35
Hi @chanseokoh,

Thank you for you reply in the early morning.
Do i have to replace the `org.apache.httpcomponents:httpclient:jar:4.5.10` with `com.google.http-client:google-http-client`

**Comment by chanseokoh** [comment] 2020-10-26 14:49
This is an unusual situation. I don't think what you are thinking will resolve the issue. Note the issue is at the plugin runtime and independent of your compile-time project dependencies. Normally Maven runs a plugin (in this case, the Jib Maven plugin) in an isolated environment with its own classloader and therefore you shouldn't see this kind of failure. Can you share your `pom.xml`? And often trying to come up with a minimal `pom.xml` that reproduces this issue allows you to pinpoint which is causing the failure (probably you won't need to include any `.java` files, since this looks like an issue in dependency resolution).

**Comment by aibowen** [comment] 2020-10-28 06:09
The image has build success now, I use the company's internal network maven private library connected by vpn on weekends，i feel it is a network problem, i found that the port of telnet maven private libary is not working, the problem of re-execute order after go back to the company is gone, thank you for your reply @chanseokoh

**Comment by chanseokoh** [comment] 2020-10-28 14:53
Thank you for your update. I'll help other users. I'll close this issue.

**Closed by chanseokoh** 2020-10-28 14:53 UTC
