### ISSUE TITLE
second `jibDockerBuild` still assembles and uploads image again

### ISSUE THREAD

**Issue by bdellegrazie** [GoogleContainerTools/jib#2950] opened 2020-12-18 15:51 UTC
**Environment**:
Java 11
Docker 20.10.1

- *Jib version:* 2.7.0
 
- *Build tool:* Gradle 6.7.1

- *OS:* Ubuntu Linux 20.04 LTS

**Description of the issue**:
Two successive builds against the target `jibDockerBuild`
the first build pushes the new image to local docker registry as antipated
the second should be a "do nothing" build - but the build re-assembles the image and 

**Expected behavior**:
Gradle does not reassemble the image but instead checks the manifest on the docker registry - see's they're identical and performs no upload or assembly.

**Steps to reproduce**:

  1. Using Jib helloworld example
  2. ./gradlew wrapper --gradle-version=6.7.1
  3. ./gradlew jibDockerBuild
  4. ./gradlew jibDockerBuild

Build step 4 should produce no change.

**Log output**: 
./gradlew jibDockerBuild

> Task :jibDockerBuild
```
Containerizing application to Docker daemon as gcr.io/example/image-built-with-jib...
Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
Using base image with digest: sha256:50ffbd05df754f787277c8aaa178a586c69d95da29edc318b8c9cbc21ede0cd1

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]

Built image to Docker daemon as gcr.io/example/image-built-with-jib
Executing tasks:
[==============================] 100.0% complete


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
3 actionable tasks: 1 executed, 2 up-to-date

./gradlew jibDockerBuild
> Task :jibDockerBuild

Containerizing application to Docker daemon as gcr.io/example/image-built-with-jib...
Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
Using base image with digest: sha256:50ffbd05df754f787277c8aaa178a586c69d95da29edc318b8c9cbc21ede0cd1

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]

Built image to Docker daemon as gcr.io/example/image-built-with-jib
Executing tasks:
[==============================] 100.0% complete


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by loosebazooka** [comment] 2020-12-18 19:07
`jibDockerBuild` talks to a **docker daemon**. `jib` would be the task that communicates with **docker registry**. The api for communicating with docker daemon is much more primitive that communicating with a registry.

For `jibDockerBuild`, we write down and image to file and then use: `docker load` to load the image into your daemon. This probably why you're seeing this.

If you are using `gradlew jib`with a registry you'll see the performance improvements.

**Comment by chanseokoh** [comment] 2021-02-04 20:00
This is due to the unfortunate limitation of the Docker Engine API (https://stackoverflow.com/a/62003793/1701388). Closing as this is working as intended.

**Closed by chanseokoh** 2021-02-04 20:00 UTC
Labels: area/jib-cli, area/jib-core, area/jib-gradle-plugin, area/jib-maven-plugin, kind/question

**Comment by chanseokoh** [comment] 2021-02-04 20:03
> the second should be a "do nothing" build - but the build re-assembles the image

Just in case, this isn't really true. Jib already has generated the layers and cached them, so it doesn't re-generate them. It's just that Jib has to stream the  entire image into a Docker daemon again.

**Comment by mjustin** [comment] 2021-08-12 18:12
> the second should be a "do nothing" build - but the build re-assembles the image

It looks like this might be the same issue that was mentioned at https://github.com/GoogleContainerTools/jib/issues/1103#issuecomment-427361839:

> Although it does seem like the task should just skip as up-to-date, Jib builds work a bit differently from Docker builds in that the base image is not stored (only layers are cached). Therefore, Jib must at least check if the base image has changed via a request to its registry. We plan to potentially add caching of base images if they are specified via a digest so that in those cases the task could skip the base image check request.
