### ISSUE TITLE
Running a fat jar

### ISSUE THREAD

**Issue by j75** [GoogleContainerTools/jib#1489] opened 2019-02-19 16:58 UTC
**Description of the issue**: Would it be possible to skip copying the **/app/libs**/ , **/app/resources/** and **/app/classes/** in case of running a fat jar ?

**Expected behavior**: just copy the target/my-fat.jar to **appRoot**

**Additional Information**: 
This is not actually an *issue*, it is mostly a suggestion/request for information. I already found a way to run my jar but this plugin copies unnecessary files, wasting space & time.

**Comment by briandealwis** [comment] 2019-02-19 19:00
Duplicate of #530

**Closed by briandealwis** 2019-02-19 19:00 UTC
