### ISSUE TITLE
Support creation of Docker tags

### ISSUE THREAD

**Issue by az82** [GoogleContainerTools/jib#654] opened 2018-07-18 18:07 UTC
**Description of the issue**:
The Jib Gradle/Maven plugins should support the creation of Docker tags without building a new image. This is important for promotion workflows where an image gains new tags while being promoted through the stages.

**Expected behavior**:

Something like the command below creates a tag in the repository `repo`:

```sh
gradle jibTag --source "repo/img:$GIT_COMMIT" --target "repo/img:$GIT_TAG"
```

**Comment by az82** [comment] 2018-07-18 18:42
True indeed - The point would be to decrease the number of tools required to build and therefore make Jib more attractive. If this would be supported, more people could do without Docker, Gcloud or whatever in the build.

**Comment by chanseokoh** [comment] 2018-07-18 19:13
@coollog that's a good point I missed.

@az82 so I believe you can call `gradle jib --image=<MY IMAGE>`, which will cover your use case nicely. I'll close this issue. Feel free to re-open if it doesn't work as you expected.

**Closed by chanseokoh** 2018-07-18 19:13 UTC

**Comment by gluehbirnenkopf** [comment] 2019-02-27 20:10
I still see the point of delivering an image which was already built to  Registry X, retag it and then push it to Registry Y.

I really went through a lot of docs now and it seems that jib only supports multiple tagging during the gradle build.

But in my case the build container which runs in kubernetes is just a temporary provisioned gradle Deamon. So let’s say t some stage my snapshot image from development needs to be tagged and delivered to some Registry Y, it’s simply not possible.

**Comment by chanseokoh** [comment] 2019-02-27 20:19
Hi @gluehbirnenkopf,

> I still see the point of delivering an image which was already built to Registry X, retag it and then push it to Registry Y.

> at some stage my snapshot image from development needs to be tagged and delivered to some Registry Y

Sorry, I didn't get it. Are you saying there is an already built and published image in Registry X and you simply want to "copy" that image to Registry Y, without running Gradle or Jib? Are you basically suggesting a separate CLI tool that'll do the copy?

**Comment by gluehbirnenkopf** [comment] 2019-02-27 20:37
@chanseokoh
Yes, I "just" want to copy an image from registry X to registry Y, but also giving it a new version tag.
The Problem is that I cant simply run a second time jib, as the build infrastructure is dynamically provisioned for every CI build job. Which means JIB would always build new sources.

Example:
Image "registry-x.com/repo/app1:v1-snapshot" gets built with jib in CI to registry-x.
Image "registry-x.com/repo/app1:v1-snapshot" is then at some point of time deployed and tested. If this test is successfull it needs to be marked as a release version and needs to be delivered to the registry Y.

**Comment by gluehbirnenkopf** [comment] 2019-02-27 20:42
If there would be a way to achieve this with jib, perfect! Otherwise I need to look in different toolings.

**Comment by coollog** [comment] 2019-02-27 21:06
Hi @gluehbirnenkopf , this seems like a use case that is outside the scope of Jib, since Jib is intended to be just a container builder for Java. 

For a standalone tool to copy remote images, I would recommend [`crane`](https://github.com/google/go-containerregistry/blob/master/cmd/crane/doc/crane_copy.md). 

If you'd like to copy an image as part of your Gradle build, you could use [Jib Core](https://github.com/GoogleContainerTools/jib/tree/master/jib-core):

```groovy
// Imports Jib Core as a library to use in this build script.
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'com.google.cloud.tools:jib-core:0.1.1'
  }
}

import com.google.cloud.tools.jib.api.Jib
import com.google.cloud.tools.jib.api.Containerizer
import com.google.cloud.tools.jib.api.RegistryImage
import com.google.cloud.tools.jib.frontend.CredentialRetrieverFactory
import com.google.cloud.tools.jib.image.ImageReference

// 'jibcopy' copies a container image from `sourceImage` to `targetImage`.
task('jibcopy') {
  doLast { 
    def sourceImage = '<source image reference>'
    def targetImage = '<target image reference>'
    Jib
        // Starts with the existing image.
        .from(sourceImage)
        // Performs the containerization.
        .containerize(
            Containerizer.to(
                // Tells Jib to containerize to targetImage's registry. 
                RegistryImage
                    .named(targetImage)
                    // Tells Jib to get registry credentials from a Docker config.
                    .addCredentialRetriever(
                        CredentialRetrieverFactory
                            .forImage(ImageReference.parse(targetImage))
                            .dockerConfig())))
    println 'done'
  }
}
```

**Comment by gluehbirnenkopf** [comment] 2019-02-27 21:20
@coollog This is valueable input. I will dive into jib core right after checking crane.
I really like JIB and therefore would like to go with it.
