### ISSUE TITLE
How can I use extraDirectories property correctly in a build.gradle.kts 

### ISSUE THREAD

**Issue by hwiorn** [GoogleContainerTools/jib#2715] opened 2020-08-21 05:20 UTC
**Environment**:

- *Jib version:* 2.5.0
- *Build tool:* Gradle 6.5.1 (Kotlin 1.3.72, Groovy 2.5.11, Ant 1.10.7, JVM 11.0.8)
- *OS:* Ubuntu 20.04.1 LTS

**Description of the issue**:
I tried to use the `extraDirectories.paths.path` to bundle my native shared libraries, but It always said `Val cannot be reassigned`. How can I fix it?

**Steps to reproduce**:

  1. Generate a simple gradle project using `gradle init --type java-application`.
  2. Add a `jib` configuration in `build.gradle.kts`.
  3. Run `./gradlew jibDockerBuild`

**`jib-gradle-plugin` Configuration**: 

A short part of my `build.gradle.kts`.

```kotlin
    
jib {
    from.image = "openjdk:14"
    to.image = "simple_test"
    to.tags = setOf("$version")
    container {
        mainClass = "some.simple.project.App"
        jvmFlags = listOf("-Djava.library.path=${jib.container.appRoot}/native-libs")
        creationTime = "USE_CURRENT_TIMESTAMP"
    }
    extraDirectories {
        //paths.add(ExtraDirectoryParameters("native-libs/linux-amd64", "${jib.container.appRoot}/native-libs"))
        paths {
            path {
                from = "native-libs/linux-amd64"
                into = "${jib.container.appRoot}/native-libs"   
            }
        }
    }
}

```
**Log output**: 

```
✦ ❯ ./gradlew jibDockerBuild 

> Configure project :
e: /home/xx/Projects/XX/build.gradle.kts:109:17: Val cannot be reassigned
e: /home/xx/Projects/XX/build.gradle.kts:109:24: Type mismatch: inferred type is String but Path! was expected

FAILURE: Build failed with an exception.

* Where:
Build file '/home/xx/Projects/XX/build.gradle.kts' line: 109

* What went wrong:
Script compilation errors:

  Line 109:                 from = "native-libs/linux-amd64"
                            ^ Val cannot be reassigned

  Line 109:                 from = "native-libs/linux-amd64"
                                   ^ Type mismatch: inferred type is String but Path! was expected

2 errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 909ms

```

**Additional Information**: 
I use Gradle kotlin DSL now.

**Comment by hwiorn** [comment] 2020-08-24 04:15
@chanseokoh 
Thank  you. Your workaround works.

**Comment by chanseokoh** [comment] 2020-08-24 12:32
Glad it worked. We will keep this open to track the issue with Kotlin.

**Comment by Xaseron** [comment] 2021-07-27 15:04
I stumble upon the same issue. I'll try to explain the cause or what i think the cause is.

```
  public Path getFrom() {
    return from;
  }

  public void setFrom(Object from) {
    this.from = project.file(from).toPath();
  }
```
Kotlin converts getters and setters into properties.
there is a `getFrom` but no set from with the same signature, therefore getFrom is immutable (val).

 Line 109:                 from = "native-libs/linux-amd64"
                            ^ Val cannot be reassigned

Even if there would be a setter it probably has to have the same type.
  Line 109:                 from = "native-libs/linux-amd64"
                                   ^ Type mismatch: inferred type is String but Path! was expected

Maybe adding this can solve the problem:
```
  public void setFrom(Path from) {
    this.from = from;
  }

  public void setFrom(String from) {
    this.from = project.file(from).toPath();
  }
```

**Comment by chanseokoh** [comment] 2021-07-27 21:48
That may fix it, although I vaguely remember there might be a subtle issue with multiple `setFrom()` overrides. But I think ideally this should be resolved by having `ExtraDirectoryParameters.getFrom()` directly return `Property` as in #2727 and #3094.

**Comment by chanseokoh** [comment] 2021-07-28 22:36
That may fix it, although I vaguely remember there might be a subtle issue with multiple `setFrom()` overrides. But I think ideally this should be resolved by having `ExtraDirectoryParameters.getFrom()` directly return `Property` as in #2727 and #3094.

**Comment by mostlylikeable** [comment] 2022-05-27 04:53
for anyone dealing with intellij complaints about supertype access when using `setFrom`, you can workaround that by suppressing the warning to appease intellij:
```kt
    @Suppress("MISSING_DEPENDENCY_SUPERCLASS")
    extraDirectories {
        paths {
            path {
                setFrom("native-libs/linux-amd64")
                into = "${jib.container.appRoot}/native-libs"   
            }
        }
    }
```

**Comment by ddixit14** [comment] 2022-05-31 13:58
Thanks @mostlylikeable for pointing this out!

**Closed** 2022-08-04 20:12 UTC
Labels: p2, kind/user-question, area/jib-gradle-plugin, good first issue

**Comment by ChristianCiach** [comment] 2023-07-20 14:02
You can also just call the setter directly:

```kotlin
    extraDirectories {
        setPaths("src/main/jib")
```
