### ISSUE TITLE
jib can't work,Not found com.google.common.base.Preconditions.checkArgument

### ISSUE THREAD

**Issue by SamPeng87** [GoogleContainerTools/jib#2636] opened 2020-07-28 09:41 UTC
**Environment**:

- *Jib version:* 2.6.0 
- *Build tool:* gradle
- *OS:* macos

**Description of the issue**:
I test with jibDockerBuild
config：
```
   from {
            image = 'docker://openjdk:11.0.2-jdk-slim-stretch'
            auth {
                username= "abc"
                password= "xyz"
            }
        }
        to {
            image = "thisistest"
            tags = ["abc", "latest"]
            auth {
                username= "abc"
                password= "xyz"
            }
        }
        container {
            jvmFlags = ['-Xms512m', '-Xmy:flag=jib-rules']
            mainClass = 'org.springframework.boot.loader.PropertiesLauncher'
            format = 'OCI'
        }
    }
```

error stacktrace:
```
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at com.google.cloud.tools.jib.api.Containerizer.withAdditionalTag(Containerizer.java:161)
        at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.configureContainerizer(PluginConfigurationProcessor.java:850)
        at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.processCommonConfiguration(PluginConfigurationProcessor.java:437)
        at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.createJibBuildRunnerForDockerDaemonImage(PluginConfigurationProcessor.java:126)
        at com.google.cloud.tools.jib.gradle.BuildDockerTask.buildDocker(BuildDockerTask.java:109)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:133)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$5(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
        ... 37 more
```

I don't know this error is buildscript dependencies or code build dependencies..I set that in build.gradle(root)

```
plugins {
    id 'com.google.cloud.tools.jib' version '2.4.0' apply false
}
```

We Build Environment is :

```
------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
+--- org.jfrog.buildinfo:build-info-extractor-gradle:4.4.18
|    +--- org.apache.ivy:ivy:2.2.0
|    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|    +--- commons-io:commons-io:2.2 -> 2.4
|    +--- org.codehaus.groovy:groovy-all:2.4.7
|    +--- org.jfrog.buildinfo:build-info-extractor:2.7.8
|    |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|    |    +--- commons-io:commons-io:2.2 -> 2.4
|    |    +--- commons-lang:commons-lang:2.4 -> 2.6
|    |    +--- org.jfrog.buildinfo:build-info-client:2.7.8
|    |    |    +--- commons-codec:commons-codec:1.8 -> 1.11
|    |    |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|    |    |    +--- commons-io:commons-io:2.2 -> 2.4
|    |    |    +--- org.jfrog.buildinfo:build-info-api:2.7.8
|    |    |    |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|    |    |    |    +--- commons-io:commons-io:2.2 -> 2.4
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.8.1 -> 2.9.10
|    |    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.10
|    |    |    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.10
|    |    |    |    +--- commons-lang:commons-lang:2.4 -> 2.6
|    |    |    |    +--- com.google.guava:guava:18.0 -> 28.1-jre
|    |    |    |    |    +--- com.google.guava:failureaccess:1.0.1
|    |    |    |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    |    |    +--- org.checkerframework:checker-qual:2.8.1
|    |    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.3.2
|    |    |    |    |    +--- com.google.j2objc:j2objc-annotations:1.3
|    |    |    |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.18
|    |    |    |    +--- com.thoughtworks.xstream:xstream:1.3.1
|    |    |    |    |    \--- xpp3:xpp3_min:1.1.4c
|    |    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.1 -> 2.9.10
|    |    |    +--- commons-lang:commons-lang:2.4 -> 2.6
|    |    |    +--- com.google.guava:guava:18.0 -> 28.1-jre (*)
|    |    |    +--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.10
|    |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.12
|    |    |    |    +--- commons-logging:commons-logging:1.2
|    |    |    |    \--- commons-codec:commons-codec:1.11
|    |    |    +--- org.apache.httpcomponents:httpcore:4.4.5 -> 4.4.12
|    |    |    +--- com.thoughtworks.xstream:xstream:1.3.1 (*)
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.1 -> 2.9.10
|    |    +--- com.google.guava:guava:18.0 -> 28.1-jre (*)
|    |    \--- com.thoughtworks.xstream:xstream:1.3.1 (*)
|    \--- commons-lang:commons-lang:2.4 -> 2.6
+--- com.eriwen:gradle-js-plugin:1.12.1 -> 2.14.1
|    +--- com.google.javascript:closure-compiler:v20160208
|    \--- io.jdev.html2js:html2js:0.1
+--- org.springframework.boot:spring-boot-gradle-plugin:2.2.1.RELEASE
|    +--- org.springframework.boot:spring-boot-loader-tools:2.2.1.RELEASE
|    |    +--- org.springframework:spring-core:5.2.1.RELEASE
|    |    |    \--- org.springframework:spring-jcl:5.2.1.RELEASE
|    |    \--- org.apache.commons:commons-compress:1.19
|    +--- io.spring.gradle:dependency-management-plugin:1.0.8.RELEASE
|    \--- org.apache.commons:commons-compress:1.19
+--- com.qmino:miredot-plugin:1.6.2
|    +--- com.qmino:miredot-common:1.0
|    +--- com.qmino:miredot-client:1.6.2
|    +--- com.qmino:miredot-annotations:1.4.0
|    +--- org.apache.maven:maven-plugin-api:2.2.1
|    +--- org.apache.maven:maven-core:2.2.1
|    |    +--- org.apache.maven:maven-settings:2.2.1
|    |    |    +--- org.apache.maven:maven-model:2.2.1
|    |    |    |    \--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    +--- org.codehaus.plexus:plexus-interpolation:1.11
|    |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30
|    |    |         +--- org.codehaus.plexus:plexus-utils:1.4.5 -> 1.5.15
|    |    |         +--- org.codehaus.plexus:plexus-classworlds:1.2-alpha-9
|    |    |         |    \--- junit:junit:3.8.1 -> 4.10
|    |    |         |         \--- org.hamcrest:hamcrest-core:1.1
|    |    |         \--- junit:junit:3.8.1 -> 4.10 (*)
|    |    +--- org.apache.maven.wagon:wagon-file:1.0-beta-6
|    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6
|    |    |         \--- org.codehaus.plexus:plexus-utils:1.4.2 -> 1.5.15
|    |    +--- org.apache.maven:maven-plugin-parameter-documenter:2.2.1
|    |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    +--- org.apache.maven.wagon:wagon-http-lightweight:1.0-beta-6
|    |    |    +--- org.apache.maven.wagon:wagon-http-shared:1.0-beta-6
|    |    |    |    +--- nekohtml:xercesMinimal:1.9.6.2
|    |    |    |    +--- nekohtml:nekohtml:1.9.6.2
|    |    |    |    +--- commons-httpclient:commons-httpclient:3.1
|    |    |    |    |    +--- commons-logging:commons-logging:1.0.4 -> 1.2
|    |    |    |    |    \--- commons-codec:commons-codec:1.2 -> 1.11
|    |    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    +--- org.apache.maven.wagon:wagon-http:1.0-beta-6
|    |    |    +--- org.apache.maven.wagon:wagon-http-shared:1.0-beta-6 (*)
|    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    +--- org.apache.maven.wagon:wagon-webdav-jackrabbit:1.0-beta-6
|    |    |    +--- org.apache.maven.wagon:wagon-http-shared:1.0-beta-6 (*)
|    |    |    +--- org.apache.jackrabbit:jackrabbit-webdav:1.5.0
|    |    |    |    +--- org.apache.jackrabbit:jackrabbit-jcr-commons:1.5.0
|    |    |    |    +--- org.slf4j:slf4j-api:1.5.3 -> 1.7.7
|    |    |    |    \--- commons-httpclient:commons-httpclient:3.0 -> 3.1 (*)
|    |    |    +--- org.slf4j:slf4j-nop:1.5.3
|    |    |    |    \--- org.slf4j:slf4j-api:1.5.3 -> 1.7.7
|    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    +--- org.slf4j:slf4j-jdk14:1.5.6
|    |    |    \--- org.slf4j:slf4j-api:1.5.6 -> 1.7.7
|    |    +--- org.slf4j:jcl-over-slf4j:1.5.6
|    |    +--- org.apache.maven.reporting:maven-reporting-api:2.2.1
|    |    |    +--- org.apache.maven.doxia:doxia-sink-api:1.1
|    |    |    |    \--- org.apache.maven.doxia:doxia-logging-api:1.1
|    |    |    |         \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-30 (*)
|    |    |    \--- org.apache.maven.doxia:doxia-logging-api:1.1 (*)
|    |    +--- org.apache.maven:maven-profile:2.2.1
|    |    |    +--- org.apache.maven:maven-model:2.2.1 (*)
|    |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    +--- org.codehaus.plexus:plexus-interpolation:1.11
|    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    +--- org.apache.maven:maven-model:2.2.1 (*)
|    |    +--- org.apache.maven:maven-artifact:2.2.1
|    |    |    \--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    +--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    +--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    +--- org.apache.maven:maven-repository-metadata:2.2.1
|    |    |    \--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    +--- org.apache.maven:maven-error-diagnostics:2.2.1
|    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    +--- org.apache.maven:maven-project:2.2.1
|    |    |    +--- org.apache.maven:maven-settings:2.2.1 (*)
|    |    |    +--- org.apache.maven:maven-profile:2.2.1 (*)
|    |    |    +--- org.apache.maven:maven-model:2.2.1 (*)
|    |    |    +--- org.apache.maven:maven-artifact-manager:2.2.1
|    |    |    |    +--- org.apache.maven:maven-repository-metadata:2.2.1 (*)
|    |    |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    |    +--- org.apache.maven:maven-artifact:2.2.1 (*)
|    |    |    |    +--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    |    |    +--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    |    |    \--- backport-util-concurrent:backport-util-concurrent:3.1
|    |    |    +--- org.apache.maven:maven-plugin-registry:2.2.1
|    |    |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    |    +--- org.codehaus.plexus:plexus-interpolation:1.11
|    |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    |    +--- org.apache.maven:maven-artifact:2.2.1 (*)
|    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    +--- commons-cli:commons-cli:1.2
|    |    +--- org.apache.maven:maven-plugin-api:2.2.1
|    |    +--- org.apache.maven.wagon:wagon-ssh-external:1.0-beta-6
|    |    |    +--- org.codehaus.plexus:plexus-utils:1.4.2 -> 1.5.15
|    |    |    +--- org.apache.maven.wagon:wagon-ssh-common:1.0-beta-6
|    |    |    |    +--- org.codehaus.plexus:plexus-utils:1.4.2 -> 1.5.15
|    |    |    |    +--- org.codehaus.plexus:plexus-interactivity-api:1.0-alpha-6
|    |    |    |    |    +--- org.codehaus.plexus:plexus-utils:1.4 -> 1.5.15
|    |    |    |    |    \--- org.codehaus.plexus:plexus-component-api:1.0-alpha-16
|    |    |    |    |         +--- org.codehaus.plexus:plexus-classworlds:1.2-alpha-7 -> 1.2-alpha-9 (*)
|    |    |    |    |         \--- junit:junit:3.8.1 -> 4.10 (*)
|    |    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    +--- org.apache.maven:maven-plugin-descriptor:2.2.1
|    |    |    +--- org.apache.maven:maven-plugin-api:2.2.1
|    |    |    +--- org.apache.maven:maven-artifact:2.2.1 (*)
|    |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 -> 1.0-alpha-30 (*)
|    |    +--- org.codehaus.plexus:plexus-interactivity-api:1.0-alpha-4 -> 1.0-alpha-6 (*)
|    |    +--- org.apache.maven:maven-artifact-manager:2.2.1 (*)
|    |    +--- org.apache.maven:maven-monitor:2.2.1
|    |    +--- org.apache.maven.wagon:wagon-ssh:1.0-beta-6
|    |    |    +--- com.jcraft:jsch:0.1.38 -> 0.1.53
|    |    |    +--- org.codehaus.plexus:plexus-utils:1.4.2 -> 1.5.15
|    |    |    +--- org.apache.maven.wagon:wagon-ssh-common:1.0-beta-6 (*)
|    |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|    |    +--- org.codehaus.plexus:plexus-utils:1.5.15
|    |    +--- classworlds:classworlds:1.1
|    |    \--- org.sonatype.plexus:plexus-sec-dispatcher:1.3
|    |         +--- org.codehaus.plexus:plexus-utils:1.5.5 -> 1.5.15
|    |         \--- org.sonatype.plexus:plexus-cipher:1.4
|    +--- com.googlecode.json-simple:json-simple:1.1.1
|    |    \--- junit:junit:4.10 (*)
|    +--- org.apache.poi:poi:3.10-FINAL
|    |    \--- commons-codec:commons-codec:1.5 -> 1.11
|    +--- org.apache.poi:poi-ooxml:3.10-beta2
|    |    +--- org.apache.poi:poi:3.10-beta2 -> 3.10-FINAL (*)
|    |    +--- org.apache.poi:poi-ooxml-schemas:3.10-beta2
|    |    |    \--- org.apache.xmlbeans:xmlbeans:2.3.0
|    |    |         \--- stax:stax-api:1.0.1
|    |    \--- dom4j:dom4j:1.6.1
|    |         \--- xml-apis:xml-apis:1.0.b2
|    +--- org.apache.poi:ooxml-schemas:1.1
|    |    \--- org.apache.xmlbeans:xmlbeans:2.3.0 (*)
|    +--- commons-io:commons-io:2.4
|    +--- org.apache.maven.shared:maven-dependency-tree:2.1
|    |    +--- org.apache.maven:maven-project:2.2.0 -> 2.2.1 (*)
|    |    +--- org.codehaus.plexus:plexus-component-annotations:1.5.5
|    |    \--- org.eclipse.aether:aether-util:0.9.0.M2
|    +--- commons-configuration:commons-configuration:1.10
|    |    +--- commons-lang:commons-lang:2.6
|    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
|    \--- javax.validation:validation-api:1.1.0.Final
+--- gradle.plugin.ua.eshepelyuk.gradle.jaxrsAnalyzer:gradle-jaxrs-analyzer-plugin:0.1.0
+--- com.moowork.gradle:gradle-node-plugin:1.2.0
+--- org.hidetake:gradle-ssh-plugin:2.9.0
|    \--- org.hidetake:groovy-ssh:2.9.0
|         +--- org.slf4j:slf4j-api:1.7.7
|         +--- com.jcraft:jsch:0.1.53
|         +--- com.jcraft:jsch.agentproxy.connector-factory:0.0.9
|         |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.9
|         |    |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |    |    +--- net.java.dev.jna:jna:4.1.0
|         |    |    \--- net.java.dev.jna:jna-platform:4.1.0
|         |    |         \--- net.java.dev.jna:jna:4.1.0
|         |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.9
|         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.9
|         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |    \--- com.jcraft:jsch.agentproxy.pageant:0.0.9
|         |         +--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |         +--- net.java.dev.jna:jna:4.1.0
|         |         \--- net.java.dev.jna:jna-platform:4.1.0 (*)
|         \--- com.jcraft:jsch.agentproxy.jsch:0.0.9
|              +--- com.jcraft:jsch:0.1.49 -> 0.1.53
|              \--- com.jcraft:jsch.agentproxy.core:0.0.9
+--- gradle.plugin.com.boxfuse.client:flyway-release:4.0.3
|    \--- org.flywaydb:flyway-core:4.0.3
+--- com.moowork.gradle:gradle-node-plugin:1.1.1 -> 1.2.0
+--- gradle.plugin.com.ewerk.gradle.plugins:annotation-processor-plugin:1.0.4
+--- gradle.plugin.com.ewerk.gradle.plugins:querydsl-plugin:1.0.10
+--- io.spring.gradle:dependency-management-plugin:1.0.8.RELEASE
+--- com.eriwen:gradle-js-plugin:2.14.1 (*)
\--- com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:2.4.0
     \--- gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:2.4.0
          +--- com.google.http-client:google-http-client:1.34.0
          |    +--- org.apache.httpcomponents:httpclient:4.5.10 (*)
          |    +--- org.apache.httpcomponents:httpcore:4.4.12
          |    +--- com.google.code.findbugs:jsr305:3.0.2
          |    +--- com.google.guava:guava:28.1-android -> 28.1-jre (*)
          |    +--- com.google.j2objc:j2objc-annotations:1.3
          |    +--- io.opencensus:opencensus-api:0.24.0
          |    |    \--- io.grpc:grpc-context:1.22.1
          |    \--- io.opencensus:opencensus-contrib-http-util:0.24.0
          |         +--- io.opencensus:opencensus-api:0.24.0 (*)
          |         \--- com.google.guava:guava:26.0-android -> 28.1-jre (*)
          +--- com.google.http-client:google-http-client-apache-v2:1.34.0
          |    +--- com.google.http-client:google-http-client:1.34.0 (*)
          |    +--- org.apache.httpcomponents:httpclient:4.5.10 (*)
          |    \--- org.apache.httpcomponents:httpcore:4.4.12
          +--- com.google.auth:google-auth-library-oauth2-http:0.18.0
          |    +--- com.google.auto.value:auto-value-annotations:1.6.6
          |    +--- com.google.code.findbugs:jsr305:3.0.2
          |    +--- com.google.auth:google-auth-library-credentials:0.18.0
          |    +--- com.google.http-client:google-http-client:1.32.1 -> 1.34.0 (*)
          |    +--- com.google.http-client:google-http-client-jackson2:1.32.1
          |    |    +--- com.google.http-client:google-http-client:1.32.1 -> 1.34.0 (*)
          |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.9 -> 2.9.10
          |    \--- com.google.guava:guava:28.1-android -> 28.1-jre (*)
          +--- org.apache.commons:commons-compress:1.19
          +--- com.google.guava:guava:28.1-jre (*)
          +--- com.fasterxml.jackson.core:jackson-databind:2.9.10 (*)
          +--- org.ow2.asm:asm:7.3.1
          +--- com.google.cloud.tools:jib-build-plan:0.2.0
          +--- com.google.cloud.tools:jib-plugins-extension-common:0.2.0
          \--- com.google.cloud.tools:jib-gradle-plugin-extension-api:0.3.0
               +--- com.google.cloud.tools:jib-build-plan:0.2.0
               \--- com.google.cloud.tools:jib-plugins-extension-common:0.2.0

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.
```

have any idea help me? I have not any other method resolve this issues

**Comment by loosebazooka** [comment] 2020-07-28 15:45
The only way this would happen is if there is a guava mismatch. It looks like you've done everything right here though. I think we can only help if you create a minimal project that reproduces this issue and share it with us.

**Comment by SamPeng87** [comment] 2020-07-29 03:17
> The only way this would happen is if there is a guava mismatch. It looks like you've done everything right here though. I think we can only help if you create a minimal project that reproduces this issue and share it with us.

ok，I will try if I can do this。I think jib not work good for jfrog。I'm trying to prove this

**Comment by chanseokoh** [comment] 2020-07-31 13:45
The error is definitely due to Gradle loading an old Guava version and means there is an issue in the way Gradle is set up.

And FYI, there are a lot of Jib users using JFrog Artifactory. If you hit any issue using Artifactory, feel free to open a new issue.

**Comment by chanseokoh** [comment] 2020-08-05 00:35
@SamPeng87 any update?

**Comment by chanseokoh** [comment] 2020-08-13 15:16
Closing as not getting back from the user. In any case, I don't think it's an issue in Jib but a user environment issue that can and should be fixed by properly setting up the project.

**Closed by chanseokoh** 2020-08-13 15:16 UTC

**Comment by chanseokoh** [comment] 2020-08-13 15:17
For those coming to thread hitting a similar issue, see this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building).
