### ISSUE TITLE
Cannot upgrade Google HTTP libraries

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#3416] opened 2021-08-13 14:47 UTC
#3415 downgraded Google HTTP libraries to resolve #3058 and #3409. However, we cannot delay upgrading libraries indefinitely.

Moreover, even if we downgraded them, Gradle and Maven can still pull in newer versions depending on how a project is set up. Examples:
- https://github.com/GoogleContainerTools/jib/issues/3409#issuecomment-902360557
- https://github.com/GoogleContainerTools/jib/issues/3058#issuecomment-900681904
- https://github.com/googleapis/google-http-java-client/issues/1409#issuecomment-879819285I

In the last case, we didn't release jib-core with the problematic Google HTTP library version, but Quarkus picked up the latest version; I think jib-core will be more susceptible to version overriding than Jib plugins.

These issues need to be investigated further before we can upgrade the libraries.

**Comment by suztomo** [comment] 2021-08-13 16:54
I assume the challenge is that we cannot reproduce the problem. Is this correct?

**Comment by chanseokoh** [comment] 2021-08-13 17:09
For #3058, yeah, I haven't able to reproduce it. And the root cause is still unknown. Also perplexing is that it's always Gradle.

For #3409, I think I know what exactly is the problem, but I have trouble reproducing this.

**Comment by famod** [comment] 2021-10-01 16:12
In Quarkus, we just ran into a dependency "conflict" because of this: https://github.com/quarkusio/quarkus/pull/20507

I anyone looking at getting the remaining issues fixed upstream? I understand it's hard to reproduce?

**Comment by chanseokoh** [comment] 2021-10-01 19:15
#3409, which caused an outright no-go friction to many people with the "premature end of chunk" error, has been [fixed upstream](https://github.com/googleapis/google-http-java-client/pull/1427). However, as of now, I see they [didn't yet release](https://search.maven.org/search?q=google-http-client) a new version of google-http-client and -apache-v2. I don't know when they will release new versions.

The other issue, #3058, is a very subtle one. It seems to happen to only some small group of people specifically using AWS ECR. Also, I've seen elsewhere that the people hit into the failure out of the Jib context, so it seems like a general problem. It's unclear if it's the fault of AWS or the Apache HttpClient. It's hard to reproduce, and I asked if anyone seeing the failure can contribute their time to debug it with us, but so far, no one responded.

Therefore, for Quarkus, IMO it'd be acceptable to upgrade the Google HTTP libraries to the latest _once_ they release new versions.

**Comment by chanseokoh** [comment] 2021-10-01 19:17
Oh, actually, new versions of Google HTTP libraries published after the fix for #3409 is merged.

**Comment by famod** [comment] 2021-10-03 16:25
Thanks @chanseokoh, just one question:
> New versions of the Google HTTP libraries with the fix are live now.

Are you sure about that? 1.40.0 does not seem to include https://github.com/googleapis/google-http-java-client/pull/1427?

**Comment by chanseokoh** [comment] 2021-10-03 21:25
Actually, it doesn't seem so. I naively thought 1.40.0 included the fix based it was released after the PR is merged. Sorry for the misinformation. Not sure why it wasn't included.

**Comment by chanseokoh** [comment] 2021-10-03 21:28
Sorry, I was dumb. The fix was merged on Sep 23, while 1.40.0 was released on Aug 26.

**Comment by famod** [comment] 2021-10-04 13:24
@chanseokoh alright. Apart from those known issues in newer Google HTTP libs, would anything break if using latest jib-core with 1.38.0 of Google HTTP?

**Comment by chanseokoh** [comment] 2021-10-08 01:05
@famod Google HTTP Client 1.40.1 is released.

**Comment by elefeint** [comment] 2022-08-09 19:09
There were 3 issues that blocked upgrade:
1) premature end of chunk coded message body -- fixed in googleapis/google-http-java-client#1427
2) certificate issue with docker containers stored on AWS S3
    https://github.com/aws/aws-sdk-java/issues/1919
    https://github.com/aws/aws-sdk-java-v2/issues/1786

In any case, Jib can't hold off upgrading core HTTP libraries indefinitely. We should upgrade, and then help users work with AWS support if necessary.

**Closed** 2022-09-02 19:09 UTC
Labels: p2, kind/bug, help wanted, upcoming

**Comment by emmileaf** [comment] 2022-10-28 20:25
`jib-core` 0.23.0, `jib-maven-plugin` 3.3.1, `jib-gradle-plugin` 3.3.1, and `jib-cli` 0.12.0 have been released with the HTTP libraries upgraded.
