### ISSUE TITLE
Indicate when configuration will lead to non-reproducible builds.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1595] opened 2019-04-02 16:36 UTC
like `useCurrentTimestamp`.

We should document this in our docs, and emit a log message?

**Comment by TadCordle** [comment] 2019-04-02 20:31
We do already emit a warning of `useCurrentTimestamp` is set, and we also mention in our docs that using the parameter will affect reproducibility:

>By default, Jib wipes all timestamps to guarantee reproducibility. If this parameter is set to true, Jib will set the image's creation timestamp to the time of the build, which sacrifices reproducibility for easily being able to tell when your image was created.

At the moment, it seems to be the only parameter that doesn't guarantee reproducibility. So I think we can either go ahead and close this issue now, or leave it open until we're done with whatever timestamp adjustments we make.

**Comment by TadCordle** [comment] 2019-09-16 18:41
I think we warn about this everywhere we need to, so I'll close this for now.

**Closed by TadCordle** 2019-09-16 18:41 UTC
