### ISSUE TITLE
LockFileTest failure

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1695] opened 2019-05-06 16:34 UTC
Looking at the test, because the integer update is not an atomic get-and-set, ~~I think it's prone to failure.~~

```
[INFO] Running com.google.cloud.tools.jib.filesystem.LockFileTest
Exception in thread "Thread-1" java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.jib.filesystem.LockFileTest.lambda$testLockAndRelease$0(LockFileTest.java:41)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.117 s <<< FAILURE! - in com.google.cloud.tools.jib.filesystem.LockFileTest
[ERROR] testLockAndRelease(com.google.cloud.tools.jib.filesystem.LockFileTest)  Time elapsed: 0.115 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.jib.filesystem.LockFileTest.testLockAndRelease(LockFileTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by TadCordle** [comment] 2019-05-06 16:43
The non-atomic get and set was intended to make sure the lock file actually works. So maybe the lock file itself is broken?

**Comment by chanseokoh** [comment] 2019-05-06 16:45
Ah... this is intriguing. This is from Kokoro MacOS.

**Comment by TadCordle** [comment] 2019-05-06 16:47
It's strange that it would be flaky. Given the 100ms sleep in the middle of the test procedure, you'd think it'd always fail if it wasn't locking correctly, but it seems to only fail sometimes.

**Comment by chanseokoh** [comment] 2019-05-06 19:15
Oh, I see what happened at the surface. "Thread-1" is the new thread started, and it failed on the assertion (line 41) that checks the existence of the lock file.

```
Exception in thread "Thread-1" java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.jib.filesystem.LockFileTest.lambda$testLockAndRelease$0(LockFileTest.java:41)
```

The file did not exist, so it stopped there. That's why the test ended up with 1.

**Comment by chanseokoh** [comment] 2019-05-06 19:20
Things to check:

1. Try deleting the file while holding the lock. If deletion doesn't fail, that may explain https://github.com/GoogleContainerTools/jib/issues/1695#issuecomment-489740855 and we need to do something different.

1. Assuming the deletion fails: I also see the warning in my IDE that the `FileOutputStream` is never closed. Will closing the stream also close the channel (and subsequently releasing the lock)?
   ```java
       FileLock fileLock = new FileOutputStream(lockFile.toFile()).getChannel().lock();
   ```
   If that is the case, garbage collection may be the cause and we should prevent that.

**Comment by TadCordle** [comment] 2019-05-06 19:23
Just tried, and it looks like deleting the file while the lock is held succeeds.

**Comment by chanseokoh** [comment] 2019-05-06 19:26
> Just tried, and it looks like deleting the file while the lock is held succeeds.

And `Files.exists()` returns false? That is a bit surprising. Then potentially a different thread/process can obtain a new file lock? If so, that sounds like we should never delete the lock file.

> garbage collection may be the cause and we should prevent that.

FTR: but we keep the reference for `fileLock`. If that prevents garbage-collecting `FileChannel` or `OutputStream`, the second theory won't hold. Need to confirm that too.

**Comment by TadCordle** [comment] 2019-05-06 19:34
>And Files.exists() returns false?

At least on Linux, yes. Going to push a commit to my test PR to see if it's different on mac.

**Comment by TadCordle** [comment] 2019-05-06 20:12
(Already discussed this with you, but I'll mention it here for the sake of completeness)

I think I might have an idea. File channels are used to prevent concurrent access between different JVMs, but have no effect between different threads in the same JVM. Which is why we use the `lockMap` with `ReentrantLock`s to prevent race conditions within the same application.

At the end of `LockFile`, we do this:
```
Preconditions.checkNotNull(lockMap.get(lockFile)).unlock();
Files.delete(lockFile);
```
This means, Thread A could release the lock in `lockMap`, Thread B could then acquire the lock file, and then Thread A would proceed to delete the lock file.

**Comment by TadCordle** [comment] 2019-05-06 20:31
Tested using 2 different processes, looks like the lock file can be deleted by a process even while the lock is being held by another process.

**Comment by TadCordle** [comment] 2019-05-06 20:39
Closing the output stream does also release the lock it seems. Same with the `FileChannel`.

**Comment by chanseokoh** [comment] 2019-05-06 21:07
> looks like the lock file can be deleted by a process even while the lock is being held by another process.

This came to our surprise. Perhaps `FileChannel` locks a region of the channel's file and cannot prevent other progress from deleting the file itself. I can't think of a better way than not deleting the lock file at all in our implementation.

**Closed** 2019-05-07 13:30 UTC
Labels: tech debt
