### ISSUE TITLE
[question] Possible to run Containerpilot (or other init processes) as entrypoint?

### ISSUE THREAD

**Issue by cricket007** [GoogleContainerTools/jib#1315] opened 2018-12-06 23:42 UTC
**Description of the issue**:

Consul is useful in service discovery, and rather than running something like [Registrator](https://github.com/gliderlabs/registrator) as a _sidecar_ to the application, would it be possible to add [ContainerPilot](https://github.com/joyent/containerpilot) that is ran _within_ the container as a type of [init system](https://docs.docker.com/engine/reference/run/#specify-an-init-process) (other examples for non service discovery would be `s6` or `tini`)? 

I pick those because I think they have little dependencies. I'm leaving `supervisord` out of the list because that requires Python, IIUC (although, that can be added with one's own base image)

**Expected behavior**: 

- [ ] Install `containerpilot` into image (for simplicity, let's say the base image has it), or better - Can Jib do multistage builds yet?

It is a [statically linked binary](https://github.com/joyent/containerpilot/blob/master/docs/30-configuration/31-installation.md), written in go

> ```dockerfile
> # get ContainerPilot release
> RUN curl -Lo /tmp/cb.tar.gz https://github.com/joyent/containerpilot... \
>     && tar -xz -f /tmp/cb.tar.gz && mv /containerpilot /bin/
> ```

- [x] `contiainerpilot.json` can be added into `src/main/jib/app`
- [x] `ENV CONTAINERPILOT=file:///app/containerpilot.json` can be put into the build system

- [ ]  **Question**: Is this possible?

```dockerfile
ENTRYPOINT ["/bin/containerpilot"]
CMD ["java", "-cp" ...jibStuff...]
```

Or even with a custom entrypoint, are the JVM args exposed to a custom entrypoint script?

I'm leaning towards the thought a custom entrypoint is required to run the config templating command i.e.`/bin/containerpilot -config /app/containerpilot.json5`

**Additional Information**:  Feel free to ask. *Disclaimer* - I have only done a few projects with Containerpilot, but it is required for our containers to work "properly" in our environment and I just copy paste from others' code. At a high level, I think the above are the only steps required.

**Comment by chanseokoh** [comment] 2018-12-07 03:12
> Install containerpilot into image (for simplicity, let's say the base image has it), or better - Can Jib do multistage builds yet?

I don't think we want to do multistage builds. We are rather on the declarative and reproducible-build side. If you want some software unrelated to Java to be pre-installed in the image, generally I think I'd prepare a base image with it. I feel like `containerpilot` doesn't have to be installed as part of a Java build.

> Is this possible?

> Or even with a custom entrypoint, are the JVM args exposed to a custom entrypoint script?

At least it's possible to set a custom `ENTRYPOINT` and `CMD` through `<entrypoint>` and `<args>` (https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#container-object). But if you are asking if you can pass the default Jib entrypoint (`java -cp ...<Jib stuff>`) to some custom script at runtime, unfortunately no, it's not possible. The best bet for now is to remember your default Jib entrypoint and use the fixed value. It may work, but honestly, I cannot really recommend it, because potentially it's possible that in the future we may consider changing the default entrypoint.

> `/bin/containerpilot -config /app/containerpilot.json5`

It's definitely possible to set the entrypoint to this.

**Comment by cricket007** [comment] 2018-12-07 04:33
>  If you want some software unrelated to Java to be pre-installed in the image, generally I think I'd prepare a base image with it.

I agree with this.

If not a multi-stage build, I was thinking the Containerpilot binary could be downloaded and cached in `src/main/jib/bin` via a Gradle task, for example, though? As long as it matched the cpu architecture being built for the container, I think it might work.  

> It's definitely possible to set the entrypoint to this.

>`/bin/containerpilot -config /app/containerpilot.json5`

But this needs to run in a shell to first template out the config file, then the app is ran via `containerpilot java ...`. From what I understand a shell isn't available in the distroless container? Sure, one can change the base image, but I was thinking in the default case. How would one have, say, a "`docker-entrypoint.sh`" equivalent? (I'm guessing this has been answered before)... Would it have to be Groovy scripts? Or is here absolutely when a custom base image is necessary? 

Something like the following could be possible

```dockerfile
FROM gcr.io/distroless/java
ARG CPU_ARCH=x64
COPY containerpilot-$CPU_ARCH /app/bin/containerpilot # containerpilot already downloaded
ONBUILD RUN /app/bin/containerpilot -config /app/containerpilot.json5
ENV CONTAINERPILOT file:///app/containerpilot.json5
ENTRYPOINT ["/app/bin/containerpilot"]
```

Or if using `openjdk` images, of course `curl` or `wget` are available, and an entrypoint shell script can be added...

> pass the default Jib entrypoint (`java -cp ...<Jib stuff>`) to some custom script at runtime, unfortunately no, it's not possible

Not verbatim, exactly, but how about individually the main class, the generated classpath string and ideally the concatenated `jvmArgs` defined though the build plugins? Otherwise, I see the workaround as to just go through just environment variables from the plugins, and applied in an entrypoint script or from [`JAVA_TOOL_OPTIONS`](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html). 

However, again, without a shell in `distroless/java`, I'm not seeing how that could be done.

**Comment by chanseokoh** [comment] 2018-12-07 20:15
> If not a multi-stage build, I was thinking the Containerpilot binary could be downloaded and cached in src/main/jib/bin via a Gradle task, for example, though?

I think it will work with Jib, though it may not be the best approach. You can achieve anything with Gradle. I wouldn't put it under under a src repo though. (In any case, I don't think we will introduce such a task in Jib anytime soon.) Maybe having a base image prepared may be better, depending on your use case, as we discussed.

> From what I understand a shell isn't available in the distroless container? Sure, one can change the base image, but I was thinking in the default case.

> without a shell in distroless/java, I'm not seeing how that could be done.

Regardless of whether you need a shell or not, I suggest you do pick the best base image you need for production, using a fixed tags. Using a fixed SHA may be better, actually. In fact, I can't recommend using distroless for production usage. And if you need a shell, definitely pick a base image that has a shell.

And as I said, I don't think we will make Jib able to remotely download something and putting them into the container anytime soon. It's not likely Jib will become able to install a shell, for example. We are cautious on the image building process becoming too imperative or scripty like `Dockerfile`. However, we did have an internal discussion around whether we would support accepting a ZIP or TAR as part of "extraDirectory", and in that sense, it might make sense to specify a remote ZIP URL. However, so far, we decided to remain on the current "extraDirectory" feature (i.e., just copying the files in the directory as-is). You still have some degree of flexibility and other options. Put what you want under "extraDirectory" (be it a `sh` or not), or prepare a base image. In any case, we won't allow doing imperative things like "copy this to there, then copy this, download this, run this, change file mode, then do this, etc."

**Comment by chanseokoh** [comment] 2018-12-07 20:39
Yeah, that makes sense. Not that they are what I strongly recommend or the best approaches. It's basically that I think those can work depending on use cases. My colleagues may think differently :)

**Comment by chanseokoh** [comment] 2018-12-07 23:54
Okay, I think we can close this issue, for the purpose of tracking open issues. Feel free to reopen if you have questions.

**Closed by chanseokoh** 2018-12-07 23:54 UTC
