### ISSUE TITLE
IOException when building from local base image to docker damon

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1942] opened 2019-08-29 17:21 UTC
When using a docker daemon base image, and building to the docker daemon, the following is thrown:

```
...
Caused by: java.io.IOException: This archive contains unclosed entries.
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:307)
        at com.google.cloud.tools.jib.blob.Blobs.lambda$compress$0(Blobs.java:92)
...
```

**Comment by TadCordle** [comment] 2019-08-29 17:22
I think the problem has something to do with the `Blobs#compress` blob calling `writeTo` twice (once to calculate the digest, and once again written in `TarStreamBuilder`). The solution until we cache local base image layers might be to write the compressed blob out to a temp file, and construct the `CachedLayer` using that, rather than using the `compress`ed Blob twice.

**Comment by chanseokoh** [comment] 2019-08-29 19:06
Just trying to ensure if that's really the cause. What's the actual `Blob` class in this case? `FileBlob` should have no issue calling `writeTo()` multiple times. (Not that it is ideal to rely on this implementation detail.)

**Comment by TadCordle** [comment] 2019-08-29 19:22
Problem blob is:
```
Blobs.compress(Blobs.from(file));
```

Blobs.compress():
```
  public static Blob compress(Blob blob) {
    return Blobs.from(
        outputStream -> {
          try (GZIPOutputStream compressorStream = new GZIPOutputStream(outputStream)) {
            blob.writeTo(compressorStream);
          }
        });
  }
```

**Comment by chanseokoh** [comment] 2019-08-29 19:36
Yeah, so I think the problem is that it is closing `outputStream` in the code above twice, not because `Blobs#compress` calling `writeTo()` twice?

**Comment by TadCordle** [comment] 2019-08-29 19:49
That makes more sense.

**Closed** 2019-08-30 20:52 UTC
