### ISSUE TITLE
jibDockerBuild:multi-platform image building not supported when pushing to Docker engine

### ISSUE THREAD

**Issue by machaleb** [GoogleContainerTools/jib#3692] opened 2022-06-15 13:42 UTC
**Environment**:

- com.google.cloud.tools.jib: 3.2.1
- Gradle 7.3.3
- OS: Linux 4.18.0-348.23.1.el8_5.x86_64 amd64
- JVM: 17.0.3 (Azul Systems, Inc. 17.0.3+7-LTS

**Description of the issue**:
When trying to build multi-arch image for amd64 and s390x platform using `jibDockerBuild`  it gives error as below
```
* What went wrong:
Execution failed for task ':jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: multi-platform image building not supported when pushing to Docker engine
```

**Expected behavior**:
It should build the image using command  `./gradlew jibDockerBuild `

**Steps to reproduce**:

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
[root@flexible1 helloworld]# cat build.gradle
plugins {
  id 'java'
  id 'com.google.cloud.tools.jib' version '3.2.1'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.google.guava:guava:23.6-jre'
}

jib.from {
  image = 'nginx'
  platforms {
    platform {
      architecture = 'amd64'
      os = 'linux'
    }
    platform {
      architecture = 's390x'
      os = 'linux'
    }
  }
}

jib.to {
  image = 'bhagyashrimachale/helloworld:v2'
  auth {
    username = 'bhagyashrimachale'
    password = '*********************'
  }
}

```

**Log output**: 
```
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :jibDockerBuild

Containerizing application to Docker daemon as bhagyashrimachale/helloworld:v2...
Base image 'nginx' does not use a specific image digest - build may not be reproducible
The base image requires auth. Trying again for nginx...
Using base image with digest: sha256:2bcabc23b45489fb0885d69a06ba1d648aeda973fae7bb981bafbb884165e514

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]
Executing tasks:
[========================      ] 80.0% complete
> building image to Docker daemon


> Task :jibDockerBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: multi-platform image building not supported when pushing to Docker engine

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
3 actionable tasks: 3 executed
```
**Additional Information**: 
I am able to build the image using `./gradlew jib` but my requirement is to build it using `./gradlew jibDockerBuild`

**Comment by chanseokoh** [comment] 2022-06-15 14:39
This is a duplicate of #2743. And it's unclear if the Docker daemon supports storing images of different architectures.

**Comment by machaleb** [comment] 2022-06-15 15:06
@chanseokoh I saw the issue which you referred but it is bit unclear. with docker buildx we can build mutli-platform image using `docker buildx build --platform linux/amd64,linux/s390x .` How we can do using  `jibDockerBuild`  ?
`jibDockerBuild` is not having same feature as docker buildx?

**Closed** 2022-06-16 14:02 UTC

**Comment by machaleb** [comment] 2022-06-17 04:58
Closing this issue as docker engine doesn't support multiplatform manifest when pushing to it.
@chanseokoh thanks for explanation .

**Comment by abluepoint-dev** [comment] 2023-02-09 09:46
use build

**Comment by MilanObrenovic** [comment] 2023-06-08 21:35
> ```groovy
> auth
> ```

solved it for me. thanks. seems like `jibDockerBuild` only builds a local docker image out of the spring boot app. but `jib` builds the image and pushes to docker hub, and also somehow works on multi platform.

**Comment by alexanderankin** [comment] 2024-06-15 10:18
this has been fixed, see https://github.com/GoogleContainerTools/jib/issues/2743#issuecomment-2142601350
