### ISSUE TITLE
Failed to publish image with new tag to Sonatype Nexus3 v3.29.2

### ISSUE THREAD

**Issue by echupriyanov** [GoogleContainerTools/jib#3057] opened 2021-02-15 11:58 UTC
**Environment**:

- *Jib version:* 2.7.1
- *Build tool:* Maven
- *OS:* Alpine Linux in container

**Description of the issue**:
 We are building Docker images and publish them to the Nexus Docker Registry as a part of CI process.
Registry is configured with disabled redeployment, and our images are uniquely tagged with pipeline id, to avoid confusion with image/app versions.

But, even with unique image tag I'm getting the following error:
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:build (default-cli) on project adhocer-taxon-desc-back: Tried to push image manifest for coe-dcr.vimpelcom.global/test-maven-project:1.1.1_275 but failed because: other: blob upload invalid | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 400 Bad Request
[ERROR] PUT https://coe-dcr.vimpelcom.global/v2/test-maven-project/manifests/1.1.1_275
[ERROR] {"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"blob upload invalid","detail":"Repository does not allow updating assets: coe-docker"}]}
```
**Expected behavior**:

Image tagged and published in Nexus Docker Registry

**Steps to reproduce**:

  1. Configure projects pom.xml with approprieate jib. plugin configuration
  2. Setup Nexus Docker Registry with disabled re-deployment
  3. Try to build/publish image

**`jib-maven-plugin` Configuration**: 
```xml
            <plugin>
              <groupId>com.google.cloud.tools</groupId>
              <artifactId>jib-maven-plugin</artifactId>
              <version>2.7.1</version>
              <configuration>
                <from>
                  <image>coe-dcr.vimpelcom.global/openjdk:8u111-jdk-alpine</image>
                </from>
                <to>
                  <image>coe-dcr.vimpelcom.global/test-maven-project:${env.VERSION}</image>
                  <auth>
                    <username>${env.NEXUS_MAVEN_USER}</username>
                    <password>${env.NEXUS_MAVEN_PASSWORD}</password>
                  </auth>
                </to>
                <appRoot>/app></appRoot>
                <format>OCI</format>
                <container>
                  <environment>
                    <PROJECT_DIR>/app</PROJECT_DIR>
                    <MAIN_CLASS>ru.beeline.mircoservices.adhocer_taxon_desc.DimTaxonDescApplication</MAIN_CLASS>
                  </environment>
                  <jvmFlags>
                    <jvmFlag>$JVM_FLAGS</jvmFlag>
                  </jvmFlags>
                  <args>
                    <arg>$APP_FLAGS</arg>
                  </args>
                </container>
              </configuration>
            </plugin>            
```

**Comment by echupriyanov** [comment] 2021-02-15 12:15
Note: [kaniko](https://github.com/GoogleContainerTools/kaniko) is working perfectly in the same setup

**Comment by chanseokoh** [comment] 2021-02-16 15:32
Hi @echupriyanov,

We learned in the past that disabling redeployment in Sonatype Nexus prevents updating any assets, including existing images (technically speaking, "image manifests", which are simple JSON files). Using a fresh new tag doesn't matter, because the asset in question is the manifest.

What's happening in your case is that, because of Jib's strong reproducibility, consecutive Jib builds are generating the exact same manifest JSON (i.e., the image SHA digest doesn't change), and pushing the manifest fails because Nexus prevents updating existing manifests (images). Note that the only way to add a new tag with the Docker Registry API is to push a new manifest. Kaniko doesn't hit this issue because it always generates a new, different image whenever it builds an image.

For example, if I push the same image with different tags using the Docker CLI to Nexus with redeployment disabled, it fails with the same error message.
```
$ docker tag busybox localhost:5443/busybox:mytag1
$ docker tag busybox localhost:5443/busybox:mytag2
$ docker push localhost:5443/busybox:mytag1
The push refers to repository [localhost:5443/busybox]
6b245f040973: Pushed 
mytag1: digest: sha256:56853b711255f4a0bc7c44d2158167f03f64ef75a22a0249a9fae4703ec10f61 size: 527
$ docker push localhost:5443/busybox:mytag2
The push refers to repository [localhost:5443/busybox]
6b245f040973: Layer already exists 
blob upload invalid: blob upload invalid
```

From my perspective, [it's arguable that disabling redeployment should also prevent adding a new tag for an existing image](https://github.com/GoogleContainerTools/jib/issues/2395#issuecomment-616755454). I don't know if Nexus intended it, or it's just what it is due to the server locking down every existing assent.

In any case, Jib is working correctly as intended. I'll close the issue.

There are some workarounds you can think of, depending on your situation.
- Just don't push if you are not building a different image. ([`-Djib.skipExistingImages`](https://github.com/GoogleContainerTools/jib/blob/master/proposals/tags-on-existing-images.md) may be useful.]
- Always create a different image (manifest). For example, using [USE_CURRENT_TIMESTAMP](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago). Of course, this affects reproducibility.

**Closed by chanseokoh** 2021-02-16 15:32 UTC

**Comment by echupriyanov** [comment] 2021-02-16 18:16
Great thanks for clarification! Will try suggested workarounds
