### ISSUE TITLE
Sorting files before adding to layers does not seem really worth

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1050] opened 2018-09-27 14:57 UTC
In `GradleLayerConfigurations` and `MavenLayerConfigurations`, we have

```java
    // Sorts all files by path for consistent ordering.
    Collections.sort(dependenciesFiles);
    Collections.sort(snapshotDependenciesFiles);
    Collections.sort(resourcesFiles);
    Collections.sort(classesFiles);
    Collections.sort(extraFiles);
```

The files (paths) being sorted are top-level files and directories, and if a directory, files in the directory will be added recursively.

Therefore, sorting affects only the top-level files. I just noticed that files in sub-directories are added in a random order.

Should we just remove sorting, as it's not much useful in this regard?

**Comment by coollog** [comment] 2018-09-27 17:36
Yes, I believe this is fine to remove once we switch over to the new cache mechanism in #1047, since the new cache mechanism takes care of ordering in itself, whereas I believe the current cache mechanism uses the ordering it is given (meaning layer entries in different orders would not match cached layers by their metadata).

**Comment by chanseokoh** [comment] 2018-09-27 18:35
If so, I think the current cache mechanism is losing cache opportunities. `LayerConfiguration.addEntryRecursive()` does `Files.list()` recursively, not doing any sorting, resulting in an random order of layer entry addition. That said, the sorting doesn't make much difference.

Rather, it may make more sense to do the sorting inside `addEntryRecursive()`.

**Comment by coollog** [comment] 2018-09-27 18:45
Hmm, that might be a regression from changing the way `LayerConfiguration` was built. I think we could have `LayerConfiguration` have a set of `LayerEntry`s rather than a list and sort at the points at which sorting is needed - when caching and when building the layer. I think these should be separate because the caching needs sorting for serializing the set of `LayerEntry`s in a deterministic manner, whereas the layer building needs sorting to guarantee reproducibility. Even if sorting was added to `LayerConfiguration` itself, the layer building would still need to perform an extra sort since the layer building adds parent directories for all paths, which need to be added in the same sort order.

**Comment by chanseokoh** [comment] 2018-09-27 20:12
> Yes, I believe this is fine to remove once we switch over to the new cache mechanism in #1047

Double-checking: we can remove sorting after merging #1047, right?

**Comment by coollog** [comment] 2018-09-27 20:45
Yes, #1047 has been merged. The sorting can be removed.

**Closed** 2018-09-27 22:39 UTC
