### ISSUE TITLE
Jib container registry push to GCR failed due to credentials 

### ISSUE THREAD

**Issue by sankar22222** [GoogleContainerTools/jib#1617] opened 2019-04-10 21:17 UTC
**Description of the issue**: Jib build push failed due to following error
Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.2:build (default-cli) on project demogcp: Build image failed, perhaps you should make sure your credentials for 'gcr.io' are set 
up correctly: Unauthorized forgcr.io/storageproject-12345/demogcp: 401 Unauthorized

I have already set it up docker-credential-gcr as well . So this is unexpected behavior. if i call from command line it works . It only fails on Cloud build steps

**Expected behavior**: Image should be pushed without error

**Steps to reproduce**: Put jib steps on Cloud build yaml and it will fail
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['compile','com.google.cloud.tools:jib-maven-plugin:build', '-Djib.to.image=gcr.io/storageproject-12345/demogcp:v1']
images: ['gcr.io/storageproject-12345/demogcp:v1']

More logs follows

Downloaded from central: https://repo.maven.apache.org/maven2/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar (2.7 MB at 1.6 MB/s)
Step #1: [INFO]
Step #1: [INFO] Containerizing application to gcr.io/storageproject-12345/demogcp:v1...
Step #1: [INFO] Retrieving registry credentials for gcr.io...
Step #1: [INFO] Getting base image gcr.io/distroless/java:8...
Step #1: [INFO] Building dependencies layer...
Step #1: [INFO] Building resources layer...
Step #1: [INFO] Building classes layer...
Step #1: [INFO]
Step #1: [INFO] ------------------------------------------------------------------------
Step #1: [INFO] BUILD FAILURE
Step #1: [INFO] ------------------------------------------------------------------------
Step #1: [INFO] Total time:  01:08 min
Step #1: [INFO] Finished at: 2019-04-10T20:47:59Z
Step #1: [INFO] ------------------------------------------------------------------------
Step #1: [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.2:build (default-cli) on project demogcp: Build image failed, perhaps you should make sure your credentials for 'gcr.io' are set 
up correctly: Unauthorized forgcr.io/storageproject-12345/demogcp: 401 Unauthorized
Step #1: [ERROR] {"errors":[{"code":"UNAUTHORIZED","message":"Not Authorized."}]}
Step #1: [ERROR] -> [Help 1]
Step #1: [ERROR]

**Comment by chanseokoh** [comment] 2019-04-10 21:24
Hi @sankar22222,

This should have worked on Cloud Build, but currently fails unfortunately. Please see #1500 for possible workarounds. Closing as a duplicate of #1500.

**Closed by chanseokoh** 2019-04-10 21:24 UTC
