### ISSUE TITLE
Can it directly refer to Dockerfile to build the image?

### ISSUE THREAD

**Issue by ningyu1** [GoogleContainerTools/jib#657] opened 2018-07-19 02:25 UTC
Use the Dockerfile that already exists in the project to generate the docker image directly at package time?
No relevant instructions were found in the document. 
If so, please provide a link, thanks.

**Comment by coollog** [comment] 2018-07-19 03:05
Hi @ningyu1 , Jib is intended to allow Java developers to use the tools they are familiar with to build containers for their Java applications. Dockerfiles, by design, are not supported. Is there something you are doing in your Dockerfile that you need?

**Comment by ningyu1** [comment] 2018-07-19 03:19
@coollog Yes, my dockerfile has some extra processing.

**Comment by coollog** [comment] 2018-07-19 13:02
Yes, you would need to add the corresponding XML description.

**Comment by breandan** [comment] 2018-07-19 15:16
The [Gradle DSL](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#example) is pretty nice. I wonder if there is a way to support a small subset of the Docker instructions so that it closely resembles the `Dockerfile` syntax...

**Comment by briandealwis** [comment] 2018-07-19 15:45
What additional steps are you performing @breandan?

**Comment by coollog** [comment] 2018-08-29 21:02
Closing unless there's any instructions that need support in Jib.

**Closed by coollog** 2018-08-29 21:02 UTC
