### ISSUE TITLE
Jib build fails to older versions of docker-registry

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#701] opened 2018-07-24 15:10 UTC
**Description of the issue**:

Jib fails to older versions of docker registry, whereas a current version of the docker client is able to push.

The following versions fail:
  - 2.1: `400 Bad Request`, `{"errors":[{"code":"TAG_INVALID","message":"manifest tag did not match URI"}]}`
  - 2.2: `400 Bad Request`, `{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}`

The following versions succeed:
  - 2.3, 2.4, 2.5, 2.6

**Expected behavior**:

**Steps to reproduce**:

Start the registry:
```sh
docker run -it - -rm -p 5000:5000 registry:2.1
```

Push an example project (note: requires `allowInsecureRegistries=true`):
```sh
mvn -Dimage=localhost:5000/testimage jib:build
```

**Comment by briandealwis** [comment] 2018-07-24 15:22
With 2.1, the registry log shows the following (but pushing to `localhost:5000/foo/java:latest` produces identical results):
```
ERRO[0011] invalid tag on manifest payload: "" != "latest"  http.request.contenttype=application/vnd.docker.distribution.manifest.v2+json http.request.host=localhost:5000 http.request.id=2fe6e7a1-f232-40ae-a8ca-8957ea6453c6 http.request.method=PUT http.request.remoteaddr=172.17.0.1:41900 http.request.uri=/v2/foo/java/manifests/latest http.request.useragent=jib 0.9.8-SNAPSHOT jib-maven-plugin Google-HTTP-Java-Client/1.23.0 (gzip) instance.id=a2119b5d-9f2f-4577-ac1c-c62075f79043 vars.name=foo/java vars.reference=latest version=v2.1.1
ERRO[0011] response completed with error                 err.code=TAG_INVALID err.message=manifest tag did not match URI http.request.contenttype=application/vnd.docker.distribution.manifest.v2+json http.request.host=localhost:5000 http.request.id=2fe6e7a1-f232-40ae-a8ca-8957ea6453c6 http.request.method=PUT http.request.remoteaddr=172.17.0.1:41900 http.request.uri=/v2/foo/java/manifests/latest http.request.useragent=jib 0.9.8-SNAPSHOT jib-maven-plugin Google-HTTP-Java-Client/1.23.0 (gzip) http.response.contenttype=application/json; charset=utf-8 http.response.duration=6.8127ms http.response.status=400 http.response.written=79 instance.id=a2119b5d-9f2f-4577-ac1c-c62075f79043 vars.name=foo/java vars.reference=latest version=v2.1.1
```

With 2.2:
```
ERRO[0085] response completed with error                 err.code=MANIFEST_INVALID err.detail=missing signature key err.message=manifest invalid go.version=go1.5.2 http.request.contenttype=application/vnd.docker.distribution.manifest.v2+json http.request.host=localhost:5000 http.request.id=a6cb438a-1edd-4bf8-b010-cd61f5624f79 http.request.method=PUT http.request.remoteaddr=172.17.0.1:41808 http.request.uri=/v2/foo/java/manifests/latest http.request.useragent=jib 0.9.8-SNAPSHOT jib-maven-plugin Google-HTTP-Java-Client/1.23.0 (gzip) http.response.contenttype=application/json; charset=utf-8 http.response.duration=9.3816ms http.response.status=400 http.response.written=82 instance.id=86dad5f4-f7dd-4d1f-b981-4b6600b71460 vars.name=foo/java vars.reference=latest version=v2.2.1
```

**Comment by chanseokoh** [comment] 2018-07-24 15:29
Probably the images before the tag 2.3 are too old and don't support the manifest schema 2.

**Comment by chanseokoh** [comment] 2018-07-24 15:31
So this is basically #698, and the question is if we really want to put resources to be able to create schema 1 images. I'm not so thrilled, TBH.

**Comment by briandealwis** [comment] 2018-07-24 15:38
That does seem to be it: [Docker Registry compatibility notes](https://docs.docker.com/registry/compatibility/) says:
> For registry versions 2.2.1 and below, the registry always stores and serves Schema 1 manifests. Engine 1.10 first attempts to send a Schema 2 manifest, falling back to sending a Schema 1 type manifest when it detects that the registry does not support the new version.

Not supporting deployed and commonly used registries isn't an ideal situation :-(

**Comment by chanseokoh** [comment] 2018-07-24 17:59
Duplicate of #601.

**Closed** 2018-07-25 14:39 UTC
