### ISSUE TITLE
jib unresolved when used in Gradle subprojects block while using plugins block

### ISSUE THREAD

**Issue by alwyn** [GoogleContainerTools/jib#1841] opened 2019-07-12 16:04 UTC
**Description of the issue**:

When using a Gradle plugins block and subsequently configuring jib in a subprojects block of a multi-module build, referring to jib for configuration results in the jib reference being unresolved.

The multi-module example for jib also fails for different reasons when replacing buildScript with plugins.

**Expected behavior**:

jib should be on the classpath and resolved when using it with Gradle plugins block in a subprojects block according to Gradle usage guides.

**Steps to reproduce**:
Example build using kotlin-dsl:
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    val springBootVersion = "2.1.6.RELEASE"
    val jibVersion = "1.3.0"

    base
    kotlin("jvm") version embeddedKotlinVersion apply false
    id("org.springframework.boot") version springBootVersion apply false
    id("org.jetbrains.kotlin.plugin.spring") version embeddedKotlinVersion apply false
    id("com.google.cloud.tools.jib") version jibVersion apply false
}

allprojects {
    group = "someproject"
    version = "1.0"

    repositories {
        jcenter()
    }
}

dependencies {
    subprojects.forEach {
        archives(it)
    }
}

subprojects {
    apply(plugin = "com.google.cloud.tools.jib")

    val imageBase: String by project
    val imageOrg: String by project
    val imageName = "$imageOrg/${rootProject.name}"
    val imageTags: String by project

    val imagePorts: String by project

    jib {
        from {
            image = imageBase
        }
        to {
            image = imageName
            if (project.hasProperty("imageTags")) {
                tags = imageTags.split(",").toSet()
            } else {
                tags = setOf(version.toString(), "latest")
            }
        }
        container {
            useCurrentTimestamp = true
            ports = imagePorts.split(",")
        }
    }

    tasks {
        withType<KotlinCompile> {
            kotlinOptions {
                freeCompilerArgs = listOf("-Xjsr305=strict")
                jvmTarget = "1.8"
            }
        }
    }
}

```
**Environment**: 
Ubuntu 18.04
Gradle 5.5.1
Java 11
Kotlin 3.x

**Log output**:
* What went wrong:
Script compilation errors:

  Line 39:     jib {
               ^ Unresolved reference: jib

  Line 40:         from {
                   ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                       public inline fun <reified T : VersionControlSpec> VcsMapping.from(noinline configureAction: TypeVariable(T).() -> Unit): Unit defined in org.gradle.kotlin.dsl

  Line 41:             image = imageBase
                       ^ Unresolved reference: image

  Line 44:             image = imageName
                       ^ Unresolved reference: image

  Line 46:                 tags = imageTags.split(",").toSet()
                           ^ Unresolved reference: tags

  Line 48:                 tags = setOf(version.toString(), "latest")
                           ^ Unresolved reference: tags

  Line 52:             useCurrentTimestamp = true
                       ^ Unresolved reference: useCurrentTimestamp

  Line 53:             ports = imagePorts.split(",")
                       ^ Unresolved reference: ports

**Comment by loosebazooka** [comment] 2019-07-15 18:43
@alwyn We're not exactly experts on the kotlin-gradle configs, so we don't have any good answers just from looking at this. I assume it's either some weird config error or something about kotlin interactions that we might be missing. Any chance you could provide us with a project to test on our side so we can figure it out.

**Comment by chanseokoh** [comment] 2019-07-15 19:45
> The multi-module example for jib also fails for different reasons when replacing buildScript with plugins.

If you are talking about [this example](https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module), I verified the following configuration works. So in general, subprojects should work when using `plugins` block. I also wonder if it's some weird config error or something related to Kotiln.

```gradle
plugins {
  id 'java'
  id 'org.springframework.boot' version '2.0.3.RELEASE' apply false
  id 'io.spring.dependency-management' version '1.0.6.RELEASE' apply false
  id 'com.google.cloud.tools.jib' version '1.3.0' apply false
}

allprojects {
  repositories {
    mavenCentral()
  }
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'org.springframework.boot'
  apply plugin: 'io.spring.dependency-management'
  apply plugin: 'com.google.cloud.tools.jib'

  sourceCompatibility = 1.8
  targetCompatibility = 1.8

  dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
  }

  // IMPORTANT: Set the environment variable PROJECT_ID to your own Google Cloud Platform project.
  jib.to.image = "gcr.io/${System.getenv('PROJECT_ID')}/${project.name}:${version}"
}
```

```
$ ./gradlew clean
$ ./gradle-build.sh
++ gcloud config list --format 'value(core.project)'
+ export PROJECT_ID=...
+ PROJECT_ID=...
+ ./gradlew jib

Containerizing application to gcr.io/.../hello-service:0.1.0...

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, hello.Application]

Built and pushed image as gcr.io/.../hello-service:0.1.0
Executing tasks:
[==============================] 100.0% complete


Containerizing application to gcr.io/.../name-service:0.1.0...th

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, name.Application]

Built and pushed image as gcr.io/.../name-service:0.1.0
Executing tasks:
[==============================] 100.0% complete


BUILD SUCCESSFUL in 4s
```

**Comment by alwyn** [comment] 2019-07-16 13:52
I'll start with your working example, move it to kotlin-dsl and expand on that.
Will either report back with success or a broken example...

**Comment by chanseokoh** [comment] 2019-07-18 19:02
@alwyn sure, you can leave this open. I am also curious to hear what they will say. This seems like straight conversion to Kotlin.

And leave a new comment instead of updating an old one, since that way we get email notification. I almost missed your update.

**Comment by chanseokoh** [comment] 2019-08-02 03:18
@alwyn any update from the Gradle side?

**Comment by alwyn** [comment] 2019-08-02 14:27
Yes, we have figured out the problem.

When you want to use a gradle plugin in sub-projects you have to use ```apply(plugin=...```,
but when you do that there are no type-safe accessors generated for the plugin and you
cannot refer to it as ```jib.to...``` or ```jib {...``` any more.

The solution is to add a configuration block for ```JibExtension```.

As in the following example:
```
import com.google.cloud.tools.jib.gradle.JibExtension

plugins {
  id("com.google.cloud.tools.jib") version "1.3.0" apply false
}

subprojects {
  apply(plugin="com.google.cloud.tools.jib")

  configure<JibExtension> {
    from {
      image = ...
    }
    to { ... }
  }
}

**Comment by chanseokoh** [comment] 2019-08-02 14:48
Thanks for the update. This will help other users. But as we saw, this worked in the non-Kotlin way, so I guess the behavior becomes different in Kotlin?

Anyways, I'll close this as this seems unrelated to Jib. Thanks again.

**Closed by chanseokoh** 2019-08-02 14:48 UTC

**Comment by taylorsmithgg** [comment] 2022-11-04 21:31
FYI I just recently built a conventions plugin to standardize our jib configs, using gradle and kotlin that implements jib.
I had similar issues, and a couple of additional ones.
Namely, `apply false` was still attempting to apply jib to my `rootProject`
This kept producing issues with `jib.to.image` not existing, because we do not define it for the `rootProject`.

By dropping `jib` from the `plugins{}` block, and instead importing `JibExtension`, it works as intended.

The working solution:
```
import com.google.cloud.tools.jib.gradle.JibExtension

subprojects {
    apply(plugin="com.google.cloud.tools.jib")

    configure<JibExtension> {
        from {
            image = "123456.dkr.ecr.us-west-2.amazonaws.com/company/java:jdk-11"
        }

        to {
            image = "123456.dkr.ecr.us-west-2.amazonaws.com/company/${rootProject.name}-${project.name}"
            tags = setOf("$version")
        }

        container {
            entrypoint = listOf("INHERIT")
        }
    }
}
```
