### ISSUE TITLE
Support URL references to layers

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1568] opened 2019-03-19 18:53 UTC
The [Docker image manifest specification](https://docs.docker.com/registry/spec/manifest-v2-2/#image-manifest-field-descriptions) supports referencing layers via a URL.  Although this use is rare, supporting URL references to layers within Jib Core, such as via `JibContainerBuilder#addLayer()`, might be an interesting way to allow composing images.

Further, it might be useful for support OCI's nondistributable layers (`application/vnd.oci.image.layer.nondistributable.v1.tar+gzip`) and Docker's notion of _foreign_ layers  (`application/vnd.docker.image.rootfs.foreign.diff.tar.gzip`: _a gzipped tar that should never be pushed_), which are primarily used for distributing non-distributable content like Windows OS for Windows containers.

**Comment by chanseokoh** [comment] 2020-02-10 15:33
FTR: #2215 is mostly a duplicate of #2215. However, I'll leave #2215 open, since #2215 is more focused on potential Windows support and has other useful information.

This issues (#1568) also suggests changing the Jib Core API for setting a URL (which is not really required to enabled #2215).

**Closed** 2022-08-08 19:16 UTC
Labels: area/jib-maven-plugin, area/jib-core, p4, area/jib-gradle-plugin, area/jib-cli, kind/feature
